### ISSUE TITLE
Create grunt module which automatically inserts aliases

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#101]
For a given module:
- Count the number of instances of a given un-minifiable term, e.g. `navigator.xxx`
- Determine if it would be more efficient to assign a variable alias, `var navigatorAlias = navigator`
- Automatically insert that code prior to minification

**Comment by paulboocock** [comment]
Moving away from grunt and towards rollupjs. Lots of new features will emerge through that change so closing this with the idea of opening new build process opens up in the near future.
