### ISSUE TITLE
Add support for custom headers

### ISSUE THREAD

**Issue by paulboocock** [snowplow/snowplow-javascript-tracker#1010]
**Is your feature request related to a problem? Please describe.**
Some users want to place the Snowplow collector behind an authenticated gateway which requires custom headers to be sent with the request. Currently, the tracker is unable to send requests successfully to this as there is no way to easily add custom headers to the request.

**Describe the solution you'd like**
Create a configuration option that allows for custom headers to be added, and functions add and remove to alter them at runtime.

**Additional context**
https://discourse.snowplowanalytics.com/t/api-key-authentication/5716

**Comment by shalinibnair** [comment]
@paulboocock , how to do this for react native tracker

**Comment by AlexBenny** [comment]
FYI @shalinibnair, [here](https://github.com/snowplow/snowplow-android-tracker/issues/276#issuecomment-1217884218) replied to the same request.
