### ISSUE TITLE
Does Snowplow JS Tracker work in Apache Cordova projects?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#107]
I will talk you through this one.

**Comment by paulboocock** [comment]
PhoneGap is now Apache Cordova. 
Renamed the ticket and moved to a "Question" format, potentially a good issue for community to answer if we don't get the opportunity to test this.

**Comment by paulboocock** [comment]
Closing as there's been little to no interest in this for 7 years. Mobile has moved on quite a bit in that time, with Xamarin, React Native and Flutter taking hold when it comes to cross platform mobile frameworks.
