### ISSUE TITLE
Update ContextGenerator function return type to also accept SelfDescribingJson list and undefined

### ISSUE THREAD

**Issue by af-tomwilkins** [snowplow/snowplow-javascript-tracker#1070]
**Describe the bug**
ContextGenerator functions can be passed to `addGlobalContext`. The type definition of `ContextGenerator` is as follows:

```ts
type ContextGenerator = (args?: ContextEvent) => SelfDescribingJson;
```

This constraint doesn't appear to reflect what's possible with Context Generators:

* The example in the [browser tracker documentation](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/browser-tracker/browser-tracker-v3-reference/tracking-events/#global-context) shows a context generator conditionally returning SelfDescribingJson
* It also appears to be possible to use a ContextGenerator to return a list of SelfDescribingJson

My suggestion is to update the type definition to be this:
```ts
type ContextGenerator = (args?: ContextEvent) => SelfDescribingJson | SelfDescribingJson[] | undefined;
```

**To Reproduce**

Using the example from then documentation should redline in an IDE using TypeScript.

```ts
import { addGlobalContexts } from '@snowplow/browser-tracker';
const contextGenerator = (args) => {
  if (args.eventType == 'pv') {
    return {
      schema: 'iglu:com.acme.marketing/some_event/jsonschema/1-0-0',
      data: { test: 1 },
    };
  }
};
addGlobalContexts([contextGenerator]);
```

**Expected behavior**
`addGlobalContexts` should accept ContextGenerator functions that return SelfDescribingJson, a SelfDescribingJson list, or `undefined`.

**Comment by paulboocock** [comment]
@matus-tomlein could you look at this for v3.3?
