### ISSUE TITLE
Add Service Worker Support

### ISSUE THREAD

**Issue by albert-gonzalez** [snowplow/snowplow-javascript-tracker#1076]
Hi!

**Is your feature request related to a problem? Please describe.**
We have a Chrome extension that sends events using your lib in the foreground (called **content script**) and in the background (a **service worker**). In the foreground, we can use your **browser tracker** without problems, but we can't use this in the **service worker** due to these issues:
- Browser Tracker needs a **window** object to work, and service workers don't have it.
- Browser Tracker uses **XHR** to send events, and service workers use **fetch** only. 

We developed a workaround to send events in the background using the **Core Tracker** and a port of the **Node Emitter**, but using **fetch** instead of **got**.

**Describe the solution you'd like**
It would be nice if your library supported service workers.

Thank you for your time!

**Comment by kamil-cf** [comment]
Any updates on this issue? We could use node-tracker for now just to make it works, but it doesn't send a lot of useful properties that JS tracker used to send.
