### ISSUE TITLE
Add ability to modify links allowing cross-domain tracking

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#109]
A common requirement in web analytics is to track users across multiple domains but without resorting to 3rd party cookies. This is important if e.g. a customer journey spans two separate domains, A and B, and you want to track that journey across both domains.

The approach taken by Google analytics (documented very clearly [here](https://developers.google.com/analytics/devguides/collection/analyticsjs/cross-domain)) is to take read the cookie ID on domain A and append it to all links to domain B as a query string parameter. On domain B, you can then read the value from the landing page query string parameter and write it to the Snowplow cookie on B.

Google provides a number of helper functions to make it easier to implement this:

1. A function for retrieving the first party cookie ID. (The domain user ID in our case): `tracker.get('clientId');`
2. A function that returns both the first party cookie ID and a hashed timestamp. This is to deal with the case of a user who shares a link (with their cookie ID) with other people in their network - which would otherwise confuse Google into thinking all those different people are really the same person. 
3. A set of `decorate` utility methods, to simplify appending the cookie values to links from A to B

It's not clear to me what the best approach would be for Snowplow. Clearly we can piggyback off the `setUserIdFromReferrer` that @fblundun has already built. However, I think that rather than populating the `user_id` field in the database, we should define two new `cookie_sync` event type:

1. A 'cookie send' event when a link is clicked with the cookie ID appended
2. A 'cookie received' event when a landing page is loaded with a cookie ID on the querystring

Rather than pass a hash of the timestamp, we could pass the transaction ID of the 'cookie send' event onto the query string and include it in the definition of the cookie received event. That way, it'd be trivial in the SQL to filter out all sync events where the cookie recieved is more than a certain amount of time after the cookie send. (Which we can assume are cases where users have shared links with cookie IDs on the query string.)

@alexanderdean @fblundun - if you think the above approach sounds sensible, we should probably schedule this for after link tracking is delivered, and work on a proper spec. (So break this ticket up into multiple tickets for the individual methods. Shall we have a brainstorm to thrash out a spec once @alexanderdean is back from NYC?

**Comment by alexanderdean** [comment]
We should probably namespace our querystring variables to reduce chance of collision:

    sp.duid=xxx&sp.dtm=xxx

**Comment by fblundun** [comment]
How about this API:

```javascript
{
    ...
    // Only decorate links which include the string "target.com"
    crossDomain: function (elt) {
        return /target.com/.test(elt.href);
    }
    ....
}
```

This would give users full control over which links get decorated.

**Comment by fblundun** [comment]
We should also add a public method to decorate links in case new ones get added to the page after the tracker has loaded.

**Comment by alexanderdean** [comment]
Good thinking. This looks really nice to me. I think we should call it `crossDomainLinker` because a lot of people will be familiar with the GA terminology. I think for the example function we should show something a little less minimal to help people grok it. Also `elt` is a little oblique as a var name.

**Comment by alexanderdean** [comment]
e.g. a lot of people probably haven't even seen JavaScript's regular expression syntax before!

**Comment by fblundun** [comment]
You're probably right...

```javascript
{
    ...
    // Only decorate links whose HTML id is "crossDomainLink"
    crossDomainLinker: function (linkElement) {
        return linkElement.id === "crossDomainLink"
    }
    ....
}
```

would be better as the introductory example, since it doesn't require any knowledge of JavaScript string methods.

**Comment by alexanderdean** [comment]
Nice, how about:

```javascript
{
    ...
    // Only decorate links whose HTML id is "crossDomainLink"
    crossDomainLinker: function (linkElement) {
        return (linkElement.href === "http://acme.de" || linkElement.id === "crossDomainLink");
    }
    ....
}
```

**Comment by fblundun** [comment]
Looks good!

**Comment by fblundun** [comment]
We decided to use a single querystring parameter of the form "_sp={{duid}.{{dtm}}"

**Comment by alexanderdean** [comment]
Discussion of equivalent in Piwik out of interest: https://github.com/piwik/piwik/issues/2211
