### ISSUE TITLE
Add support for JavaScript version detection

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#11]
This is a bit fiddly:

http://stackoverflow.com/questions/7340726/detecting-version-of-javascript-within-browser

**Comment by paulboocock** [comment]
Not sure about the value of this? We don't really think of sites in terms of JS Version support but more of feature support now. Feature Detection is how sites should be built and usually are, rather the browser/useragent/js version identification.
