### ISSUE TITLE
Fix valid youtube error

### ISSUE THREAD

**Issue by adatzer** [snowplow/snowplow-javascript-tracker#1111]
**Describe**
When embedding a youtube video on a page we may get `MISSING_EMBED_PERMISSION` error, which is not in the enum type [here](https://github.com/snowplow/snowplow-javascript-tracker/blob/4dec01b9a314ca11d88372afa4b2dc67a431ee0d/plugins/browser-plugin-youtube-tracking/src/contexts.ts#L126). 
This results to the event being invalidated as well ([schema](https://github.com/snowplow/iglu-central/blob/cb00a49406207243ae22d282441359735f8850e6/schemas/com.youtube/youtube/jsonschema/1-0-0#L56)). As discussed with @greg-el , there seems to be a mismatch with the error codes mapping [here](https://github.com/snowplow/snowplow-javascript-tracker/blob/4dec01b9a314ca11d88372afa4b2dc67a431ee0d/plugins/browser-plugin-youtube-tracking/src/constants.ts#L45).

**To Reproduce**
Probably by embedding a youtube video without embed permissions.

**Expected behavior**
The event with the youtube error being valid.

**Additional context**
The corresponding youtube schema may need to be patched as well.

**Comment by igneel64** [comment]
@adatzer 
Checked a bit an example implementation and it seems there is the same issue with other error codes as well.
I am wondering if this ever worked 🤔 
What we would need to do is:
1. Either update the mapping and not change the schema. _(A minor change on the tracker and update iglu which can take time)_
2. Change the schema to match the errors produced by the tracker. _(Update only the tracker but with keeping a double mapping logic)_

**Comment by adatzer** [comment]
Good point, you are right! It seems that through the youtube plugin so far, we have never sent an error event that is valid to the schema. 
I am wondering where does [this mapping of error codes](https://github.com/snowplow/snowplow-javascript-tracker/blob/dc8fa2a1df02e74bbb1ee5c313c2b64907b152ea/plugins/browser-plugin-youtube-tracking/src/constants.ts#L43-L49) comes from. Is it based onto external (i.e. youtube) documentation? Or is it our interpretation/choice?

- If the first, then i'd go for option 2, because it means that the schema does not match an "objective" reality.
- If the second, i guess the schema can stay the same and we just change our choise of error codes' naming to match the schema (option 1). In that case though, would we still need a double mapping? (you mentioned this for option 2, but i assumed you meant for option 1 - please do shout if i misunderstood)

What do you think?

**Comment by igneel64** [comment]
It is external and comes from the [reference](https://developers.google.com/youtube/iframe_api_reference#onError).

The double mapping would come from the fact that we do not just send the errors as they arrive from the API _(mapped from numbers to strings),_ but we map them again to fit the custom error codes we have on the schema.
Map 1 = error numbers to message.
Map 2 = youtube message to snowplow message.

Sorry if it is unclear, might be just my way of viewing this 😂

**Comment by igneel64** [comment]
Yeap that is Option 2 in a nutshell! _(I was wrong to say that it would need a double mapping)_
