### ISSUE TITLE
PR to Base64 project to add URL-safe option

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#114]
So that we can remove base64urlencode from our project.

In open-source we are always trying to move code that is non-core out of core, either into separate modules, separate projects or into other people's open-source projects, where the functionality is more widely useful...

**Comment by alexanderdean** [comment]
@fblundun what's the status of this one?

**Comment by fblundun** [comment]
This is no longer necessary since we now have our own base 64 module (which will soon be separately available on npm). Closing...
