### ISSUE TITLE
@snowplow/javascript-tracker is missing `files` in package.json

### ISSUE THREAD

**Issue by AndersCan** [snowplow/snowplow-javascript-tracker#1146]
**Describe the bug**
The files that are published to NPM contain all build files and folders: https://unpkg.com/browse/@snowplow/javascript-tracker@3.8.0/ 

I assume you don't want to publish everything

**To Reproduce**
N/A

**Expected behavior**
Only required folders/files

**Screenshots**
![image](https://user-images.githubusercontent.com/3702766/215754049-4e011232-816f-45bd-81c8-afd41e81e305.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by igneel64** [comment]
Hey @AndersCan :) Thank you for spotting that. 
The `javascript-tracker` is not meant to be installed as an npm package but rather self-hosted or grabbed by a CDN. On our instructions we already point on the specific `dist` files needed. 

On that note though I am going to add a fix for it. You are right, no need to have these files published.

**Comment by AndersCan** [comment]
> ...but rather self-hosted

That was my original plan: `npm install` and copy `dist/` file from `node_modules` to cdn. Not sure how else I would do it (without manually copy+pasting).

I'm now however just using `@snowplow/browser-tracker`

**Comment by igneel64** [comment]
@AndersCan 
We have some guidance on our documentation which describes both the CDN way and the self-hosting way: 
https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/web-quick-start-guide/

If you have any feedback on that or it was hard to find or not clear, please do let us know.
