### ISSUE TITLE
Add disableActivityTracking function

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow-javascript-tracker#1161]
**Is your feature request related to a problem? Please describe.**

In single page apps certain portions of the app we may not want activity tracking.

**Describe the solution you'd like**

The tracker should expose a `disableActivityTracking` method that stops activity tracking.

**Additional context**
For more info see the Discourse thread here: https://discourse.snowplow.io/t/dynamically-turn-off-activity-tracking/8200/5

**Comment by davidher-mann** [comment]
Hi Mike,
any chance that this will make into one of the upcoming releases? It would be a first step to make the tracker more single page app friendly ;)

**Comment by miike** [comment]
@igneel64 is probably in a better position to comment on this one I think - but it is definitely something on our radar.
