### ISSUE TITLE
Domain session index starts at 0 when using opt-out cookie

### ISSUE THREAD

**Issue by matus-tomlein** [snowplow/snowplow-javascript-tracker#1230]
This scenario may happen when the app is using an opt-out cookie to prevent tracking events while the user hasn't given tracking consent:

1. Initialize tracker and set an opt-out cookie (`setOptOutCookie('cookieName')`). The cookie should be enabled.
2. Track any events, these will be discarded by the tracker.
3. Remove the opt-out cookie.
4. Track further events – these events will have domain session index set to 0 (should be 1).

Tested with browser tracker version 3.5.

**Comment by igneel64** [comment]
The issue was resolved in 3.6 https://github.com/snowplow/snowplow-javascript-tracker/pull/1108 
Closing.
