### ISSUE TITLE
Consider status codes <200

### ISSUE THREAD

**Issue by greg-el** [snowplow/snowplow-javascript-tracker#1244]
Only responses with codes >=200 are [considered by the tracker](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/libraries/browser-tracker-core/src/tracker/out_queue.ts#L374). This should be extended to consider status codes 0-199. Although it's probably unlikely we'll see a `1xx`, `0` is not-uncommonly used for fail states (cors error, timeout, connection abortion etc).

This would allow users to choose if they wish not to retry on codes 0-199 with the `dontRetryStatusCodes` option, which currently will do nothing for those values, and simply leave them in the `outQueue`.

[Looking](https://github.com/snowplow/snowplow-javascript-tracker/blame/master/libraries/browser-tracker-core/src/tracker/out_queue.ts#L374) [back](https://github.com/snowplow/snowplow-javascript-tracker/blame/250316f07a31e807d27ab6ca793ac928f5b5e98e/libraries/browser-tracker-core/src/tracker/out_queue.ts#L349) [through](https://github.com/snowplow/snowplow-javascript-tracker/blame/f5568539ac2b7b8f28b03c43430a276bcfbb282d/src/js/out_queue.js#L291) [history](https://github.com/snowplow/snowplow-javascript-tracker/blame/455bf7f1a143cdec648a06a073a719cde8c8a16d/src/js/out_queue.js#L189), I can't see any reason that below 200 was excluded specifically, it just seems to have "evolved" that way over time.

**Comment by miike** [comment]
Totally agree on 1xx onwards.

Are there any genuinely instances where `0` is returned as a HTTP status code from the collector / interpreted by the HTTP libraries we use in trackers? RFC 9110 suggests this would be invalid as it's outside the range (1xx-5xx) and we should treat it as a 5xx (which is fine).

**Comment by greg-el** [comment]
Yeah it won't be coming from the collector itself, and you're right it is technically an invalid code, but things like like [XMLHttpRequest.abort()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort) will result in the request having a `0` status code (which we do when a [request has timed out](https://github.com/snowplow/snowplow-javascript-tracker/blob/de97c3bef9ef4ceccd001ea051eddbf2a05e2c70/libraries/browser-tracker-core/src/tracker/out_queue.ts#L353))

Although interestingly, WhatWG considers 0 an acceptable response code for a couple of situations (https://fetch.spec.whatwg.org/#concept-network-error)
