### ISSUE TITLE
Add episodes.js support for Real User Monitoring

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#125]
Adding support for @stevesouders' Episodes - namely:
- Support a vanilla `episodes.js` install
- When calling `EPISODES.sendBeacon()`, point it to your Snowplow collector
- We extend Snowplow ETL to detect and extract episodes
- Episodes get stored in their own table in Redshift

May not initially support the JSON of `params` which Episodes lets you send with `sendBeacon()`.

Resources:
1. https://code.google.com/p/episodes/source/browse/trunk/episodes.js?r=4
2. http://www.stevesouders.com/episodes/ex1.html
3. http://www.stevesouders.com/episodes/

**Comment by unicast** [comment]
Hey guys! Any chance to get this soon-ish?

**Comment by alexanderdean** [comment]
Hi @unicast - as it stands, the proposed implementation of this ticket is complex (touches many parts of Snowplow), and so is unlikely to get prioritised soon.

Can you think of any alternative approaches that would deliver this support as just a tracker/Iglu Central update?

**Comment by unicast** [comment]
@alexanderdean not sure if I've got it right, do you mean I can integrate this library on my own and send data through the snowplow context?

**Comment by alexanderdean** [comment]
Hey @unicast - I'm not familiar with episodes.js to know - but that feels like it could work?

**Comment by unicast** [comment]
Guess we can close that one, it's already implemented: https://discourse.snowplowanalytics.com/t/measuring-page-load-times-with-the-performance-timing-context-tutorial/100

**Comment by alexanderdean** [comment]
Is there anything in a tool like episodes.js that the Navigation Timing API can't do?

**Comment by paulboocock** [comment]
episodes.js appears dead now and superseeded by other timing options.
