### ISSUE TITLE
Bump browser_context schema to 2-0-0

### ISSUE THREAD

**Issue by adatzer** [snowplow/snowplow-javascript-tracker#1260]
**Additional context**

The issue is described in https://github.com/snowplow/iglu-central/issues/1330 and the corresponding iglu-central PR https://github.com/snowplow/iglu-central/pull/1343.
Once the v2-0-0 of the browser_context schema is released, we should switch to it [here in code](https://github.com/snowplow/snowplow-javascript-tracker/blob/1df5e9f48411720a6449a8882665e490a58cbdbf/libraries/browser-tracker-core/src/tracker/schemata.ts#L2).

**Comment by krzkz94** [comment]
Hi, the new 2-0-0 schema has been released today :)

**Comment by adatzer** [comment]
Hi @krzkz94 ! Indeed! 
The [PR for the corresponding change is approved](https://github.com/snowplow/snowplow-javascript-tracker/pull/1261) already and will be merged for next release (3.17.0)!
