### ISSUE TITLE
Do not set the previous session ID reference in cookies if anonymous tracking is enabled

### ISSUE THREAD

**Issue by matus-tomlein** [snowplow/snowplow-javascript-tracker#1268]
As [reported here](https://discourse.snowplow.io/t/is-sp-id-cookie-a-valid-alternative-to-the-client-session-context/9362/4), in case anonymous tracking with session tracking is enabled, the tracker still stores the reference to the previous session ID in the `_sp_id` cookie. While this is not directly tracked in the event, the information is present in the collector request header and could be used by the cookie enrichment to, in a way, reconstruct the user ID by stitching together the sessions.

In case anonymous tracking is enabled, the tracker should not set the previous session ID reference in cookies.

**Comment by davidher-mann** [comment]
It would be great if this could be part of the next release, to avoid potential privacy implications.
