### ISSUE TITLE
Upgrade uuid which is deprecated since 7.0.0

### ISSUE THREAD

**Issue by leo3620** [snowplow/snowplow-javascript-tracker#1305]
**Is your feature request related to a problem? Please describe.**
I don't have any issue right now but when i do a npm build I have a warning " WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details."

**Describe the solution you'd like**
Upgraded UUID package 

**Describe alternatives you've considered**

**Additional context**
Currently it's 3.4.0 in  @snowplow/browser-tracker-core@3.23.0 and  @snowplow/tracker-core@3.23.0

Thank you

**Comment by matus-tomlein** [comment]
Hi @leo3620, thank you for the suggestion! We plan to upgrade the uuid dependency in the upcoming v4 version of the tracker. The newer version does not support the full list of browsers as the 3.4.0 version does, so it would be a breaking change for the tracker (and thus needs to wait for the v4 release of the tracker).

**Comment by leo3620** [comment]
Thank you @matus-tomlein do you have any plan about when this new release should be available ? Thanks !

**Comment by matus-tomlein** [comment]
We plan to work on it this quarter and hopefully will get the release ready by the end of July.

**Comment by miike** [comment]
@leo3620 Now that the v7 RFC has been approved and it's in the latest version of the `uuid` (as of June in v10) package this is something we're actively investigating.

**Comment by xander-marjoram** [comment]
Hi, is there any update on this? Many thanks

**Comment by matus-tomlein** [comment]
Hi @xander-marjoram, the v4 release of the tracker including this feature is currently in beta and we plan to release it by the end of October.
https://discourse.snowplow.io/t/snowplow-javascript-tracker-v4-beta-release/11463
