### ISSUE TITLE
Unable to set BufferSize when Disabling Anonymous Tracking

### ISSUE THREAD

**Issue by rob-ellison-jet** [snowplow/snowplow-javascript-tracker#1309]
**Is your feature request related to a problem? Please describe.**
Consent and data privacy is very important to follow as such by default we enable anonymous tracking and disable storage by default.
We also want to keep our site performant and reduce the number of network requests. The buffer is the perfect way of achieving this.

The problem is that after consent is given and we enable storage we are unable to set a bufferSize so we end up with many requests being generated. As the site we are running on is as Single Page Application this is particularly problematic.

**Describe the solution you'd like**
The bufferSize should be an optional value that is supported when enabling storage e.g. 
```javascript
snowplow('disableAnonymousTracking', { 
  stateStorageStrategy: 'cookieAndLocalStorage',
  bufferSize: 10
});
```

**Describe alternatives you've considered**
Can't think of any clean alternatives that don't risk impacting privacy.

**Additional context**

**Comment by miike** [comment]
Hi @rob-ellison-jet, are you able to reset the buffer size manually as part of your callback when consent has been granted? e.g., for a buffer of 3

`window.snowplow('setBufferSize', 3)`

**Comment by miike** [comment]
@rob-ellison-jet Just following this one up - does this solve your issue?
