### ISSUE TITLE
Add automatic & manual tracking of JS errors to JavaScript tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#16]
So that you do something like this:

```
window.onerror = function(errorMessage, url, line) {
      _snaq.push['trackError', errorMessage, line];
  };
```

References:
- http://blog.protonet.info/post/9620971736/exception-notifier-javascript
- http://help.airbrake.io/kb/api-2/notifier-api-version-22

Also add isFatal flag...

Rename message to description, URL to file.

Also: consider adding custom variable and custom JSON support to errors, so more data can be sent...

Adapting from Airbrake, also add:

class - the class name or type of error that occurred.

component - the framework, sub-system, or MVC controller in which the error occurred

action - class method, function, or 'controller action' in MVC parlance

All optional.

**Comment by alexanderdean** [comment]
Here's the Piwik ticket for comparison: https://github.com/piwik/piwik/issues/4977

**Comment by alexanderdean** [comment]
Having looked at this, I don't think it makes sense to try to generalize error reporting to a universal format. Different languages have different error handling, exceptions, stack traces etc.

**Comment by alexanderdean** [comment]
Assigning to @jbeemster

**Comment by Koen87** [comment]
@jbeemster and @alexanderdean is this something that is ready for production? We are looking at building something ourselves for JS errors but it looks like this does exactly what we need.

**Comment by alexanderdean** [comment]
Hey @Koen87 - this will go into the next release but as far as I know it hasn't been started yet. If you are going to work on it then a PR would be most welcome - it would be good to have a standard implementation with formal schemas that works for all users...
