### ISSUE TITLE
Add support for sending in data via POST (JSONP / CORS)

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#168]
May be useful in some circumstances.

See e.g. https://github.com/keenlabs/keen-js/blob/master/src/track.js#L83

Alex has another project with example code - ping him for details.

**Comment by fblundun** [comment]
Should we send payload_data 1-0-0 for the sake of people on old versions of Snowplow which don't support 1-0-2?

**Comment by alexanderdean** [comment]
I think let's send 1-0-2 as nobody is forced to use POST...

**Comment by fblundun** [comment]
Regarding cross-browser support:

* IE 7 and below do not support CORS, so we should fall back to using GET.
* IE 8-9 use XDomainRequest rather than XMLHttpRequest. This is problematic because XDomainRequests only support the Content-Type text/plain, not application/json (http://stackoverflow.com/questions/15113355/how-can-i-set-the-content-type-of-xdomainrequest-object). So we need to either start accepting text/plain or fall back to GET.

Thoughts @alexanderdean ?

**Comment by alexanderdean** [comment]
Hey @fblundun - can you see any issues with adding `text/plain` as an option?

**Comment by fblundun** [comment]
I can't think of any... I don't think the Content-Type changes our ability to parse the body.

**Comment by alexanderdean** [comment]
Okay - let's update Scala Common Enrich to support text/plain too then...

**Comment by fblundun** [comment]
My earlier comment was out of date - instead of Content-Type text/plain, XDomainRequest has started sending no Content-Type at all, according to [this source](http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx):


> 4 . Only text/plain is supported for the request's Content-Type header

>In the original incarnation of the XDomainRequest object, we allowed specification of the Content-Type for a POST request. It was pointed out that this violated our goal of emitting only requests that HTML Forms can issue, because HTML Forms are limited to sending data in three different content types: text/plain, application/x-www-urlencoded, and multipart/form-data. In particular, it was pointed out that some AJAX server libraries would blindly assume that if they received a request with a SOAP or JSON Content-Type, then the client must either be trusted or Same Origin (because HTML itself previously offered no way to issue cross-origin requests with that Content-Type).

>Unfortunately, when we fixed this problem in a later IE8 Beta, we went a bit too far; we restricted the content type to text/plain but didn’t allow the caller to specify that the data was in application/x-www-urlencoded form. This is problematic because server-side frameworks (e.g. ASP, ASPNET, etc) will only automatically parse a request’s fields into name-value pairs if the x-www-urlencoded content type is specified.

>Note: As of 2014, XDomainRequest doesn't appear to send any Content-Type header at all. It's not clear to me when this changed.

>To workaround this issue, server code that currently processes HTML Forms must be rewritten to manually parse the request body into name-value pairs when receiving requests from XDomainRequest objects. This makes adding support for the XDomainRequest object more difficult than it would be otherwise.
