### ISSUE TITLE
Come up with cookie sync approach to deal with mobile Safari

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#17]
In a nutshell:
1. Mobile Safari is increasingly important for a growing number of sites
2. Mobile Safari does not support setting third-party cookies

So we need to take another approach to create user IDs which span a network including mobile Safari.

The idea is some sort of cookie sync approach, which allows duids (domain user ids) to be synced across multiple domains.

shermozle is going to put a Gist together to start speccing this up.

Implementation of this should be after we have cleaned up our current approach to user IDs (#150).

**Comment by christoph-buente** [comment]
Is this issue still valid? More and more browsers do not support 3rd party cookies, and cookie sync seems to be more important than ever.

**Comment by paulboocock** [comment]
No longer valid, 3rd party cookies are on their way out. Advice is to run the collector as first party for nuid is a first party cookie.
