### ISSUE TITLE
Remove dependency on fblundun fork of grunt-yui-compressor

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#172]
https://github.com/snowplow/snowplow-javascript-tracker/blob/master/package.json#L9

**Comment by fblundun** [comment]
Looks like the original repo hasn't been maintained for almost a year: https://github.com/mathiasbynens/grunt-yui-compressor/commits/master

I'm not sure the PR is ever going to get merged...

**Comment by alexanderdean** [comment]
Okay @fblundun - let's move your fork into the snowplow organization then and make it official...
