### ISSUE TITLE
Add Angulartics support

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#179]
http://luisfarzati.github.io/angulartics/

**Comment by amyboyd** [comment]
Hi,

We are interested in using Snowplow, but don't want to use it without Angulartics. Any chance this will be implemented soon?

Thanks

**Comment by alexanderdean** [comment]
Hi @amyboyd - I would love to say it will happen soon but as you can see it has been pushed back multiple times. It would be good to get this support contributed by somebody who has Angulartics experience.

**Comment by alexanderdean** [comment]
Closing this - you can track progress on this issue here: https://github.com/angulartics/angulartics-snowplow
