### ISSUE TITLE
Add support for batching events

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#186]

**Comment by fblundun** [comment]
We could have pretty much the same API as the server-side trackers for this in the argmap:

```javascript
{
  post: true,
  bufferSize: 5
}
```

And also have a public `flush` method.

We could even make the localStorage queue the buffer. And always try to flush on page unload.

Perhaps we should have the option to set the buffer size to 1 if localStorage is unavailable to reduce the risk of unloading the page before all events are sent.

**Comment by alexanderdean** [comment]
I think this all sounds great. Let's enforce buffer of 1 if localStorage is unavailable...
