### ISSUE TITLE
Explore grabbing user location browser-side

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#191]
* HTML5 Location API
* https://mozilla-ichnaea.readthedocs.org/en/latest/api/index.html

**Comment by fblundun** [comment]
The location API matches our geo_location schema, except it also returns a timestamp field containing the time of the response. I don't know whether there's any point adding this to the context given each event carries a timestamp anyway. What do you think @alexanderdean @yalisassoon ?

**Comment by yalisassoon** [comment]
I can't see any point adding it, but I can't see any harm either. If
there's no real cost associated with adding the timestamp, I'd do it - you
never know how it might come in useful one day...

On Thu, Jan 29, 2015 at 10:02 AM, Fred Blundun <notifications@github.com>
wrote:

> The location API matches our geo_location schema, except it also returns a
> timestamp field containing the time of the response. I don't know whether
> there's any point adding this to the context given each event carries a
> timestamp anyway. What do you think @alexanderdean
> <https://github.com/alexanderdean> @yalisassoon
> <https://github.com/yalisassoon> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-javascript-tracker/issues/191#issuecomment-71998319>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by fblundun** [comment]
In the above commit I'm adding the ability to send a geolocation_context to a page view event.

I've set the timeout parameter, which determines how long to wait for the data before giving up and sending the page view without the context, to 5 seconds.

I'm not sure whether this should be attached to a page view at all - it's unreliable in that the user might never give or deny permission to share location information, meaning that the page pings will fire but the original page view will not. Additionally Firefox may fail to call the error callback when a user denies permission (see https://bugzilla.mozilla.org/show_bug.cgi?id=675533).

So maybe it would be better to make this an unstructured event (even though it isn't really an event)?

**Comment by fblundun** [comment]
Progress on this ticket exists in the geolocation-context branch

**Comment by alexanderdean** [comment]
As a design note: when we add this feature, we will do something similar to the Android Tracker, when it retrieves the user ID in a separate flow and then starts adding it to the context array once it is ready. It never blocks on the sending of events.

In other words: as soon as the geolocation_context is available, add it to events, but this is an async process.

**Comment by alexanderdean** [comment]
Pushing back to 3.0.0...

**Comment by fblundun** [comment]
Moving forwards to 2.3.0.

**Comment by fblundun** [comment]
As well as adding "geolocation" to the contexts field of the argmap, I suggest we also add a tracker method to enable the geolocation context. That way Snowplow users don't have to prompt the user for permission to use geolocation information as soon as the page loads.
