### ISSUE TITLE
Add validation to `trackUnstructEvent`

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#2]
Original issue: https://github.com/snowplow/snowplow/issues/209
Author: https://github.com/alexanderdean

Including:
- Checking for null name and properties
- Checking for nesting
- Checking for arbitrary type suffixes
- Checking type suffixes match JavaScript types

**Comment by paulboocock** [comment]
Moving away from validation in the tracker. We are however considering a debug mode that may have the capabilities to do this: #215
