### ISSUE TITLE
Explore idea of contextHelper

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#203]
The problem: some tag managers have a **flat** data layer which only supports simple key-value pairs. Unfortunately Snowplow custom contexts supports quite rich JSONs.

The solution: some kind of context helper which is provided with:
- The data layer contents
- JSON Schemas for all supported contexts
- Some mapping (JSON Path based?) JSON or JS function to get the DL -> context JSONs
- A JSON Schema based validator

Then you simply run that to prep your contexts for sending over the wire. And of course empty or partial JSONs which fail JSON Schema validation are discarded before the event is sent.

Thoughts @fblundun @yalisassoon ?

**Comment by paulboocock** [comment]
Full schema validation isn't feasible in JS due to bundle size. We may end up with a debug-mode in v3 that will help with this (#215).
