### ISSUE TITLE
Create a website for testing different tag manager implementations

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#207]
For each implementation we probably want:
1. One or ideally two web pages
2. A way of firing a combination of custom structured and custom unstructured events
3. Some of the events with custom context and some without
4. It should be possible to load pages using different tag managers alongside one another, so we can compare how they perform. We'll also wan to compare the performance with the Snowplow integrations that come with the tag manager out of the box (Tealium / Ensighten and OpenTag) vs our setting up the Snowplow tags manually e.g. by pasting our own HTML / Javascript into the tag manager UI as a custom tag.

Simply uploading the relevant HTML files to S3 might be an easy way to set the above up, in a way that makes it possible to share the URLs with e.g. engineers at the different tag management companies.

**Comment by paulboocock** [comment]
Closing as we can use next.snowplowanalytics.com for testing tags
