### ISSUE TITLE
Setup GTM tracking for the tag management test website

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#208]
The test website is the one setup in https://github.com/snowplow/snowplow-javascript-tracker/issues/207.

Let's setup GTM first as it's the most straightforward. 

Create a new container tag in GTM. Then refer to the following for info:
- [Our blog post](http://snowplowanalytics.com/blog/2012/11/16/integrating-snowplow-with-google-tag-manager/)
- [Our setup guide](https://github.com/snowplow/snowplow/wiki/Integrating%20javascript%20tags%20with%20Google%20Tag%20Manager#setup-gtm)
- [GTM developer documentation](https://developers.google.com/tag-manager/devguide)

**Comment by paulboocock** [comment]
Closing as we have GTM on next.snowplowanalytics.com
