### ISSUE TITLE
Create a GA Classic-compatibility cookie

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#213]
Basically an additional cookie which provides all the info that GA Classic provides in its first-party cookie.

Background: https://groups.google.com/forum/#!topic/snowplow-user/Y6OpCGA9FKI

**Comment by paulboocock** [comment]
We now capture gaCookies, utm, mkt, campaign & various dates/times. I'm not sure I see the need for this beyond what we now have in place, so I'm going to close this. If I've missed the point and this is still required, happy to reopen.
