### ISSUE TITLE
Create Boomerang-JS Tracker bridge

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#226]
- http://cruft.io/posts/rum-waterfall-charts-w3c-resource-timing-api/
- http://www.slideshare.net/justindorfman/a-web-perf-dashboard-up-running-in-90-minutes-presentation
- https://github.com/lognormal/boomerang/issues/23
- http://dev.piwik.org/trac/ticket/1985
- http://dev.piwik.org/trac/ticket/1700

**Comment by paulboocock** [comment]
Closing in favour of native APIs #794 and #328
