### ISSUE TITLE
Publish base64.js to npm

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#232]

**Comment by fblundun** [comment]
@alexanderdean shall I set up a new Snowplow repository called snowplow-base-64 from which to publish?

**Comment by alexanderdean** [comment]
Sounds great, thanks Fred...

**Comment by alexanderdean** [comment]
Maybe call it snowplow/js-base64

**Comment by alexanderdean** [comment]
Done, https://github.com/snowplow/base64-js, you are admin

**Comment by fblundun** [comment]
The new repository is ready for publication. I've made some tests so we could add Travis CI.

**Comment by alexanderdean** [comment]
Thanks Fred! I have switched on Travis CI for the base64 repo... Have you created the vagrant and vagrant push boilerplate? That should make it a bit easier for me to publish...

**Comment by fblundun** [comment]
Travis is working! I will add the Vagrant code now.

**Comment by fblundun** [comment]
I've added the "vagrant push" command to publish to npm. I think this issue should be moved to a tracker core milestone since base 64 encoding is required by the core rather than directly be the browser tracker.

**Comment by alexanderdean** [comment]
Agree, thanks

**Comment by chuwy** [comment]
Descheduling this. Core 0.4.1 milestone is already closed.

**Comment by paulboocock** [comment]
This will be superseeded by #694 where we can used a battle tested base64 library from npm, plus with the move to using rollupjs we won't suffer the same consequences of increasing our file size when pulling in the library (due to tree shaking)
