### ISSUE TITLE
For GA users, auto-populate a context containing all the utma cookie attributes

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#253]

**Comment by fblundun** [comment]
Should we try to parse the cookie values client side? i.e. instead of

```json
{
  "__utma": "1893875.1873622213.1396541846.1422352102.1422378910.98"
}
```

have separate fields for the number of visits, last visit, etc.?

**Comment by alexanderdean** [comment]
Pro: less enrichment required later on in the pipeline
Con: could break if GA updates their cookie format

@yalisassoon what's your verdict?

**Comment by yalisassoon** [comment]
Pass the raw value through - let's build an enrichment to process it eventually. In the short term it should be relatively straightforward to parse in Redshift.

The JS is already pretty big - we should be really careful not to actually process data in it - but leave that do further down the pipeline...

**Comment by fblundun** [comment]
Is this just the __utma cookie or do we also want to send the __utmb, __utmc, __utmz and _ga cookies?

**Comment by alexanderdean** [comment]
How much work to grab the other ones?

**Comment by fblundun** [comment]
Not much, they're all extracted in the same way

**Comment by alexanderdean** [comment]
Let's add them all then...

**Comment by fblundun** [comment]
Ok!

**Comment by fblundun** [comment]
I've added an extra boolean argument to `trackPageView`. If it's `true` then the ga_cookies context will be added to all page views and page pings. (This is the same way the PerformanceTiming context works.)

Is that good, or do we want to add this context to every event?
