### ISSUE TITLE
Add validation to `setPlatform()`

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#26]
As per values supported in Tracker Protocol:

https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol

See validation in Lua Tracker: 

https://github.com/snowplow/snowplow-lua-tracker/blob/master/src/snowplow/tracker.lua#L200

Dependent on determining our validation strategy for JS Tracker (not yet decided).

**Comment by paulboocock** [comment]
We don't validate anything else in the JS Tracker so this seems odd and extra code that we don't really want. It seems excessive to do this as platform won't change often, it's a work it out one time and then never change it sort of thing.
