### ISSUE TITLE
Add support for Navigation Timing API

### ISSUE THREAD

**Issue by mfu0** [snowplow/snowplow-javascript-tracker#27]
(Enhancement)

Add support for the HTML5 Navigation Timing API --

https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/NavigationTiming/Overview.html

Currently supported by Chrome/FF/IE10.

Event page_view: 

* Compute page loadtime as the difference between window.performance.timing.loadEventEnd and window.performance.timing.navigationStart.

It would be very cool to have this metric for page load time vs conversion rate. 

*  Track window.performance.navigation:
   * 0 => Navigation (i.e. link click)
   * 1 => Page reload
   * 2 => Back/fwd buttons

Guess this variable could be useful to determine user navigation behavior.

Event page_ping:

Chrome also exposes the window.performance.memory object which gives you 

    memory: MemoryInfo
    jsHeapSizeLimit: 793000000
    totalJSHeapSize: 10600000
    usedJSHeapSize: 10000000

This could be useful for single page applications and especially mobile HTML apps. 

There is also the propsed "Resource Timing API" 

http://www.w3.org/TR/resource-timing/

which will give you detailed performance stats for all resources within a window with

window.performance.getEntriesByType("resource");

    PerformanceResourceTiming
    connectEnd: 834.3509999103844
    connectStart: 834.3509999103844
    domainLookupEnd: 834.3509999103844
    domainLookupStart: 834.3509999103844
    duration: 1933.6480000056326
    entryType: "resource"
    fetchStart: 834.3509999103844
    initiatorType: "script"
    name: "https://github.com/_stats"
    redirectEnd: 0
    redirectStart: 0
    requestStart: 1496.1749999523163
    responseEnd: 2767.998999916017
    responseStart: 2766.1749999523163
    secureConnectionStart: 0
    startTime: 834.3509999103844

This could be useful in a many scenarios, but perhaps overkill for sp.js?

**Comment by alexanderdean** [comment]
This was done before, closing as dupe.
