### ISSUE TITLE
enableActivityTracking() doesn't work in synchronous JavaScript Tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#3]
See screenshot. Suspect it's being called before DOM has finalised or something like that...
![capture](https://f.cloud.github.com/assets/200511/478454/ba08042a-b7fa-11e2-91a9-305977eebe9a.png)

**Comment by fblundun** [comment]
I couldn't reproduce this. Closing since this was probably fixed unknowingly at some point in the last three years...

**Comment by alexanderdean** [comment]
7 Jul 2013! Incredibly old ticket
