### ISSUE TITLE
Add support for callback after trackEvent

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#30]
Sometimes, it is necessary to track an event that occurs immediately before a page reload. (E.g. click on an outbound link, or form submission that triggers a new page load.)  In these situations, there is a high risk that the trackEvent is not successfully fired - it is pushed onto the _snaq queue but doesn't execute before the page has reloaded.

GA offers a solution to this via the "Hit Callback" function. This provides a callback, which is used to load the new page - that way you can be sure that this only happens after the event has successfully been tracked.

https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#hitCallback

It would be great if we could implement something similar for Snowplow

**Comment by yalisassoon** [comment]
Now that we're pushing events to localStorage so that they can be fired on a subsequent page if the page is reloaded v quickly, should we close this issue?

**Comment by alexanderdean** [comment]
Agree, let's close

**Comment by christoph-buente** [comment]
What if i would like to call another system, after the trackEvent has been successfully delivered to the collector? Is there any chance to have an optional callback method to be passed to the trackEvent method?

**Comment by alexanderdean** [comment]
We can re-open for further discussion!

**Comment by christoph-buente** [comment]
Thx @alexanderdean,

So the idea is like this: We send one tracking event to the snowplow collector and the collector sets the 3rd party network_id cookie. Upon success, i want to send another event to a different collector/system, that needs to know this cookie id as well. I cannot send the 2 events at the same time, cause that would result on both systems set a cookie with the same name :(

So somehow those requests need to be serialized.

**Comment by paulboocock** [comment]
Sorry for reviving an old-ish issue but this feature would be ideal for something we're trying to solve at the moment.

We're currently looking at monitoring drop off for users that are redirected to a third party SSO. We want to track a page view before we redirect users and be certain it has been collected before we redirect to the third party SSO page. The local storage solution doesn't really work for us as the user might never come back to one of our pages with the tracker on it.

**Comment by sushantbprise** [comment]
+1 . Any updates on this??

**Comment by paulboocock** [comment]
When you go from a user to a maintainer 💯 
This doesn't seem like a huge challenge to implement and would be a useful feature to get into the final release of v2 where callbacks are more important, before we move to v3 and asynchronous code should become easier to deal with.
