### ISSUE TITLE
Bump Core version to 0.5.0

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#301]
Warning: This bump will break the processing of contexts by versions of Snowplow below 0.9.14 for batch. Consider pushing this back to 2.5.0.

**Comment by alexanderdean** [comment]
Pushing back again...

**Comment by fblundun** [comment]
Core 0.4.0 is on npm but [Core 0.4.1](https://github.com/snowplow/snowplow-javascript-tracker/milestones/Core%200.4.1) hasn't been written or published yet. Are we going to do a core release as well this milestone?

**Comment by alexanderdean** [comment]
Let's push this back...
