### ISSUE TITLE
If cookies: false, don't send duid or vid

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#304]
The has been requested by a Snowplow user with the following use case:

* They track users across multiple sites and domains
* They are building a webform where individual users can elect 'not to send personal identifiable data' into Snowplow
* For users who elect not to send that data in, they will setup rules in their tag manager to execute the Snowplow event tracking calls without passing in a browser fingerprint and first party cookie ID

**Comment by fblundun** [comment]
Should we keep sending the first visit time, last visit time, and visit count fields from the first party cookie if the duid is disabled?

**Comment by alexanderdean** [comment]
Not sure I follow - we don't _send_ first visit time and last visit time anywhere?

**Comment by fblundun** [comment]
Good point! I meant just the visit count.

**Comment by alexanderdean** [comment]
@yalisassoon - you know the client requirements better - do we keep in domain_sessionidx or stop sending that too?

**Comment by yalisassoon** [comment]
We have to stop sending that as well - clients would want this disabled because they want to tell their users that they aren't using 1st party tracking cookies.

**Comment by alexanderdean** [comment]
Thanks guys, updated ticket name.

**Comment by fblundun** [comment]
I've just checked and this actually already happens - vid and duid aren't set if cookies are disabled. So I think we can close this ticket?

**Comment by alexanderdean** [comment]
Oh excellent! Yes let's close.
