### ISSUE TITLE
Trailing comma in core.js

### ISSUE THREAD

**Issue by iaingray** [snowplow/snowplow-javascript-tracker#307]
There is a trailing comma in core/lib/core.js, line 429 (function trackLinkClick).

This can break IE8, which a frustrating number of users still stick with!

**Comment by alexanderdean** [comment]
Thanks @iaingray ! We'll fix this in Core 0.4.1. Note that Core 0.4.0 upwards (not yet used in the JS Tracker) requires Snowplow 0.9.14+.

**Comment by alexanderdean** [comment]
@fblundun - what's the status of this one...

**Comment by fblundun** [comment]
This can be fixed any time - but we decided to wait before upgrading the browser tracker to use version 0.4.0 or higher of the tracker core because it sends version 1-0-1 of the contexts schema which is incompatible with earlier versions of Common Enrich

**Comment by chuwy** [comment]
This was fixed in #526
