### ISSUE TITLE
Fix QuotaExceededError bug with localStorage in Safari

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#308]
Failed to execute 'setItem' on 'Storage': Setting the value of 'snowplowOutQueue_s'...

Possibly caused by private mode browsing in Safari?

> When Safari (OS X or iOS) is in private browsing mode, it appears as though localStorage is available, but trying to call setItem throws an exception.

* http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an
* http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

**Comment by alexanderdean** [comment]
Let's also fix in 2.3.0

**Comment by fblundun** [comment]
This is the sequence of events which causes the bug:

1) A user arrives on the website with private browsing disabled. The JS Tracker believes that localStorage is accessible.
2) The user turns on private browsing, making localStorage inaccessible, but the JS Tracker does not check this.

**Comment by alexanderdean** [comment]
Well sleuthed!
