### ISSUE TITLE
Add Vagrant `push tracker` to build and deploy new JavaScript Tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#313]
Copy approach from e.g. https://github.com/snowplow/snowplow/blob/release/r60-bee-hummingbird/vagrant/push/publish-kinesis-release.bash

Steps:

```
Prompt to build aws.json
cd /vagrant/snowplow-javascript-tracker
npm install
grunt publish
```

**Comment by fblundun** [comment]
Why build the JSON from user input rather than just having an aws.json file created by the user?

**Comment by alexanderdean** [comment]
Ah, because the idea is that all you have to do to publish is type vagrant push, then you're in a wizard-like experience...

**Comment by fblundun** [comment]
That makes sense! The above commit seems to work but this is the first Bash script I've written so you might want check it for subtle mistakes...
