### ISSUE TITLE
Ensure correct 3-Clause BSD License notices are being used

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#316]

**Comment by paulboocock** [comment]
It's actually pretty tricky to relicense from BSD-3. The original license of what we forked states we must reproduce the full license notice https://github.com/matomo-org/matomo/blob/a6af51130b5d59f2c957b459218c152b2c2f06d5/js/LICENSE.txt and we'd need permission from major contributors to switch.

Even if we moved to Apache-2.0 we would still need to reproduce the BSD header in every file as well as the Apache header. This doesn't seem ideal (maybe we could avoid this with the original authors permission).

Also, 3-clause BSD compares very similarly to Apache-2.0 https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences#General_comparison

I believe the only way to fully relicense under Apache-2.0 would be to reach out to Anthon Pang and get explicit permission for the change however I'm not sure this is really worth the time and effort given the similarities in the licenses. I think a better use of time would be to tidy up the license notices around the codebase, ensure the LICENSE files and all copyrights are up to date.
