### ISSUE TITLE
Reduce internal code duplication by configuring tracker core with a list of contexts to be added to every event

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#318]
To prevent having to manually add contexts like PerformanceTiming and ga_cookies to every event.

**Comment by fblundun** [comment]
I don't think this can be done in time for 2.3.0 since changes to the tracker core are blocked by #301

**Comment by alexanderdean** [comment]
Agree - let's push back...

**Comment by rgabo** [comment]
@alexanderdean @fblundun just a :+1: and a comment that we would rely on this heavily. Most of the contexts we have are what we call default contexts: they are recorded with every event we record. Examples are (in an ecommerce setting): `site`, `page`, `product`, `shopper`, `ab`, etc.

We are currently on 0.x and use unstructured events for this but we will be migrating to shredded contexts soon.

**Comment by alexanderdean** [comment]
Ah! This ticket refers to enabling standard contexts:

```javascript
"contexts": {
  "performanceTiming": true,
  "geolocation": false,
  "optimizely": true,
  "gaCookies": true
}
```

kind of thing! I will update the ticket to be clear.

**Comment by rgabo** [comment]
@alexanderdean gotcha and it makes sense. We are keeping contexts as state internally so we can "just" configure the default contexts without having to always pass them.

We do pass all contexts to the JavaScript tracker :smile:

**Comment by rgabo** [comment]
..but it makes me think.. We would *love* to see contexts like Coremetrics, SiteCatalyst, Autonomy, Webtrends, etc being added.

GA & Optimizely are mostly used in startup land, whereas in the enterprise we see Adobe/IBM/Oracle heavily used with a few refreshing exceptions...

I guess a great candidate for contributing it back!

**Comment by alexanderdean** [comment]
If a service exposes some kind of JSON data object (as Optimizely does), we can definitely pass that back... Just a case of defining a JSON Schema for it and plumbing it in...

**Comment by alexanderdean** [comment]
@fblundun what's the status of this one...

**Comment by fblundun** [comment]
Like #307, this is easily done but new versions of the core can't yet be used by the main tracker.

**Comment by fblundun** [comment]
Every call to a core tracking function made by the browser tracker contains some code to handle attaching some autogenerated contexts (like the performance timing context) to the event. This ticket would add to the core the ability to register a list of contexts to be sent with every event, reducing code duplication.

**Comment by alexanderdean** [comment]
@fblundun can you update milestone and ticket to clarify this is core internals...

**Comment by paulboocock** [comment]
Closing as most of this logic will be re-written in v3, with a strong focus on removing duplication and stripping out `autoContexts` into separate modules.
