### ISSUE TITLE
Send POST requests using XDomainRequest when possible

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#327]
Instead of defaulting to GET for IE8-9, we should use their XDomainRequest object.

Blocked by https://github.com/snowplow/snowplow/issues/1434 because it is impossible to set a content type for XDomainRequests.

**Comment by alexanderdean** [comment]
Thanks Fred!

**Comment by fblundun** [comment]
Note that in InPrivate Browsing mode in IE8, all XDomainRequests will fail ([source](http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx))

**Comment by fblundun** [comment]
Some example code can be found [here](http://stackoverflow.com/questions/10232017/ie9-jquery-ajax-with-cors-returns-access-is-denied).

**Comment by paulboocock** [comment]
We no longer support IE8 and IE9 is likely on its way out...
https://github.com/snowplow/snowplow/issues/1434 has also been marked as wont-fix. Even if this works in the SSC (I haven't invested any time in testing), it not working in legacy Clojure collectors is an issue and this issue just doesn't seem that important anymore. Closing.
