### ISSUE TITLE
Stop caching page URL and referrer URL

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#337]
In a single page web app, the URL might change after the Tracker has initialized. We should recalculate it for every event.

**Comment by ciacicode** [comment]
Nice stuff!

**Comment by fblundun** [comment]
The above commit means that if the Snowplow user has not set a custom URL, then the latest URL is always used. But if they have set a custom URL, the last custom URL will always be used even if the actual URL (i.e. `location.href`) changes.

An alternative would be to snapshot the actual page URL at the time that the Snowplow user calls `setCustomUrl`, and forget the custom URL as soon as the actual URL becomes different from the snapshotted URL.

Which approach sounds the most sensible?

/cc @alexanderdean , @yalisassoon

**Comment by alexanderdean** [comment]
Hmm. `setCustomUrl` does sound sticky to me, like `setUserId`. @yalisassoon what do you reckon we should do?

Also I wonder if, in the 3.x.x series, setCustomUrl should be replaced with a customUrl argument to trackPageView, to make the association simpler.

**Comment by alexanderdean** [comment]
Hmm, I'm not sure about my last point. Part of the reason for the stickiness of setCustomUrl is that other events which occur on the "custom URL" get the same custom URL, which my suggested approach would lose.

**Comment by yalisassoon** [comment]
Agree:

* `setCustomUrl` method should be sticky
* We can add an optional argument to the trackPageView method to pass in a custom URL in a non-sticky way. I don't think this is high priority, though - I wouldn't make that part of this release.

**Comment by alexanderdean** [comment]
Cool, added #338 for the 3.x.x series

**Comment by pascal-privax** [comment]
If I may add my 5 cents,

To me `setCustomUrl` doesn't sound sticky. It's an override on the url for `trackPageView`. To me it seems much more likely that someone wants to override it for just the one page view, not keep the same custom url for every subsequent view.

**Comment by alexanderdean** [comment]
Hi @pascal-privax! With the `setXXX` methods, these methods are sticky for the rest of the page lifetime (i.e. until tracker reload). This is in comparison to `track()` method arguments, which are transient to a single argument. It would be nice to have a transient custom URL option, hence #338 - this is a big breaking change to our trackPageView API, hence it being in the 3.x.x series, not a 2.x.x patch release.

**Comment by fblundun** [comment]
My approach above leaves the referrer unchanged if the page URL changes without the page reloading. Should we try to update the referrer to the previous value of the page URL?

**Comment by yalisassoon** [comment]
Yes we should!

On Tue, Mar 10, 2015 at 9:00 AM, Fred Blundun <notifications@github.com>
wrote:

> My approach above leaves the referrer unchanged if the page URL changes
> without the page reloading. Should we try to update the referrer to the
> previous value of the page URL?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-javascript-tracker/issues/337#issuecomment-78016568>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>
