### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by ianthehenry** [snowplow/snowplow-javascript-tracker#350]
There's a `snowplow-tracker` on NPM, but it points to a different repo: https://github.com/snowplow/snowplow-nodejs-tracker

Any plans to publish this repository to NPM somewhere? This project's `package.json` made me expect to see this on NPM as `snowplow-tracker`.

**Comment by alexanderdean** [comment]
Hey @ianthehenry - we publish two assets to NPM:

1. https://www.npmjs.com/package/snowplow-tracker-core
2. https://www.npmjs.com/package/snowplow-tracker

The first of these is a library extraction from this repo; as you've spotted the second is the Node.js Tracker.

No plans to publish the overall repo to npm as it's not strictly a library...
