### ISSUE TITLE
Decide what to do if a single event exceeds the maximum request size

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#359]
My suggestion is to skip saving it in the localStorage queue and try sending it once immediately.

**Comment by alexanderdean** [comment]
I think that suggestion sounds sane! Let's discuss further in due course

**Comment by fblundun** [comment]
Should we do the same thing for GET requests that are too long?

The setting in the argmap is called "maxPostBytes" so we can't really use it for GETs as well.

**Comment by alexanderdean** [comment]
Hmm - potentially yes. Could you create a ticket for 2.5? Let's not rush this GET issue...

**Comment by fblundun** [comment]
Here it is: #362

**Comment by alexanderdean** [comment]
Thanks Fred!
