### ISSUE TITLE
Investigate having a maximum size for GET requests

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#362]
Otherwise a single huge event might never leave localStorage because it is too big to send successfully.

**Comment by alexanderdean** [comment]
This will block further events from sending.

**Comment by alexanderdean** [comment]
I'm not sure why I wanted to hold back on this one... It feels like maxGetBytes would be a sensible option to add... /cc @yalisassoon

**Comment by javiermar** [comment]
Is there an update on this front? It's 2019 and we're seeing this problem in our environment.

**Comment by paulboocock** [comment]
Investigating this seems a worthwhile thing to do in the last release of v2. The risk of getting in a "stuck" state with local storage and GET together is an unfortunate issue. 
General advice is to only use POST with localStorage queues (tracker defaults) but the tracker is quite happy to be configured with GET and localStorage queues.

**Comment by matus-tomlein** [comment]
Addressed in #449
