### ISSUE TITLE
Update docs for trackSocialInteraction

### ISSUE THREAD

**Issue by dudeman** [snowplow/snowplow-javascript-tracker#363]
According to this #12 trackSocialInteraction was implemented in 2.1.0, but according to the docs https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#social it's not implemented yet.  Looks like the docs our out of date, it would avoid confusion if they were updated to correctly reflect weather or not it's implemented.

**Comment by alexanderdean** [comment]
Thanks! It has been implemented. @fblundun - can you please update the documentation, and check the specifics are right - e.g. it says "The trackSocial method takes four parameters:" but there are only three in the table!

**Comment by fblundun** [comment]
Thanks for noticing this @dudeman . I've gone through the social tracking section and cleaned up these inconsistencies.

**Comment by dudeman** [comment]
Sweet!  Thanks for the clarifications and the quick changes!

**Comment by alexanderdean** [comment]
No worries!
