### ISSUE TITLE
Investigate inconsistent user_fingerprint

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#365]
We have had a report of a user_fingerprint changing without the user changing any of the inputs to the hash function. The events were page views on different subdomains of the same root domain. The fingerprint was the same on two subdomains and different on the third.

**Comment by fblundun** [comment]
Executing this code in the console will print the user_fingerprint:

```javascript
snowplow(function() {console.log(this[namespace].getUserFingerprint())});
```

where `namespace` is the tracker namespace from the call to `newTracker`, e.g. "cf".

**Comment by fblundun** [comment]
`screen.width` and `screen.height` aren't always consistent. On Firefox 30, I get these results;

```
GitHub and snowplowanalytics
screen.width === 2133
screen.height === 1333

Everywhere else I have checked, including the Google homepage
screen.width === 2560
screen.height === 1600
```

The GitHub measurements are almost exactly 5/6 the Google measurements.

**Comment by paulboocock** [comment]
Fingerprinting has been removed as of 2.13.0
