### ISSUE TITLE
Create browser context

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#366]
This would contain all browser-specific fields currently sent first-class in the tracker protocol

**Comment by paulboocock** [comment]
Likely to be deprecated feature in an atomic.events refactor. Closing as I don't believe we will do this in terms of taking the current browser feature identification and stuffing it into a context. Can reopen something similar in the future if this does crop up following any changes to atomic.events.

**Comment by alexanderdean** [comment]
Are these fields not interesting for analytics any more?

**Comment by paulboocock** [comment]
I don't think they are, it's all a bit 2005. I'm not sure I can remember the last time I went on a site that contained any of these technologies (bar PDFs).

We check for:

```
	// document types
	pdf: 'application/pdf',

	// media players
	qt: 'video/quicktime',	
	realp: 'audio/x-pn-realaudio-plugin',
	wma: 'application/x-mplayer2',

	// interactive multimedia
	dir: 'application/x-director',
	fla: 'application/x-shockwave-flash',

	// RIA
	java: 'application/x-java-vm',
	gears: 'application/x-googlegears',
	ag: 'application/x-silverlight'
```

The only one that is interesting is probably PDF but all modern browsers have a PDF viewer built in now.
I think the only interesting things we look at in terms of browser features are screen resolution and cookie availability:

```
		// Other browser features
		features.res = screenAlias.width + 'x' + screenAlias.height;
		features.cd = screenAlias.colorDepth;
		if (useCookies) {
			features.cookie = object.hasCookies(testCookieName);
		}
```

**Comment by alexanderdean** [comment]
> it's all a bit 2005.

🗡
