### ISSUE TITLE
HTTP 413 response from the CloudFront collector

### ISSUE THREAD

**Issue by yuvalherziger** [snowplow/snowplow-javascript-tracker#368]
Problem raised due to an average of 17% less distinct visits than in GA.
The following thread elaborates on the details: 
https://groups.google.com/forum/#!topic/snowplow-user/rdMtt8vQwlY

Could be related to respectDoNotTrack, might as well be a coincidence, but the important thing is that for a given browser, it was resolved by clearing the cache.

**Comment by yuvalherziger** [comment]
Caused by this issue:
https://github.com/snowplow/snowplow-javascript-tracker/issues/362

**Comment by alexanderdean** [comment]
Closing as duplicate of #362.
