### ISSUE TITLE
Add a page view UUID to the Javascript tracker

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-javascript-tracker#369]
Add a UUID to each page view (the subsequent page pings should have the same UUID). This will make it much easier to aggregate page views and pings into single rows.

**Comment by yalisassoon** [comment]
Basic idea:

page view ID (UUID) gets generated with each new page view. It get's fired with the initial page view event, and then any subsequent page view events.

The ID is pushed into Snowplow as part of a new `com.snowplowanalytics.snowplow/web_page/jsonschema/1-0-0` context:

```json
{
	"$schema": "http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#",
	"description": "Schema for a web page context",
	"self": {
		"vendor": "com.snowplowanalytics.snowplow",
		"name": "web_page",
		"format": "jsonschema",
		"version": "1-0-0"
	},

	"type": "object",
	"properties": {
		"id": {
			"type": "string",
			"maxLength": 60
		}
	},
	"required": ["id"],
	"additionalProperties": false
}
```

Note: over time we can explore migrating fields in `atomic.events` that really belong in a web page context to this object in the data model.

**Comment by alexanderdean** [comment]
I would say the format/maxLength should match a UUID, otherwise looks good...

**Comment by fblundun** [comment]
I have made this work like the ga cookies context, the performance timing context, and the geolocation context: you use a dictionary that looks like

```js
          contexts: {
            webPage: true,
            gaCookies: true,
            performanceTiming: true
          }
```

when configuring the tracker, and if "webPage" is one of the entries and is set to `true`, the page view ID is attached to every event.

Is that right, or should the context be enabled by default?

**Comment by alexanderdean** [comment]
@jbeemster - is the mobile_context on by default? That's probably the closest analogy...

**Comment by fblundun** [comment]
Just remembered that we already have a org.schema/WebPage schema (https://github.com/snowplow/iglu-central/blob/master/schemas/org.schema/WebPage/jsonschema/1-0-0)

Should we rename this context to avoid confusion?

**Comment by alexanderdean** [comment]
No I think it's okay - it's two different vendors' "take" on a web-page...

**Comment by fblundun** [comment]
That makes sense.

**Comment by fblundun** [comment]
Given the other contexts are opt-in, it would be cleaner to have the web_page context off by default. Perhaps we could have it turned on in all our examples to make it clear that it's recommended?

**Comment by bogaert** [comment]
Sounds good to me.
