### ISSUE TITLE
Structured event bugs? Or Docs issue?

### ISSUE THREAD

**Issue by keyscores** [snowplow/snowplow-javascript-tracker#377]
Not sure if this is a bug in the docs or SP proper.
I can't seem to get structured events to fire from a simple html page.
I've tried to have the event be triggered by jquery button click event. And I've also enabled it in the tag. Can we have a full html example of a button click to make sure I'm doing it right?
Seems like it should be very straight forward but can't see a way. I only get PV data.

**Comment by alexanderdean** [comment]
https://groups.google.com/forum/#!forum/snowplow-user

**Comment by keyscores** [comment]
Ok Thanks @alexanderdean Can I get your input here please: https://groups.google.com/forum/#!topic/snowplow-user/_CKwRdwXGRA
