### ISSUE TITLE
applyAsyncFunction have no return value.

### ISSUE THREAD

**Issue by ale-grosselle** [snowplow/snowplow-javascript-tracker#389]
If you call for example window.snowPlowReference('getUserFingerprint'), It not return any value.

Instead of: 
```javascript
for (j = 0; j < namedTrackers.length; j++) {
   namedTrackers[j][f].apply(namedTrackers[j], parameterArray);
}
```

What do you think of doing so:
```javascript
var returnValues = [];
for (j = 0; j < namedTrackers.length; j++) {
   returnValues.push(namedTrackers[j][f].apply(namedTrackers[j], parameterArray));
}
...
...

return returnValues ;
```

**Comment by fblundun** [comment]
Hi @ale-grosselle ,

I think you're looking for our callback functionality: https://github.com/snowplow/snowplow/wiki/3-Advanced-usage-of-the-JavaScript-Tracker#41-callbacks

This functionality lets you access the return values of methods like `getUserFingerprint`.

**Comment by ale-grosselle** [comment]
Hi @fblundun, Thank you for your answer!
It is true with the callback functionality I can access to return value.

So, for "set" functions i can call  ```window.snowPlowReference``` passing name of method; for "get" functions i must pass callback function

**Comment by fblundun** [comment]
That's right - there's no need to use the callback function unless you want to use the return value of the method.
