### ISSUE TITLE
trackPageView not tracking dynamic page titles

### ISSUE THREAD

**Issue by rockrep** [snowplow/snowplow-javascript-tracker#392]
Snowplow JS Tracker 2.4.3

We're using Turbolinks in our Rails app to load content on link clicks.   Turbolinks handles dynamically updating the title tags for the page on page:load and substitutes the page body via ajax.      

Content returned from the ajax calls contains a script which makes a call to trackPageView.
```
<script type="text/javascript">
    # snowplow trackPageView called here
</script>
```
Snowplow docs state the page title is inferred from the title tag, however, we are seeing the original page title being sent on subsequent page views loaded via Turbolinks.   We are passing null for the optional page title param in calls to trackPageView.

Repro:
Visit: http://www.funnyordie.com/articles/ebf5e34fc8/10-hours-of-walking-in-nyc-as-a-man
```
e:pv
url:http://www.funnyordie.com/articles/ebf5e34fc8/10-hours-of-walking-in-nyc-as-a-man?_cc=S_d___&_ccid=v02irt.no9emy
page:10 Hours of Walking in NYC as a Man from Nate Dern, FOD ...
```
Then click on any of the articles in the browse-related carousel, e.g. the Donald Trump announcement article.
```
e:pv
url:http://www.funnyordie.com/articles/bc32a38b90/a-note-about-funny-or-die-s-coverage-of-donald-trump-s-campaign?playlist=348049&_cc=S_d___&_ccid=v02irt.no9emy
page:10 Hours of Walking in NYC as a Man from Nate Dern, FOD ...
refr:http://www.funnyordie.com/articles/bc32a38b90/a-note-about-funny-or-die-s-coverage-of-donald-trump-s-campaign?playlist=348049
```

**Comment by alexanderdean** [comment]
Thanks for raising, scheduling for investigation...

**Comment by fblundun** [comment]
Hi @rockrep ,

Thanks for finding this. The JS Tracker currently caches `document.title` which prevents it from noticing the changes made by Turbolinks.

We will fix this in 2.5.1, the release we are working on at the moment.

Another thing to note: when you call `enableLinkClickTracking`, link click tracking is only enabled for those links which are already on the page. So if you navigate to a new page, the new link elements won't automatically be tracked. The solution is to call [`refreshLinkClickTracking`](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#refreshLinkClickTracking) whenever Turbolinks loads a new page.

**Comment by fblundun** [comment]
If a user sets a custom title, and later on the actual value of `document.title` changes, should we keep using the custom title in page pings or should we swap to using the new value of `document.title`? Does anybody have a preference?

**Comment by yalisassoon** [comment]
I think we need to swap to using the new value of document.title, or it'll
make it very hard to integrate in single page apps...

On Thu, Jul 23, 2015 at 2:00 PM, Fred Blundun <notifications@github.com>
wrote:

> If a user sets a custom title, and later on the actual value of
> document.title changes, should we keep using the custom title in page
> pings or should we swap to using the new value of document.title? Does
> anybody have a preference?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-javascript-tracker/issues/392#issuecomment-124088004>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by fblundun** [comment]
I think you're right... In general we should just use whichever of the actual `domain.title` and the custom title has changed most recently.

**Comment by rockrep** [comment]
Hi Fred. Thanks. Looking forward to the update. And I noticed the issue
with link click tracking this week, and already added code to call
refreshLinkClickTracking on turbo link updates.

Michael
