### ISSUE TITLE
Move setCustomUrl/setReferrerUrl into... customizable web_page context?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#396]
Something to explore for the 3.0.0 release.

/cc @philpearce

**Comment by paulboocock** [comment]
I'm not entirely sure what this might look like. Are we suggesting the `autocontext` has more properties? If we're suggesting this occurs at tracker initialisation then I worry that it wouldn't work for single page applications and in fact, the function versions we are suggesting we replacing here are probably more future proof and flexibile.

**Comment by alexanderdean** [comment]
I think this can be closed. It would be superceded by the atomic.events refactor eventually.
