### ISSUE TITLE
Explore moving enableXXX methods into tracker constructor

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#410]

**Comment by alexanderdean** [comment]
The thinking here is that these aren't really imperative track() functions, but rather pieces of configuration that could be attached at tracker construction time...

**Comment by paulboocock** [comment]
Being able to disable and enable certain features at runtime is an interesting concept however (particularly things like cookies). We will have the opportunity to assess our available in v3.0.0, so I'm going to pop this into the milestone but I'm not sure removing all the "enable" methods is the right route to take. Limiting to track init only, means users end up with complex configurations with multiple trackers at the same time with different configurations (I'll admit that from a state management point of view, that is nicer however).
