### ISSUE TITLE
Attempting to create a new tracker using an existing namespace should do nothing

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#411]

**Comment by fblundun** [comment]
Inspired by this user group thread: https://groups.google.com/forum/#!topic/snowplow-user/UGHyekhRn8Y

**Comment by fblundun** [comment]
At the moment, the new tracker shadows the old tracker but page pings and event handlers set up by the old tracker still work.

**Comment by danielCalbonero12345** [comment]
java -jar node-v1.0.jar --key key.store 2>&1 &
// customize some configuration
java -jar node-v1.0.jar --server.port=8081 --spring.profiles.active=dev --key key.store 2>&1 &TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t
