### ISSUE TITLE
Page Pings as page_view with Post = false

### ISSUE THREAD

**Issue by vsabato** [snowplow/snowplow-javascript-tracker#413]
Hi, I'm using sp.js as local file in my web application, with private collector (specific web page).
I don't know if it is a normal behavior or is an issue, but my expecting is that the event notification works in the same way with post parameter = true or false. In other words the e parameter in the event notification will be pp or pw based on kind of event.
It works fine if post = true, but with post = false, I receive all information in query string with e parameter always with value "pv", for both page ping and page view events.

var documentAlias = document;
var windowAlias = window;

;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];
p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
};p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
n.src=w;g.parentNode.insertBefore(n,g)}}(windowAlias,documentAlias,"script","<%=urls%>/_asset/js/sp.js","my_event_tracker"));

windowAlias .my_event_tracker("newTracker", "cf", urltracker + "/tracker.jsp?p=", {
    appId: "app123",
    platform: "web",    
	contexts: {
            webPage: true,
            gaCookies: true,
            performanceTiming: true
          }
	});
windowAlias.my_event_tracker('enableActivityTracking', 10, 10);
windowAlias.my_webchat_event_tracker('trackPageView');

**Comment by alexanderdean** [comment]
I'm not sure I fully understand the bug report - it sounds like the issue is that pagepings are sent as `&e=pp` for GET, which doesn't sound likely. Assigning to Fred to follow up on...

**Comment by fblundun** [comment]
I can't reproduce this. Could you check that your sp.js is the same as the one hosted at http://d1fc8wv8zag5ca.cloudfront.net/2.5.2/sp.js?

**Comment by Ideandro** [comment]
test

**Comment by vsabato** [comment]
Hi,
I founded that the notification work fine if I initialize the tracker with 

<code>
windowAlias.webchat_event_tracker("newTracker", "cf", <b>"d3rkrsqld9gmqf.cloudfront.net"</b>, {
	appId: "abc123",
	platform: "mob",    	
});
</code>

but it not works if I don't use d3rkrsqld9gmqf.cloudfront.net but a local collector page.

<code>
windowAlias.webchat_event_tracker("newTracker", "cf", <b>"localhost:8080/testproject/tracker.htm?p=track"</b>, {
	appId: "abc123",
	platform: "mob",    	
});
</code>

note that I need to add <b>?p=track</b> to the collector URL because snowplow JS tracker always add /i in the GET (I don't know why).

Could you help me to understand how to solve it ?

Thank you

**Comment by alexanderdean** [comment]
Supporting local collectors isn't a priority, de-scheduling...

**Comment by vsabato** [comment]
I'm sorry my purpose is not to create a local collector, but just to receive correctly a GET for page_view and page_ping. At moment it not works if I use a different parameter than d3rkrsqld9gmqf.cloudfront.net in the initialization.

Could you confirm me that this is not an issue but a normal behavior of library ?

Thank you

**Comment by fblundun** [comment]
Page views appearing as "pp" rather than "pv" is incorrect, but I suspect this is due to the querystring you added to the collector rather than being a tracker bug.

The tracker expects the collector to accept GET requests on the path "/i" and POST requests on the path "/com.snowplowanalytics.snowplow/tp2". I suggest altering your collector to accept GET requests with the "/i" path.

**Comment by vsabato** [comment]
Hi, I solved creating a servlet with /i mapping that write a pixel to the response.
Now, I can manage the events from my servlet.
This issue should be closed.
Thank you

**Comment by alexanderdean** [comment]
Thanks for updating us @vsabato !
