### ISSUE TITLE
Assemble PerformanceTiming context explicitly

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#415]
Rather than assuming that window.performance will fit the schema

https://github.com/snowplow/snowplow-javascript-tracker/blob/43c941cdecab2ffbb60d71320d7178985f9040a7/src/js/tracker.js#L779

**Comment by alexanderdean** [comment]
Great call - this will reduce the chance of us losing events because a browser is freestyling...

**Comment by paulboocock** [comment]
This should be considered as part of rewriting performance timing usage #794
