### ISSUE TITLE
Allow certain params to be set via QS vars

### ISSUE THREAD

**Issue by jrobgood** [snowplow/snowplow-javascript-tracker#42]
Allow certain params such as UID / user_id to be consumed and set using the existing querystring parser functions, just like pushing a value via setUserId.

Use cases: clickthroughs from email campaigns, partner/affiliate sites with a shared key for known users, pseudo-session (obviously no PII or security assertion) handoff from one UA to another, e.g.: web (desktop) to mobile, mobile to media device, whatever.

Bonus points for opening up the entire SE and UE event types to this kind of flexibility. 

Things to think about:
- Does this persist in the cookie, and if so, what happens when new values collide with previously-known values?
- Truncating the columns in the ETL job so nothing overflows (and errors out on the L part of ETL)
- Allow for this flexibility in the no-js collection method, which I assume is limited currently by rules in the enrichment process, unless any and all params are pushable into their columns so long as the right key/value pairs appear in the qs to the static gif.

**Comment by alexanderdean** [comment]
I don't think this one still needs to be in-scope for the tracker, closing
