### ISSUE TITLE
Make build process compatible with Node 4.1.2

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#420]
Attempting to deploy from a fresh Vagrant causes 3 problems:

* Our fork of grunt-yui-compressor fails when reporting the size of the gzipped JS: https://github.com/mathiasbynens/grunt-yui-compressor/issues/28
* grunt-s3 fails due to one of its dependencies attempting to modify a read-only property: https://github.com/vesln/temporary/issues/20
* grunt-cloudfront reports an error (although it does seem to perform the invalidation) - https://github.com/flrent/grunt-cloudfront/issues/16

I eventually found that these errors were caused by a change to my Node.js version - the playbook now installs the latest version, 4.1.2. Retrying with v0.10.35 worked.

So we could fix the Node.js version installed to 0.10.35. But going forwards it is probably better to upgrade our dependencies to be compatible with the latest version.

**Comment by alexanderdean** [comment]
Hey @fblundun - aoplogies yes, I had to bump the version to release the nodejs-tracker, because npm publish doesn't work with with 0.10.35 any more.

**Comment by fblundun** [comment]
grunt-s3 is no longer maintained. Fortunately the problem is with its dependency on temporary, so for now we can fix temporary to a later version.

**Comment by fblundun** [comment]
I have split this into #424, #425, and #426.
