### ISSUE TITLE
Update docs on cross domain tracking to explain where the decorated data ends up in Redshift

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#421]
Otherwise it isn't clear what the purpose of decorating the links is!

**Comment by yalisassoon** [comment]
This is the bit of documentation to update: https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#cross-domain

**Comment by fblundun** [comment]
I've made an edit - do you think it's clear enough now?

**Comment by yalisassoon** [comment]
Looks great @fblundun!

On Tue, Oct 20, 2015 at 4:31 PM, Fred Blundun <notifications@github.com>
wrote:

> I've made an edit - do you think it's clear enough now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-javascript-tracker/issues/421#issuecomment-149603564>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by fblundun** [comment]
Thanks!
