### ISSUE TITLE
nodeName is null error in getFormTrackingManager::getParentFormName()

### ISSUE THREAD

**Issue by andrewk** [snowplow/snowplow-javascript-tracker#423]
One of the most common errors in the JS logs of our apps using snowplow is `Unable to get property 'nodeName' of undefined or null reference`. We have updated to the latest version and the error continues.

I believe this error to be caused by [this code](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/forms.js#L76-L82):
```
	function getParentFormName(elt) {
		while (elt && elt.nodeName.toUpperCase() !== 'HTML' && elt.nodeName.toUpperCase() !== 'FORM') {
			elt = elt.parentNode;
		}
		if (elt.nodeName.toUpperCase() === 'FORM') {
			return getFormElementName(elt);
		}
	}
```

At some point `elt` is being assigned to a `Document` or `DocumentFragment` node type, which will return false to the `while` check, but does not have a `parentNode`. The result is that the `if (elt.nodeName.toUpperCase())` call causes a TypeError as the `parentNode` of a Document or DocumentFragment node is null.

**Comment by alexanderdean** [comment]
Thanks for raising @andrewk !

**Comment by andrewk** [comment]
thanks, for the instant triaging :) If you have trouble reproducing let me know and I'll put more instrumentation in place at our end.

**Comment by alexanderdean** [comment]
Thanks for the detailed bug report!

**Comment by fblundun** [comment]
Thanks for finding this @andrewk! There is a new test version of the next release available at http://d1fc8wv8zag5ca.cloudfront.net/2.5.3-m2/sp.js - if you use it these errors should disappear.

**Comment by andrewk** [comment]
Great, thank you :+1:
We'll probably have to wait for the official release as we integrate platform-wide via google tag manager, but I can see from the diff that you've added every possible precaution.
Maybe one day we'll get a safe navigation operator in JS :)

**Comment by fblundun** [comment]
Fair enough! We will let you know when 2.5.3 is released.

**Comment by fblundun** [comment]
@andrewk 2.5.3 has now been released!
