### ISSUE TITLE
Possible anti-bot measures

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#434]
Just an idea: some sort of anti-bot configuration which doesn't send any events until some sort of user activity like moving the mouse or pressing keys is detected.

**Comment by wiremine** [comment]
+1. Might be nice to disable this for automated testing. I.e., it would be nice to test without forcing a mouse or keyboard event first.

**Comment by matogertel** [comment]
If this feature is implemented, it has to support touch events too. No mouse moving on mobile devices! Also, on larger tablets, even scrolling may never happen, so you need to be really careful how you implement this. I suggest adding it as an opt-in option rather than a default.

**Comment by kingo55** [comment]
What about the usual snowplow approach? Track the status into a context and
filter the events out selectively during Analytics?

**Comment by alexanderdean** [comment]
Makes sense @kingo55 !

**Comment by paulboocock** [comment]
We have a number of other anti-bot measures now in place, in particular at Enrichment.
This seems like it is high risk (for data loss) for low reward. I can reopen this is any feels differently?
