### ISSUE TITLE
Pass custom URL path to trackPageview

### ISSUE THREAD

**Issue by timelf123** [snowplow/snowplow-javascript-tracker#435]
I am just sitting down to develop a snowplow addon for https://github.com/angulartics/angulartics and noticed that the page URL seems to be inferred. In an Angular app where hash routing is used, it would be nice to be able to override the page path use for tracking.

Has this been discussed/planned already?

**Comment by alexanderdean** [comment]
Hey @timelf123 ! This would be awesome (and is long-awaited #179). Assigning to @fblundun to follow up with you...

**Comment by timelf123** [comment]
Awesome, thanks @alexanderdean

**Comment by fblundun** [comment]
@timelf123 is this already covered by the [setCustomUrl](https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#232-setting-a-custom-page-url-and-referrer-url) API call?

Example usage:

```javascript
snowplow('setCustomUrl', mycustomurl);
snowplow('trackPageView');
```

**Comment by timelf123** [comment]
> On a single-page app, the page URL might change without the page being reloaded. Whenever an event is fired, the Tracker checks whether the page URL has changed since the last event. If it has, the page URL is updated and the URL at the time of the last event is used as the referrer. If you use setCustomUrl, the page URL will no longer be updated in this way.

@fblundun in the context of an SPA, manually setting the URL with `setCustomURL()` every time the route changes and then firing a pageview should do the trick, thanks. Does `setCustomURL()` apply to the next event then?

**Comment by alexanderdean** [comment]
Hi @timelf123 - exactly that, `setCustomURL()` applies to the next event fired (and in fact subsequent events like page pings until the custom URL is changed again).

**Comment by timelf123** [comment]
Excellent, this should be all I need to add an angulartics plugin for snowplow. Thanks again

**Comment by alexanderdean** [comment]
Thank you @timelf123 - super-excited about this!
