### ISSUE TITLE
change_form event doesn't work on fields with mask

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow-javascript-tracker#437]
We're using FormTracking to track changes and submits on our forms. We've noticed that the change_form event doesn't work when the field has an input mask.

Please see a live example at http://www.getninjas.com.br/reformas-e-reparos/pedreiro

To replicate:
- Fill in anything on the first step of the form
- On the second step, the "CEP" and "Telefone" fields have masks and don't trigger the change_form event
- All other fields work as expected

**Comment by alexanderdean** [comment]
Thanks for raising @bernardosrulzon ! Assigning to @fblundun for investigation...

**Comment by fblundun** [comment]
Hi @bernardosrulzon ,

I've tried duplicating the HTML for your form locally and it does fire change_form events for all fields. Is it possible that you are validating those fields with JavaScript which swallows the `change` event created when those fields are altered, preventing the event handler set by the JS Tracker from being called?

**Comment by enriquesaid** [comment]
@bernardosrulzon,

**My solution:**
Call this code on "complete" callback (once the mask has been completed):
```
var event = document.createEvent('HTMLEvents');
var el = this[0]; // using jQuery

event.initEvent("change", true, false);
el.dispatchEvent(event);
```

**Comment by bernardosrulzon** [comment]
Great stuff, @enriquesaid! And thanks for looking into it, @fblundun. I think we can safely close this now.
