### ISSUE TITLE
Investigate part of batch being sent twice 

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#438]
The observed situation:

Two sets of 3 events.
For each set, all events in that set have the same collector_tstamp and the same dvce_tstamp, implying that they were sent as part of a batch POST request (unless the timestamps are the same by coincidence).
For each set of events, two events in that set get duplicated but the third does not. This suggests that the 
only part of a batch is being resent, which shouldn't really happen.

@bogaert is this an accurate description of your findings?

**Comment by bogaert** [comment]
Thanks @fblundun!

This is the pattern:

dvce_tstamp  | collector_tstamp | event_id | network_userid
------------- | ------------- | ------------- | -------------
1  | 1  | A | X
1  | 2  | A | Y
2  | 1  | B | X
2  | 2  | B | Y
3  | 1   | C | X
4  | 2  | D | Y

**Comment by fblundun** [comment]
Thanks!

**Comment by fblundun** [comment]
Pushing back...

**Comment by chuwy** [comment]
Pushing back.

**Comment by paulboocock** [comment]
We've made a number of alterations to batching and how we send requests since this issue was raised. Closing but can reopen if anyone is still effected by this issue.
