### ISSUE TITLE
Enable the possibility to set a custom user_fingerprint

### ISSUE THREAD

**Issue by alejandro-hendrix** [snowplow/snowplow-javascript-tracker#439]
Currently, if we want to assign our own fingerprint, the only way is through a custom context that needs to be sent with any event. Custom contexts require the creation of a custom schema with all its tedious process.
Having a custom context for a single UUID is a bit of an overkilling solution and it also creates unused data (the default user_fingerprint field).

**Comment by alexanderdean** [comment]
Thanks for suggesting @alejandro-hendrix - scheduling...

**Comment by paulboocock** [comment]
Closing as we have removed all fingerprinting functionality in #549
