### ISSUE TITLE
Investigate different domain_userid having the same domain_sessionid

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-javascript-tracker#442]
We found one case (a client using JS-tracker 1.5.2) where the number of distinct `domain_sessionid` is between 50 to 100% higher than the number of `domain_userid || domain_sessionidx`.

It appears that this is driven by different `domain_userid` (often on different domains) having the same `domain_sessionid`.

In SQL:

``` sql
SELECT
domain_sessionid,
COUNT(DISTINCT domain_userid || domain_sessionidx) AS user_sessionidx,
COUNT(DISTINCT domain_userid)
FROM atomic.events
GROUP BY 1
ORDER BY 2 DESC
LIMIT 50
```

Needs to be investigated further.

**Comment by fblundun** [comment]
One idea we investigated: that the UUID generation was not generated sufficiently randomly. We use the standard Node UUID library. If it fails to find `window.crypto.getRandomValues` or `window.msCrypto.getRandomValues`, it will [fall back on Math.random](https://github.com/broofa/node-uuid/blob/309512573ec1c60143c257157479a20f7f1f51cd/uuid.js#L36-L37) which is not guaranteed to return unique values.

[This compatibility chart](http://caniuse.com/#feat=getrandomvalues) has information about which browsers support `getRandomValues`. Chrome for Android apparently does support it, but the problem of duplicated domain_sessionid sometimes appears for Chrome for Android. So falling back on `Math.random` doesn't explain this.

**Comment by paulboocock** [comment]
Closing in favour of #499
