### ISSUE TITLE
Investigate pageUnloadTimer causing the page to hang in Chrome

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#444]
A user with an AngularJS page reports:

"I had set it to 300ms instead of default 500ms. When this parameter exists in the configuration, link tracking does NOT work in Chrome. The browser becomes unresponsive and page cannot be used anymore and needs to be shutdown. When I removed this parameter in the initialization, link tracking works in Chrome. This parameter has no impact on Firefox and Safari."

I have unsuccessfully tried to reproduce this in Chrome using the example async-small.html page. Perhaps this issue is related to AngularJS specifically? It's surprising that reducing the wait period from 0.5s to 0.3s would make the page less responsive.

**Comment by paulboocock** [comment]
Closing as no updates in 5 years, likely no longer an issue.
