### ISSUE TITLE
Placeholder for video plays

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#445]
Promote video-related events to capture:
- Plays
- Pauses
- Fast forward / skip forward
- Rewind / skip backward

We need a set of dimensions to capture metadata related to the video (Video ID etc...)

We need a set of metrics related to the video view e.g. start time, finish time, number of ads shown, CPM etc.

We need to decide which would be supported by standard named dimensions / metrics, and which would only be supported by individual clients using custom dimensions / metrics.

**Comment by alexanderdean** [comment]
Migrated from https://github.com/snowplow/snowplow/issues/155

**Comment by paulboocock** [comment]
Closing in favour of https://github.com/snowplow/snowplow-javascript-tracker/issues/805
