### ISSUE TITLE
Placeholder for adding track() methods for all Google Analytics enhanced ecommerce entities

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#447]
Similar to these here:

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#measuring-activities

Under the hood these new track() methods should use the entities defined in Iglu Central for GA EE and be functionally similar to the guide here: https://github.com/snowplow/snowplow/wiki/Integrating-Javascript-tags-with-enhanced-ecommerce

**Comment by jbeemster** [comment]
Split and committed the methods.
