### ISSUE TITLE
Add Optimizely contexts

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#448]
Optimizely delivers a [data object](http://developers.optimizely.com/javascript/reference/index.html#the-data-object) on websites running Optimizely. This contains a load of useful data.

The proposal is to send this data into Snowplow as custom context.

A couple of things make this difficult:

1. The [data object](http://developers.optimizely.com/javascript/reference/index.html#the-data-object) contains an *enormous* amount of data
2. The [data object](http://developers.optimizely.com/javascript/reference/index.html#the-data-object) has a complicated structure

As a result, I think we should:

1. Break it down into a smaller set of contexts
2. Give users the choice which to send (i.e. multiple contexts)
3. Do some transformation of the data structure in the JS, prior to sending it into Snowplow, so that it is easier to process and load

I propose the following contexts:

1. experiment
2. state
3. variation
4. visitor
5. visitor_audience
6. visitor_dimension

The associated schemas are available [here](https://github.com/snowplow/iglu-central/tree/optimizely/schemas/com.optimizely)

Note that apart from visitor, it is likely that there will be multiple contexts for each other type with each event i.e. 1 state context for every experiment that is currently running.

For an initial release, we could either:

1. Only releasing support for the `state` context
2. Releasing support for a subset of the contexts
3. Release support for all contexts

Users should explicitly be able to say which of the Optimizely contexts they want tracked in Snowplow (e.g. specify if they want to capture experiments, state, variations, visitor data, visitor_audience (segments) and visitor_dimensions.

An example of the raw Optimizely data object is given [here](https://gist.github.com/yalisassoon/cb9e37fd872e280ae75c).

An example of the same data transformed into the different contexts listed in Iglu is given [here](https://gist.github.com/yalisassoon/a5ecef98f794cd245ac4).

What do you think @alexanderdean ?

**Comment by alexanderdean** [comment]
All sounds good @yalisassoon ! I think for the first release we should release support for all contexts:

1. Once @jbeemster has got up to speed on all the Optimizely data, hopefully it's only incremental effort to support all the contexts (versus just `state`) 
2. We do JS Tracker releases infrequently currently, so probably wouldn't add the remaining contexts for a long time

**Comment by jbeemster** [comment]
Sounds good!  So it will be a case of taking the __data__ object, extracting the relevant JSONs from it and then flattening them down.

With instrumentation do we have to wait to send any events until the required contexts have been fetched/processed?

**Comment by alexanderdean** [comment]
I believe we won't have to delay sends - we'll just attach whatever is available when we track the events. If that leads to patchy attach rates, we can re-evaluate...

**Comment by jbeemster** [comment]
I guess it all depends on the load order of snowplow vs optimizely really.

**Comment by fblundun** [comment]
That's how the PerformanceTiming context works: for each event, attach it if it's available.

**Comment by jbeemster** [comment]
@yalisassoon : I am correct in thinking that the highlighted fields need to be switched?https://github.com/snowplow/iglu-central/blob/optimizely/schemas/com.optimizely/state/jsonschema/1-0-0#L19-L25
