### ISSUE TITLE
Add support for users opting out of state tracking using cookie or localStorage

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#459]
http://www.allaboutcookies.org/manage-cookies/opt-out-cookies.html

Piwik supports this:
http://piwik.org/docs/privacy/#step-3-include-a-web-analytics-opt-out-feature-on-your-site-using-an-iframe

I'm not sure if opt-out cookies are a good way to give end users control over what is tracked per-se, but I like the idea of making it easier for Snowplow users to give their users the option to opt out of cookie tracking.

**Comment by alexanderdean** [comment]
Bringing forwards as we are doing lots of work in this area anyway

**Comment by alexanderdean** [comment]
Similar to the current `respectDoNotTrack`, let's add an option `respectOptOutCookie`

**Comment by BenFradet** [comment]
As @alexanderdean and I discussed, we're thinking of providing a `setOptOutCookie` method and if the cookie has been set we don't do any tracking.

**Comment by robertbakker** [comment]
What about an opt-in cookie ?
With a users consent the cookie will be set and only then snowplow will track.
So the user never gets cookies when they do not want to be tracked.

**Comment by alexanderdean** [comment]
Hey @robertbakker - feel free to create a new ticket to propose this idea!

**Comment by danny-andrews** [comment]
From the diff, it looks like `respectOptOutCookie` is not actually used anywhere.

**Comment by danny-andrews** [comment]
The `respectOptOutCookie` config option has no effect, but it is still referenced in the [docs](https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#22-initialising-a-tracker).

**Comment by alexanderdean** [comment]
@chuwy - is this a bug?

**Comment by BenFradet** [comment]
This is most likely an artifact of when we changed approach regarding the opt-out cookie.

**Comment by alexanderdean** [comment]
@BenFradet - can we create a new ticket to tidy this up?

**Comment by BenFradet** [comment]
Yup, I also removed it from the wiki.

**Comment by danny-andrews** [comment]
Thanks!
