### ISSUE TITLE
IE8 support is missing

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow-javascript-tracker#463]

**Comment by alexanderdean** [comment]
Hi @0xABAB - when you create a ticket in GitHub, the Snowplow engineering team receives notifications and starts exploring the ticket. If you find that your ticket is mistaken, please add a comment explaining why and close the ticket - don't delete the ticket body and close the ticket without comment.

**Comment by ezefranca** [comment]
https://github.com/contact?report=0xABAB
