### ISSUE TITLE
Add ability to change field content before sending form tracking

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow-javascript-tracker#465]
When i enable form tracking, i would like to be able not only to filter the fields, but als provide a function to change the field value programmatically. For example find fields with class email and transform it into an md5 hash. Of course the transform should only be executed if whitelist and filter let the respective field through.

```
var config = {
  forms: {},
  fields: {
    filter: function (field) {
      return field.class == "email";
    },
    transform: function(value) {
      return md5(value);
    }
  }
};
```

Cheers.

**Comment by fblundun** [comment]
This is an interesting idea... Would the transform change the content of the submitted form, or just the value sent in the Snowplow event?

**Comment by christoph-buente** [comment]
Just of the values being sent to SnowPlow.

**Comment by fblundun** [comment]
Yes, that makes sense. There's a similar idea in [this ticket](https://github.com/snowplow/snowplow/issues/860). Potentially we could do this in a way which doesn't just apply to forms: you would globally configure which fields to transform across all your custom events, together with the corresponding transformation functions.

**Comment by alexanderdean** [comment]
I like the idea of offering:

* The ability to globally configure fields to transform
* Helpers for specific scenarios (like form tracking or geolocation) so that users don't have to be aware of the specific events/contexts which those helpers generate

**Comment by alexanderdean** [comment]
Scheduling

**Comment by fwahlqvist** [comment]
If it would be possible to add a salt and select the transform method  it would be even better (SHA128/256 etc)

**Comment by christoph-buente** [comment]
@fwahlqvist if you can implement a callback function prior to sending the event, you can essentially do whatever you want. Also salt+crypting it.

**Comment by christoph-buente** [comment]
But @alexanderdean no-one is assigned to it anymore 😢

**Comment by mariendev** [comment]
Any updates on this issue? We would also love this feature to filter out data.

**Comment by alexanderdean** [comment]
Let's move this forwards into the current release.
