### ISSUE TITLE
Add Optimizely summary context

### ISSUE THREAD

**Issue by digdeep** [snowplow/snowplow-javascript-tracker#466]
The current approach suffers from logging too much data with an event model requiring taxing queries on analysis.
It will cost us us more money to store and higher difficulty to analyse.

**Comments on current tables** (brevity is the soul of wit) 
- 'optimizelyExperiments': this logs the full list of experiments running on every page view - overkill
- 'optimizelyStates': this is important to subset only the active experiment not log everything
- 'optimizelyVariations': current table logs everything tied to that user - overkill
- 'optimizelyVisitor': why do we need this? makes no sense when you have atomic events for visitor data. 
- 'optimizelyAudiences': why do we need this? makes no sense when you have atomic events for Audience data. 
- 'optimizelyDimensions': not that important, you should safely ignore this in most use cases, unless someone actually has real segments. 
  (deviceCategory is not a dimension and can be replicated with atomic events) 

Rather than log everything, set an event when the page you are on is part of an active experiment. This means you can set it in the base snowplow tracker once and not worry about false positives logging data on 6 reference tables for every page view. In the DesignCrowd example, they have 15 experiments so every page view is logging info on each experiment. In my test case running in GTM, I ended up logging 2,500 events just refreshing a handful of pages. 

Try the following which should set the value ONLY when the target location State = true. 

Go to https://www.designcrowd.com/ and insert the below in console. 
_(do note I am not good at JS but you should figure out what is happening here and prettify it)_

``` javascript
if (window['optimizely'].data.state.activeExperiments.length !== 0) {
  xxx = window['optimizely'].data.state.activeExperiments
  dataLayer.push({"optimizely": {
  "activeExperiments": window['optimizely'].data.state.activeExperiments, //need to confirm if this can set multiple values
  "variation": window['optimizely'].data.state.variationIdsMap[xxx],
  "conditional": window['optimizely'].data.experiments[xxx].conditional,
  "manual": window['optimizely'].data.experiments[xxx].manual,
  "name": window['optimizely'].data.experiments[xxx].name
}});
};
```

Repeat process by Clicking the **Get started now** button taking you to step 1.
Compare results from previous output. Different experiment ID, name, variation.

Lastly, repeat again here: http://www.designcrowd.com/how-it-works 
This last example has no active state therefore does not send an event. 
#### Putting it together
- All we are doing is making sure the page you are on is active state, then grabbing the specific experiment details (name, variation) you are seeing. 
- That is all you need for analysis. Domain_userid +  optimizely.name, optimizely.variation will give you everything you need to compare A versus B.

**Comment by kingo55** [comment]
Completely agree Narbeh.

All we need is the experiment and treatment assigned at exposure.
Everything else can be calculated at analysis.

Also, I've never been a fan of attaching the data as contexts.

1. We are defining that the test unit should be a user at collection... But
what if you're interested in sessions as a test unit?
2. Gargantuan amounts of data to store, query and analyse... When all you
really need is the exposure time, test name and treatment.
3. Large contexts drop off CF collector hits.

As for what you have proposed Narbeh, I think that's pretty sound. I assume
you would trigger an event for every active experiment?

**Comment by digdeep** [comment]
Spot on Robert, ideally the JS should fire only when the page you are on is part of an active experiment. 

You can achieve this using ```window['optimizely'].data.state.activeExperiments``` in the data object.

**Comment by kingo55** [comment]
Indeed... And then there's tests on things other than pages.

**Comment by yalisassoon** [comment]
Hi @digdeep , this is great, many thanks!

So if I understand you correctly, you want the Javascript tracker to return a JSON like the following for every active experiment that is currently running:

```json
{
	"activeExperimentId": "5277980204",
	"variation": "5263801276",
	"conditional": false,
	"manual": false,
	"name": "DC-6121 [CRO] [A/B Test] Step1 - Easier design type selection (RESTART w/ 2 VARS)"
}
```
This JSON would be constructed using the following logic:

1. Inspect `window['optimizely'].data.state.activeExperiments`: this returns an array of active experiments. We should return one active experiment context (like the one above) for each active experiment that is running.
2. Use the activeExperiment IDs returned in (1) to lookup the associated variation ID, conditional, manual and name fields

The actual logic for doing those lookups is provided in the JS you shared, but that JS assumes that there's only one experiment running so we'd need to generalize it for the case when more are running.

Does that sound right? If so, we'll put together a discrete set of tickets and tee up a follow-up release.

@alexanderdean and @jbeemster - any comments / feedback?

Thanks again,


Yali

**Comment by alexanderdean** [comment]
Sounds good to me!

**Comment by digdeep** [comment]
Hi @yalisassoon this looks great. Thanks!

**Comment by digdeep** [comment]
Looks like the logic needs updating to support multiple tests running in a page at any one time. I will update this ticket in the coming days with new JS.

**Comment by yalisassoon** [comment]
Brilliant - many thanks @digdeep

**Comment by alexanderdean** [comment]
Renamed ticket
