### ISSUE TITLE
Extend performance timing context with load trigger information

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-javascript-tracker#467]
From: https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API

> The window.performance.navigation object stores two attributes that can be used to know if a page load is triggered by a redirect, back/forward button or normal URL load.
> - TYPE_NAVIGATENEXT: Navigation started by clicking on a link, or entering the URL in the user agent's address bar, or form submission, or initializing through a script operation other than the ones used by 
> - TYPE_RELOAD: Navigation through the reload operation or the location.reload() method.
> - TYPE_BACK_FORWARD: Navigation through a history traversal operation.
> - TYPE_UNDEFINED: Any navigation types not defined by values above.

In short, it would tell us what kind of page view it was (new, reload or back/forward).

The last field that would be useful to add is the redirect count:

> window.performance.navigation.redirectCount will indicate how many redirects have taken place until the final page has been reached, if any.

**Comment by alexanderdean** [comment]
Pushing back

**Comment by paulboocock** [comment]
This API is now deprecated.
We should now look to use: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming

**Comment by paulboocock** [comment]
Closing due to deprecated API and we don't plan to extend current Performance Timing.
