### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by jramos** [snowplow/snowplow-javascript-tracker#469]
Getting a console error when trying to do manual linkClick tracking.

```
tracker.js:24 Uncaught TypeError: Cannot read property 'apply' of undefined
```

Any ideas?

**Comment by jramos** [comment]
Turning off respectDoNotTrack fixed it.

**Comment by alexanderdean** [comment]
Are you saying that trackLinkClick errors if respectDoNotTrack is on?

**Comment by jramos** [comment]
My mistake. That wasn't the actual problem. The documentation is just incorrect, and I was inputting the parameters in the wrong order.

https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#trackLinkClick

The `targetUrl` needs to come first. I.e.

```
snowplow_name_here('trackLinkClick', 'http://www.example.com', 'first-link', ['class-1', 'class-2'], '', 'this page', optionalCustomContexts);
```

**Comment by alexanderdean** [comment]
Ah great, migrated over for a doco fix
