### ISSUE TITLE
Remove deprecated visibility state check

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow-javascript-tracker#470]
In Chrome 49.0.2623.87, version 2.5.3 of Snowplow JavaScript:

```
'mozHidden' and 'mozVisibilityState' are deprecated.  Please use the unprefixed 'hidden' and 'visibilityState' instead.
```

**Comment by fblundun** [comment]
@0xABAB thanks for pointing this out. We can prevent the message appearing by terminating the loop [here](https://github.com/snowplow/snowplow-javascript-tracker/blob/4e52a258dba248d824c360941caadd338f9e4490/src/js/tracker.js#L1301) if `documentAlias[prefixPropertyName(prefix, 'hidden')] === false`.

**Comment by alexanderdean** [comment]
This is also present in Firefox Beta 47
