### ISSUE TITLE
Make it possible to disable updates to the referrer

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#476]
Because of #337, whenever the URL changes without the page reloading, the tracker sets the referrer to the previous URL.

Workaround: just call `snowplow('setReferrerUrl', document.referrer);` before sending any events.

**Comment by paulboocock** [comment]
The standard behaviour seems to be the correct one for SPAs. Utilising this workaround seems fine to me for anyone who wishes to implement the tracker in such a way that they are changing referrers as they navigate through a SPA.
