### ISSUE TITLE
Use passive event listeners for mouse wheel event

### ISSUE THREAD

**Issue by orzage** [snowplow/snowplow-javascript-tracker#478]
A mouse wheel event (mousewheel and DOMMouseScroll) listener, simply by being attached, causes significant performance issues.

See https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md for details on the problem.

That page also provides a proposal for passive event listeners, which work around the problem by making the event not cancelable (using preventDefault will not do anything useful.) Since SnowPlow does not use preventDefault, this should be a perfect fit. Passive event listeners are currently scheduled for release with Chrome 51 / Opera 38: https://www.chromestatus.com/feature/5745543795965952.

Finally, to prevent this from being an issue when passive event listeners are not available, the mouse wheel event listeners should either not be attached by default (at least unless passive event listeners are available) with a mechanism to enable them or, at the very least, should provide a means to declaratively disable these event listeners from ever being attached when not passive.

**Comment by alexanderdean** [comment]
Thanks for raising @orzage ! We take any performance impacts of the Snowplow JavaScript Tracker on the hosting page very seriously. Assigning to @fblundun to review...

**Comment by fblundun** [comment]
Thanks for pointing this out @orzage. A configuration option to disable those listeners when passive listeners are unavailable sounds like a good idea - we probably shouldn't make it disabled by default since this would break backwards compatibility. Do you know whether this also applies to `scroll` events?

**Comment by orzage** [comment]
That sounds reasonable.

This does not apply to scroll events since they are not cancelable. If you are considering switching to using scroll events in place of the mouse wheel events, then yes, that could be a viable solution and a good compromise.

**Comment by RByers** [comment]
That is correct - `wheel` and `touch*` events are the only problem here (`scroll` events are already asynchronous, don't actually block scrolling, though if they hog the CPU they can still be a perf issue of course).  Thanks for pushing on this!

**Comment by pdufour** [comment]
Any update on this? Can all the "activity" handlers here https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L1179-L1191 be marked as passive? Seeing this warning in the console `Handling of 'mousewheel' input event was delayed for 107 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.`

**Comment by alexanderdean** [comment]
Hi @pdufour - no update on this just yet, but we hope to get started on 2.7.0 in about 2 weeks' time.

**Comment by yalisassoon** [comment]
Green light assuming the end result is functionally equiv to today

**Comment by OliverJAsh** [comment]
Any updates on this? Anything we can do to help?

**Comment by alexanderdean** [comment]
Hey @OliverJAsh - no update on this yet, it remains in the backlog.

**Comment by OliverJAsh** [comment]
I raised a PR for this here: https://github.com/snowplow/snowplow-javascript-tracker/pull/641

**Comment by OliverJAsh** [comment]
Actually I'm not sure we need `DOMMouseScroll`, as it's already async apparently:

> The DOM DOMMouseScroll event is fired asynchronously when mouse wheel

https://developer.mozilla.org/en-US/docs/Web/Events/DOMMouseScroll

**Comment by alexanderdean** [comment]
Many thanks @OliverJAsh !

**Comment by mhadam** [comment]
It seems as though DOMMouseScroll and mousewheel are deprecated - wheel is now used by modern browsers. I've added a detector to find which one is supported and put it in `browserFeatures`. Likewise for the passive event listener detector.

I think it would be cleaner and easier to maintain if we call all these features in from [Modernizr](https://modernizr.com), but it doesn't have proper passive event listener detector support yet. I've made a PR on their project, hopefully it'll get fixed, but in the meantime [detect-passive-events](https://github.com/rafrex/detect-passive-events) serves us fine.

**Comment by OliverJAsh** [comment]
@mhadam Thanks for doing that! Your changes look good to me. Are they ready to be merged?

**Comment by mhadam** [comment]
@OliverJAsh Seems ready to me, outside of the test failure I see on Travis.

We won't merge this directly, we generally only merge into master by bundling changes into larger releases. Though I don't know how severe the performance impact is here, so perhaps it's worth adding into an incremental/bugfix release.

**Comment by OliverJAsh** [comment]
> Though I don't know how severe the performance impact is here, so perhaps it's worth adding into an incremental/bugfix release.

We are keen to use this on unsplash.com to remove jank from scrolling on feeds. It's not severe amount of jank, but it would be very nice to fix nonetheless!

Or, if you think you'll do a release anyway in the next 2 weeks then perhaps wait?

**Comment by OliverJAsh** [comment]
Hi @mhadam, do you have any updates on this?

**Comment by mhadam** [comment]
It's slated for the next release (there's no timeline for that right now).

**Comment by OliverJAsh** [comment]
Hi @mhadam, do you think we could release this as a patch, without waiting for other changes? Many users would benefit.

**Comment by mhadam** [comment]
There’s a release scheduled tentatively within the next couple weeks or so, so I should be able to add this in.

**Comment by alexanderdean** [comment]
Good idea, we had some other things drop out of that release. Bringing forwards...

**Comment by OliverJAsh** [comment]
Just monitoring the progress on this. For reference, it looks like the [commits attached to this issue](https://github.com/snowplow/snowplow-javascript-tracker/compare/issue/478) were moved into the [`release/2.10.0` branch](https://github.com/snowplow/snowplow-javascript-tracker/tree/release/2.10.0).

I guess that will be released soon? :-)

**Comment by OliverJAsh** [comment]
Sorry to pester, but is it possible for us to release this standalone in a release, so we don't have to keep waiting?

**Comment by mhadam** [comment]
Hi @OliverJAsh, you can try out 2.9.1-RC3 to test if this fixes the issue.

It's available here:
http://d1fc8wv8zag5ca.cloudfront.net/2.9.1-rc3/sp.js

**Comment by OliverJAsh** [comment]
@mhadam We're about to roll it out, but before we do, is there a changelog for this version so we're aware of any other changes?
