### ISSUE TITLE
Navigation Timing: connectStart almost never set

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-javascript-tracker#480]
It appears that `connect_start` in `org_w3_performance_timing_1` is _almost_ never set to an actual timestamp. Instead, it's set to `0` in 80% of events and to `NULL` in the other 20%.

According to the [W3 spec](https://www.w3.org/TR/navigation-timing/):

> This attribute must return the time immediately before the user agent start establishing the connection to the server to retrieve the document. If a persistent connection [RFC 2616] is used or the current document is retrieved from relevant application caches or local resources, this attribute must return value of domainLookupEnd.

The relevant bit of SQL:

```
select
  round(connect_start/100000000000), -- easier reading of unix timestamps
  count(*)
from atomic.org_w3_performance_timing_1
group by 1
order by 1
```

**Comment by bogaert** [comment]
This might be an issue with WebKit/Safari (versions 8 and 9).

**Comment by paulboocock** [comment]
Closing as this will be superseeded by #794 and #648
