### ISSUE TITLE
Navigation Timing: some fields have incorrect timestamps

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-javascript-tracker#481]
This issue happens in rare cases (< 1%) and appears to be restricted to these 3 fields:
- `response_end`
- `unload_event_start`
- `unload_event_end`

The Unix timestamp will be something like `2848430533766` (around 28-29XX..X). This looks like it's 2x the value it should be. Dividing by two usually gives a result that's within a few hours of what it should be.

**Comment by bogaert** [comment]
This might be an issue with WebKit/Safari (versions 8 and 9).

**Comment by paulboocock** [comment]
Closing as this will be superseeded by #794 and #648
