### ISSUE TITLE
Firefox 47.0a2 (2016-04-05) outputs "No element found" on console

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow-javascript-tracker#482]
When downloading the tp2 tracking pixel (via the 2.6.1 JS release), it returns `no element found` on the console. This is a bug in Firefox[1], which requires a workaround, which is not implemented in 2.6.1. I have not done any investigation as to how this can best be resolved, but I thought it was fairly important to let you know.  

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=884693

**Comment by fblundun** [comment]
Thanks for noticing this @0xABAB. Testing shows that this doesn't actually prevent the tracker from sending data successfully - it just creates an unsightly error message in the console. Interestingly this happens even when the status code 200, not just 204 or 304 as described in the linked ticket.

Looks like we can stop this just by returning e.g. `HttpResponse(entity = "ok")` from the collector. Do you know if there is a workaround we can implement on the client side?

**Comment by 0xABAB** [comment]
@fblundun It looks like it is in XML Expat parsing in Firefox, which means that misery already has happened before you can actually do something about it. 

I tried 
```
window.onerror = function(message, url, lineNumber) {  
        // code to execute on an error  
        return true; // prevents browser error messages  
    }; 
```
, but that doesn't work, which probably means it is unavoidable on the client side.

**Comment by alexanderdean** [comment]
Sounds like we need to close this one and create tickets for both collectors?

**Comment by 0xABAB** [comment]
Yeah, that would be a good step forward.

**Comment by fblundun** [comment]
Thanks for your help @0xABAB - I have created tickets to deal with this on the server side.
