### ISSUE TITLE
Add ability to set true timestamp

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#484]
For events where you know when they occurred exactly

**Comment by alexanderdean** [comment]
Bringing forwards

**Comment by bogaert** [comment]
@yalisassoon Do you have particular use case in mind? (drawing a blank here)

**Comment by chuwy** [comment]
#532 also introduces changes in API which makes API a bit fragile. So it would be wise to push these two timestamp-related tickets back if there's no need in it.

**Comment by alexanderdean** [comment]
Hey @chuwy - how does this make the API "a bit fragile" - can you be more specific?

**Comment by chuwy** [comment]
@alexanderdean if in some point we'll decide to add new argument - where it should go? If it should be before timestamp - users sending timestamp will brake their trackers. It's not such a problem in other languages because they at least have named argument or even static typing, but I easily can believe someone can brake their JS trackers.

**Comment by yalisassoon** [comment]
I can't comment on the API fragility issue I'm afraid

Although I can't think of a specific example for when you'd set the true timestamp in a JS environment, we've had two community members +1 this ticket and it'd be nice to have feature parity across all our trackers, so keen we support this. (That doesn't mean it needs to be part of the next milestone, but it should definitely be on the roadmap.)

**Comment by chuwy** [comment]
I agree that if it has *any* value (which is proved by +1) - we should support it and shouldn't be concerned about API fragility.

**Comment by alexanderdean** [comment]
Let's go for it, and create a separate ticket to figure out how to get to a more strongly typed invocation mechanism for the `track()` methods (if possible), versus the current "stringly typed array" approach.
