### ISSUE TITLE
Base 64 encoding long payloads results in truncation

### ISSUE THREAD

**Issue by kingo55** [snowplow/snowplow-javascript-tracker#486]
Hi guys,

We have been trying some longer unstructured event payloads recently but I'm finding the Base64 encoding is truncating the result. For example, take the following event:

```
snowplow("trackUnstructEvent", {
    schema: "iglu:io.mintmetrics.notes/note_event/jsonschema/1-0-0",
    data: {"variable":"sdhjsdjkfjskdhsfjfjasfjkdshafdskfjkdshsjklafhdfhadslfhadskljfhdskljfhasfkjsdhadjklhfadlshfdkafhdklafhdjkalhsfldjhfkldshjdksahfjkadlshfkjshdjkdsahfjdsahfjksdhfjdksalhfdskalhfjkdlhfkdhsafkasldhfjkdlashfkdsahfkldjshfkdlsjahfjkalsdhfkljdshfkdsahfjsdkfhdjsfjkdshfkldhsjakfhkdlshfjdjsklhflasdhfkldsahfaklsdfhsdafhdalshfalsdjhflasd?"}
});
```

Which produces the following base 64 encoded string.

```
eyJzY2hlbWEiOiJpZ2x1OmNvbS5zbm93cGxvd2FuYWx5dGljcy5zbm93cGxvdy91bnN0cnVjdF9ldmVudC9qc29uc2NoZW1hLzEtMC0wIiwiZGF0YSI6eyJzY2hlbWEiOiJpZ2x1OmlvLm1pbnRtZXRyaWNzLm5vdGVzL25vdGVfZXZlbnQvanNvbnNjaGVtYS8xLTAtMCIsImRhdGEiOnsidmFyaWFibGUiOiJzZGhqc2Rqa2Zqc2tkaHNmamZqYXNmamtkc2hhZmRza2Zqa2RzaHNqa2xhZmhkZmhhZHNsZmhhZHNrbGpmaGRza2xqZmhhc2ZranNkaGFkamtsaGZhZGxzaGZka2FmaGRrbGFmaGRqa2FsaHNmbGRqaGZrbGRzaGpka3NhaGZqa2FkbHNoZmtqc2hkamtkc2FoZmpkc2FoZmprc2RoZmpka3NhbGhmZHNrYWxoZmprZGxoZmtkaHNhZmthc2xkaGZqa2RsYXNoZmtkc2FoZmtsZGpzaGZrZGxzamFoZmprYWxzZGhma2xqZHNoZmtkc2FoZmpzZGtmaGRqc2Zqa2RzaGZrbGRoc2pha2Zoa2Rsc2hmamRqc2tsaGZsYXNkaGZrbGRzYWhmYWtsc2RmaHNkYWZoZGFsc2hmYWxzZGpoZmxhc2Q_In19fQ
```

This results in the following truncated JSON:

```
{"schema":"iglu:com.snowplowanalytics.snowplow/unstruct_event/jsonschema/1-0-0","data":{"schema":"iglu:io.mintmetrics.notes/note_event/jsonschema/1-0-0","data":{"variable":"sdhjsdjkfjskdhsfjfjasfjkdshafdskfjkdshsjklafhdfhadslfhadskljfhdskljfhasfkjsdhadjklhfadlshfdkafhdklafhdjkalhsfldjhfkldshjdksahfjkadlshfkjshdjkdsahfjdsahfjksdhfjdksalhfdskalhfjkdlhfkdhsafkasldhfjkdlashfkdsahfkldjshfkdlsjahfjkalsdhfkljdshfkdsahfjsdkfhdjsfjkdshfkldhsjakfhkdlshfjdjsklhflasdhfkldsahfaklsdfhsdafhdalshfalsdjhflasd__
```

When we try the base 64 encode function in the libs folder in this repo, there aren't any issues.

It's not a big deal I suppose as we can always switch the encoding off and pass the raw JSON in ue_pr

Any ideas where I should look to find the issue?

EDIT: We're on 2.5.2 and I couldn't find any issues fixed or outstanding mentioning this issue.

**Comment by fblundun** [comment]
Hi @kingo55,

Have you tested whether these test events successfully make it through enrichment?

The JS Tracker uses URL-safe Base64. This differs from the usual encoding in that it removes all `=` and replaces `+` with `-` and `/` with `_` so the output is safe to use in a URL.

The `?` in your test input causes this difference to become apparent.

Try using [this tool](http://kjur.github.io/jsjws/tool_b64udec.html), configuring it to convert from Base64URL to UTF-8.

**Comment by paulboocock** [comment]
Worth considering this issue again when we look at #694

**Comment by paulboocock** [comment]
Tested this in 2.14.0 and no longer appears to be an issue.
