### ISSUE TITLE
Update Selenium version to 2.48.0

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#487]

**Comment by fblundun** [comment]
Just increasing the version causes the following error:

```
UnknownCommand: [POST http://(redacted)@localhost:4444/wd/hub/session/d27b279edf084aa0a1c03c597ad8395c/timeouts/implicit_wait / {"ms":5000}] Unknown command: setTimeout (WARNING: The server did not provide any stacktrace information)
```

It seems that the error goes away if we remove the calls to setFindTimeout.

**Comment by fblundun** [comment]
This seems to cause intermittent errors, perhaps because I removed the `setFindTimeout` calls. I don't think this needs to be in a patch release anyway so I am rescheduling for 2.7.0.

**Comment by chuwy** [comment]
I believe this is SauceLabs/Selenium or intern bug, and we cannot just remove `setFindTimeout`, therefore I think we can update to last working selenium version, which is 2.48.0 and wait some [information](https://github.com/theintern/intern/issues/678) about a bug.
