### ISSUE TITLE
Don't send invalid viewport dimensions

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#488]
http://discourse.snowplowanalytics.com/t/javsscript-tracker-samsungbrowser-4-0-viewport-issue/167

This seems to happen specifically on Samsung devices.

**Comment by bogaert** [comment]
It’s not always 0x-56. Here are some other examples:

`Field [vp]: [0x-224] does not contain valid view dimensions`

`Field [vp]: [996x-32] does not contain valid view dimensions`

**Comment by bogaert** [comment]
It appears that `Field [vp]: [996x-32] does not contain valid view dimensions` happens on the Mac (not Samsung), while the `[0x-]` errors all happen on Samsung devices.

**Comment by fblundun** [comment]
I can think of 2 ways to deal with this:

1. Update the tracker logic to round negative dimensions up to 0
2. Change [this regex](https://github.com/snowplow/snowplow/blob/b772f6e089bb9e0b3bdbed93a4ab18902c4f1a4a/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/ClientEnrichments.scala#L43) to allow negative numbers

If we think that the negative dimension information is somehow useful we should do 2. Otherwise we can just do 1. @alexanderdean @yalisassoon @bogaert any reason why we would want to keep the negative viewports?

**Comment by fblundun** [comment]
I suppose the third way would be to discover that the negative values are caused by a bug in our JavaScript, but I can't find anything wrong with our viewport size detection code.

**Comment by bogaert** [comment]
If we don't see a bug, I'd round it up to zero.

**Comment by alexanderdean** [comment]
Makes sense to me...

**Comment by ninjabear** [comment]
Could this be caused by a signed vs unsigned integer representation problem?

**Comment by fblundun** [comment]
[This](https://github.com/snowplow/snowplow-javascript-tracker/blob/15cecb7bf398aa02d251ea6fc7f0a6a0eff5940e/src/js/lib/detectors.js#L155-L162) is the viewport dimension detection code. I don't think it is introducing any minus signs - I think it is more likely that the DOM properties it accesses are already negative.

**Comment by ninjabear** [comment]
Ah sorry that's what I mean - that Samsung devices may be incorrectly exposing it as an unsigned integer, but it's being treated as signed by Javascript (making it appear negative).

**Comment by alexanderdean** [comment]
Right. Thinking about this - why are we using a false flag value of 0 if
the viewport is corrupt - why not just not send the datum...

**Comment by alexanderdean** [comment]
Right - my point is, if the viewport is corrupted, we should just not send
it (null viewport), rather than send in an inaccurate viewport (it's not in
truth 0 pixels wide).

**Comment by fblundun** [comment]
If the width is corrupted but the height isn't, sending no viewport at all would lose the height information. Do you think that's an acceptable sacrifice?

**Comment by alexanderdean** [comment]
How do we know the height isn't corrupted? If the underlying cause is
anything like @ninjabear's suggestion, they are both broken, it's just only
one of them is probably so...

**Comment by alexanderdean** [comment]
*provably

**Comment by fblundun** [comment]
In the end we decided to just drop both fields when either is negative.

There is an SO question about this [here](http://stackoverflow.com/questions/37653284/when-can-window-dimensions-or-document-dimensions-be-nonpositive).

**Comment by bogaert** [comment]
That's a good solution.
