### ISSUE TITLE
Only call navigator.javaEnabled on instances of Navigator

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow-javascript-tracker#491]
This error happened with one of our clients: 

Error message: Can only call Navigator.javaEnabled on instances of Navigator

https://github.com/snowplow/snowplow-javascript-tracker/blob/4e52a258dba248d824c360941caadd338f9e4490/src/js/lib/detectors.js#L224

```
{
 "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2",
  "userAgentInfo": {
    "browserName": "Safari",
    "browserVersion": "7.0.6",
    "engineName": "AppleWebKit",
    "engineVersion": "537.78.2",
    "isBot": false,
    "isMobile": false,
    "os": "Intel Mac OS X 10_9_4",
    "platform": "Macintosh"
  },
```

**Comment by fblundun** [comment]
Thanks for reporting this @christoph-buente. Surprisingly, I can't find any Google results for `"on instances of Navigator"`. It's strange that `window.navigator` wouldn't be an instance of Navigator...

**Comment by christoph-buente** [comment]
It's happening in an old Safari 7, not sure if that is relevant. But i thought i give a notice, that those things are happening. Browser compliance is a minefield.
