### ISSUE TITLE
Check whether elements of navigator.plugins array are undefined

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow-javascript-tracker#492]
https://github.com/snowplow/snowplow-javascript-tracker/blob/4e52a258dba248d824c360941caadd338f9e4490/src/js/lib/detectors.js#L131

```
{
"userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rrLxV2Yh-48) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36",
  "userAgentInfo": {
    "browserName": "Chrome",
    "browserVersion": "50.0.2661.94",
    "engineName": "AppleWebKit",
    "engineVersion": "537.36",
    "isBot": false,
    "isMobile": false,
    "os": "Windows 10",
    "platform": "Windows"
  }
}
```

**Comment by fblundun** [comment]
Thanks for reporting this @christoph-buente. The only explanation I can think of is that the `navigator.plugins` array can be sparse (i.e. contain undefined elements). We could fix this by only skipping the inner loop if `navigatorAlias.plugins[i]` is `undefined`.
