### ISSUE TITLE
Stop using String.startsWith

### ISSUE THREAD

**Issue by dursk** [snowplow/snowplow-javascript-tracker#493]
Specifically on IE11 in Windows 10 (seems fine in Windows 7/8), the library is trying to do `string.startsWith` somewhere, which, according to MDN, IE does not support.

**Comment by fblundun** [comment]
Thanks for spotting this @dursk.
[This](https://github.com/snowplow/snowplow-javascript-tracker/blob/15cecb7bf398aa02d251ea6fc7f0a6a0eff5940e/src/js/lib/helpers.js#L361) is the offending call.

See also https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
