### ISSUE TITLE
Error: Access is denied

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow-javascript-tracker#494]
https://github.com/snowplow/snowplow-javascript-tracker/blob/4e52a258dba248d824c360941caadd338f9e4490/src/js/lib/detectors.js#L213

```
{
  "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko",
  "userAgentInfo": {
    "browserName": "Internet Explorer",
    "browserVersion": "11.0",
    "engineName": "Trident",
    "engineVersion": "",
    "isBot": false,
    "isMobile": false,
    "os": "Windows 7",
    "platform": "Windows"
  }
```

**Comment by fblundun** [comment]
Thanks for raising this @christoph-buente. Do you have a screenshot or stack trace for the error?

**Comment by christoph-buente** [comment]
I linked the line of code, where this happens. But i send you an email with more detail.

**Comment by fblundun** [comment]
[This](http://stackoverflow.com/questions/13378985/permission-denied-when-accessing-navigator-useragent-in-ie9) looks related...

**Comment by fblundun** [comment]
@christoph-buente any idea whether that group policy setting in Active Directory could be to blame?

**Comment by christoph-buente** [comment]
I'm not really familiar with Windows and IE, but this looks like a really arcane bug :)

**Comment by fblundun** [comment]
Pushing back as we don't understand this bug...

**Comment by chuwy** [comment]
Pushing it back.

**Comment by paulboocock** [comment]
Probably same odd issue as #498

**Comment by paulboocock** [comment]
Closing as `browser-features` is now a deprecated plugin and we've never quite managed to reproduce this.
