### ISSUE TITLE
Remove all support for _snaq

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#496]
https://github.com/snowplow/snowplow-javascript-tracker/blob/15cecb7bf398aa02d251ea6fc7f0a6a0eff5940e/src/js/init.js#L51-L52

**Comment by fblundun** [comment]
This also means we can lose [this](https://github.com/snowplow/snowplow-javascript-tracker/blob/15cecb7bf398aa02d251ea6fc7f0a6a0eff5940e/src/js/in_queue.js#L170-L173).

**Comment by paulboocock** [comment]
Resolved with #557
