### ISSUE TITLE
Error: A device attached to the system is not functioning.

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow-javascript-tracker#498]
Another weird error message that we received from a website using the snowplow tag. Just to let you know. I don't even have an idea to reproduce that error.

stracktrace says it's happening here: 

https://github.com/snowplow/snowplow-javascript-tracker/blob/9db3104548c6e762eba65fd28bd4c3de48bba8a9/src/js/lib/detectors.js#L220

```
{
  "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko",
  "userAgentInfo": {
    "browserName": "Internet Explorer",
    "browserVersion": "11.0",
    "engineName": "Trident",
    "engineVersion": "",
    "isBot": false,
    "isMobile": false,
    "os": "Windows 7",
    "platform": "Windows"
  }
```

**Comment by paulboocock** [comment]
Closing as `browser-features` is now a deprecated plugin and we've never quite managed to reproduce this.
