### ISSUE TITLE
Page view ID doesn't regenerate in rare cases

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-javascript-tracker#500]
Affects about 0.01% of page views on our website. The visitor will browse to another page and the page view ID remains the same. The events appear to be from real users and different browsers and platforms.

**Comment by bogaert** [comment]
It's a little stranger than I first thought.

Ten different `domain_userid` on different browsers (Chrome and Firefox) and platforms, and from different locations. All look like legitimate users.

In each case, the following happens:

- a page view and page pings are sent from a page on our website
- a single page ping with the same event ID is sent with `page_url  = http://snowplowanalytics.com/privacy/` (which all pages on our site link to)

Not an important issue, but I'm leaving it open nonetheless in case other people find similar edge cases.

**Comment by chuwy** [comment]
Pusing back.

**Comment by alexanderdean** [comment]
@BenFradet - @chuwy can probably help on this one...

**Comment by BenFradet** [comment]
@bogaert 

@chuwy mentioned that he changed how page view ids are generated in 2.7.0, have you seen the bug recently (if you've switched to 2.7.x)?

**Comment by bogaert** [comment]
@dilyan can you take a look?

**Comment by dilyand** [comment]
I had a look and was not able to find any events that match what @bogaert describes in version 2.7.x. My query returned results matching the odd behaviour for version 2.6.x, but nothing after that.

**Comment by BenFradet** [comment]
@dilyand thanks a lot for investigating! :+1:

**Comment by bogaert** [comment]
Thanks @dilyand. How big was the dataset for 2.7.X? It affected about 0.01% of page views before.

**Comment by dilyand** [comment]
The data set for 2.7.x had 541,492 events, not counting robot/spider users.

**Comment by bogaert** [comment]
Thanks!

**Comment by chuwy** [comment]
I assume this was implicitly resolved by https://github.com/snowplow/snowplow-javascript-tracker/issues/436

**Comment by alexanderdean** [comment]
Thanks everybody!
