### ISSUE TITLE
Use modularized imports for lodash

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow-javascript-tracker#502]
There is a version of lodash, that does not need to be prebuilt. You can easily require the submodul you need in your code. And then browserify will filter out unrequired code. 
https://www.npmjs.com/browse/keyword/lodash-modularized

For example isArray: https://www.npmjs.com/package/lodash.isarray

That would make it much easier to use snowplow itself as an npm module.

**Comment by mhadam** [comment]
@alexanderdean should be fine, I've used a module with the work I'm doing with global contexts, though it seems to make `concat` complain:
https://github.com/gruntjs/grunt/issues/662

It should be fixable, but still trying to find a workaround.
