### ISSUE TITLE
Form Tracking not working with dynamically added fields in form that exists

### ISSUE THREAD

**Issue by Koen87** [snowplow/snowplow-javascript-tracker#503]
See issue on discourse below:
http://discourse.snowplowanalytics.com/t/form-tracking-not-working-with-dynamically-added-fields-in-form-that-exists/416/1

**Comment by alexanderdean** [comment]
Thanks for raising, scheduled

**Comment by makoto** [comment]
Hello. Any plan this is going to be fixed?

**Comment by alexanderdean** [comment]
Hey! Yes it's scheduled for the next-but-one release.

**Comment by makoto** [comment]
Cool. Are there any branch which includes the fix?

**Comment by alexanderdean** [comment]
No, that would show up in a GitHub link if so...

**Comment by paulboocock** [comment]
Closing in favour of #748
