### ISSUE TITLE
Add an option to change life of the visitor cookie, or disable, on tracker creation

### ISSUE THREAD

**Issue by Ouriel** [snowplow/snowplow-javascript-tracker#504]
Hi,

I was looking into the tracker and saw that the lifetime of the cookie is hard-coded to 2 years.
The problem for me is in France, the CNIL (national organization for liberty and privacy) set the maximum life of a cookie to 13 months. 
I think a configuration argument on the creation of the tracker could be helpful for that, same as for the session timeout or Do Not Track.
I suppose the only change is on the line 169 in this file to get the argument from argmap.
https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js
I can make a pull request with the change if you want.

Regards,
Matthieu

**Comment by alexanderdean** [comment]
Sounds great - PR welcome @Ouriel !

**Comment by Ouriel** [comment]
Just created the pull request
#505

**Comment by yalisassoon** [comment]
Hi @chuwy - I think the documentation is missing the detail on how you disable cookie tracking?
