### ISSUE TITLE
Add ability to send previous session ID with all events

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#510]
Mirroring equivalent functionality in other client side trackers.

Note that this is blocked until the client-session data is moved into the dedicated client session context. (Otherwise there isn't a 'slot' available for the new data.

**Comment by bogaert** [comment]
Let's make it optional. Some users have concerns about request size and would like to disable this field.

**Comment by paulboocock** [comment]
We now support the client_session context in the JS Tracker

https://github.com/snowplow/snowplow-javascript-tracker/issues/1077
