### ISSUE TITLE
`form_id` to take either `name` or `id` value of the form

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow-javascript-tracker#511]
The `form_id`, despite its name, will take the value of the `name` attribute of the `<form>` tag on `submit_form` event. The actual `id` of the form is irrelevant, right? Would it make sense to use either of them (`name` or `id`) with priority given to one of them?

**Comment by yalisassoon** [comment]
Update so that `form_id` is the id and `form_name` is the name

**Comment by RoAsHrOaSh** [comment]
is there any update on this issue?

**Comment by RoAsHrOaSh** [comment]
@yalisassoon @chuwy @alexanderdean 
Hi Guys, could one of you post an update on this issue?

**Comment by paulboocock** [comment]
Sorry for not updating this ticket sooner when asked. 
To clarify our stance on this:
Form Tracking will now place one of the following into the `form_id` attribute (in this order until a match is found):
- 'name'
- 'id'
- 'type'
- 'nodeName'

If you wish to track additional data about the form, then we suggest using the dynamic context callback that will pass the <form> element as a parameter, see here: https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#custom-form-tracking
