### ISSUE TITLE
Explore using foreign fetch to allow event resend even when off site

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#513]
https://developers.google.com/web/updates/2016/09/foreign-fetch

> Imagine, for instance, that you’re an analytics provider. By deploying a foreign fetch service worker, you can ensure that all requests to your service that fail while a user is offline are queued and replayed once connectivity returns. While it’s been possible for a service’s clients to implement similar behavior via first-party service workers, requiring each and every client to write bespoke logic for your service is not as scalable as relying on a shared foreign fetch service worker that you deploy.

**Comment by paulboocock** [comment]
Foreign fetch is no longer available for testing in Chrome, and has been removed from the service worker specification.
