### ISSUE TITLE
Add callback when trackers are ready

### ISSUE THREAD

**Issue by sircelsius** [snowplow/snowplow-javascript-tracker#514]
I'd love to be able to know exactly when my trackers have been created and added to the tracker dictionary.

Something along the lines of

```
snowplow('newTracker', 'tname', <...>)
.then(function(tracker) {
  tracker('trackPaveView')
})
```

Would be awesome.

This would be cool because:
- It would prevent issues of the type `No tracker defined` that happen when trying to send events before `newTracker` has returned.
- It would allow to chain events efficiently (i.e make sure that `pageView` is always sent before my first `trackStructEvent`, which would later allow for more accurate device timestamps).
- Our system has a ton of JS clutter, so we had to wrap `trackPageView` inside a timeout, which in turn made it so that some page views are never sent (nor added to `localStorage`) before our users navigate to other pages.

@bogaert

**Comment by chuwy** [comment]
One more usecase: http://discourse.snowplowanalytics.com/t/error-tracking-in-the-javascript-tracker-2-7-0/1022/2

It's pretty easy to end up calling `trackError` when `newTracker` was not yet called, especially using tag manager. Having this callback we could be sure:

```
// After error occurred - wait until newTracker called and call trackError
window.addEventListener('error', function (e) {
  snowplow_name_here(function () { window.snowplow('trackError', e.message) }, null, 'newTracker')
})
```

This will buffer errors until tracker namespace is available and send them.

**Comment by ecoron** [comment]
The tracker should also trigger a Javascript-Event. Such an event could be used for several on the tracker depending tasks, especially if the tracker is loaded asynchron. it also avoids to end up in a callback hell. 
Finally it would be good if the tracker provides both options.

**Comment by chuwy** [comment]
One more usecase: in some situations (especially with GTM) it is not possible to call `newTracker` exactly once. While double call doesn't harm - it prints warning to console, which should be not observed by end-user. With `newTracker`-callback it would be safer to call it once.

**Comment by paulboocock** [comment]
The tag snippet creates a queue now that means it is safe to call snowplow functions before it is loaded and in addition there is a callback function that will execute when the tracker is loaded with the tracker dictionary available on `this`.
https://github.com/snowplow/snowplow/wiki/3-Advanced-usage-of-the-JavaScript-Tracker#41-callbacks
