### ISSUE TITLE
Add a method to start a new session

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-javascript-tracker#515]
Sessionization is now purely based on time since the last event. We could add a method that, if called, resets the session ID and increments the session index.

Possible use cases:
- a user switches accounts
- a user completes a purchase and returns to the homepage

See also: https://github.com/snowplow/snowplow-objc-tracker/issues/290

**Comment by alexanderdean** [comment]
@bogaert can you provide a little more information for Mike on this?

**Comment by alexanderdean** [comment]
Nudge @bogaert

**Comment by bogaert** [comment]
We got this request once or twice from a user. Right now, we start a new session if the last event was 30 or more minutes ago (i.e. when the session cookie has expired). However, there are cases when a user of Snowplow might want to expire a session sooner. For instance, when a user completes a transaction and returns to the homepage, one could consider the previous session complete. When the user returns to the homepage (or continues to any other page), this would start a new session, reflecting that the user has completed the previous unit of work, and is starting a new one.

I hope this explanation makes sense!

I don't think there's need for this to be in 2.9.0 though, given that there's been little user demand. I think server-side sessionization is the better approach in these cases.

**Comment by alexanderdean** [comment]
Cool, it's not a biggie so we will probably just include it as an easy add.
