### ISSUE TITLE
More support for 'context generating functions'

### ISSUE THREAD

**Issue by adamlwgriffiths** [snowplow/snowplow-javascript-tracker#519]
As per comment here: http://discourse.snowplowanalytics.com/t/selective-custom-contexts-for-link-click-events-js-tracker/624

There is a need to dynamically attach contexts to events - as mentioned here https://github.com/snowplow/snowplow-javascript-tracker/issues/372 - using 'context generating functions' (re: callbacks from here onwards).

The reason being, that it is sometimes important to add custom data as part of a callback like mechanism.
At the least, event functions which can be triggered automatically should have this support.

These would be:
- Link click
- Form submission
- Form change

As part of these 'automatically triggered events', I believe it is important that the callback receive the event information so that it may have enough information to selectively add a new context, or not.

My specific case is the `link_click` events.
'enableLinkClickTracking' automatically monitors and triggers these events, which means I have no mechanism to add extra context information to them.
In this case, I would like the callback to receive the link data, so that may inspect it and see if a custom context should be added.
I want to see if specifically decorated links have been clicked, if so, add custom context data to them. But _only_ for specific links.

Essentially:

```
function callback(link, element, ...)
  if link matches pattern
    return custom context
  else
    return null
```

**Comment by alexanderdean** [comment]
Thanks @adamlwgriffiths - this makes a lot of sense. What should the args to the callback be for the form submission|change events?

**Comment by adamlwgriffiths** [comment]
I don't currently have a use, so I cannot comment from experience.

I would think that passing the extracted event schema itself would be a good start.
I can also see the benefits of sending the actual DOM element through (rather than a string if it has already been processed).
There may be other uses of people wanting the actual event itself (mouse up, down, character delete, etc).

I think that would cover pretty much any use case I can think of.

**Comment by alexanderdean** [comment]
Thanks @adamlwgriffiths ! That's helpful.

**Comment by adamlwgriffiths** [comment]
For form change, there may also be a need to see the previous data, and the new data.
However, I'm not sure how useful it would be for the purposes of analytics.

**Comment by nesbtesh** [comment]
Hi what is the status of this?

**Comment by alexanderdean** [comment]
Hey @nesbtesh - it's currently scheduled for the next release (however, work has not started on this release yet).

**Comment by yalisassoon** [comment]
Hi @mhadam - has this been resolved with the launch of Global Contexts? (In which case we can close this issue.) Or have I misunderstood?

Thanks!

**Comment by mhadam** [comment]
Yes!

**Comment by yalisassoon** [comment]
Closing
