### ISSUE TITLE
Restrict package versions

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#522]
This may be something not very common in JS-development, but I find unreproducible builds extremely frustrating.

Problem: we use range (`~` and `^`) symbols in [list of dependencies](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/package.json#L5-L21), which means npm will download most recent version up to some point and therefore if we try to build same JS tracker `2.6.2` in different points in time - we'll get different dependency artifacts  and therefore different tracker artifacts and I don't even know what versions were used for publicly published sp.js.

Unreproducible builds mean we cannot keep track bugs/bugfixes, we can have artifacts that varying in size significantly and all kinds of implicitness. It doesn't even matter if it is `dependency` or `devDependency` - artifacts can be different anyway.

We could:
1. Make all versions explicit and bump it on every release. Or at least restrict for patch releases (`~`) - it shouldn't introduce bugs, at least, and differences in artifacts would be minimal.
2. Add explicit package versions to published artifacts.

**Comment by alexanderdean** [comment]
Makes sense, let's make this happen! I don't have a view on option 1 vs 2 - maybe @jbeemster does?

**Comment by jbeemster** [comment]
I would make all versions strict, it is what we do across every other product.  However we just need to be pro-active in moving to more recent versions to stay on top of updates.

**Comment by chuwy** [comment]
Agree. I don't mind to bump all dependencies and retest on each release.
