### ISSUE TITLE
Fix having a single variationId in Optimizely state context

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#530]
[This code](https://github.com/snowplow/snowplow-javascript-tracker/blob/4c2e720583d6283ea1bc61a622ea23826038cf36/src/js/tracker.js#L929-L932) makes tracker to send `variationId` iff there's only one element in array. It seems this array has single element in vast majority of cases, but still this is an array for some reasons and technically it can have more than one variationId (though I cannot understand why).

I [asked](https://community.optimizely.com/t5/Developers/Optimizely-global-object-s-schema/m-p/17825#M1541) this question on optimizely forums, but still no reasonable answer.

See https://github.com/snowplow/snowplow-javascript-tracker/issues/466

/cc @yalisassoon

**Comment by paulboocock** [comment]
The Optimizely code has moved on since this issue, with quite a few alterations plus a whole new version of Optimizely (OptimizelyX) that we have a new Summary context for.
