### ISSUE TITLE
Add inversion of control to tracker object

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#534]
Currently `Tracker` [is closed over](https://github.com/snowplow/snowplow-javascript-tracker/blob/a8470715e91231a32c3124c5bd019410fe845add/src/js/tracker.js#L95-L98) `core`, which is itself receiving callback with `OutQueue`. It means that we cannot decouple `Tracker` from payload transmitting logic. This all means that the only way to check tracker sends correct data is our pretty [hairy integration tests suite](https://github.com/snowplow/snowplow-javascript-tracker/issues/154).

If we could inject sending logic (`OutQueue`) to `Tracker` - we can test it in much simpler way.

**Comment by alexanderdean** [comment]
Awesome idea...

**Comment by paulboocock** [comment]
This is still worth investigating with the v3 refactor
