### ISSUE TITLE
Add AWS credentials to .travis.yml

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#537]
* `AWS_ACCESS_KEY`
* `AWS_SECRET_KEY`

Note that the following will be hardcoded outside of .travis.yml:

* `AWS_S3_BUCKET`
* `AWS_REGION`
* `AWS_CF_DISTRIBUTION`

**Comment by alexanderdean** [comment]
Hey @chuwy - could we improve the names of a couple of these?

* `AWS_BUCKET` -> `AWS_S3_BUCKET`
* `AWS_DISTRIBUTION` -> `AWS_CF_DISTRIBUTION`

Also, could you clarify what the `AWS_BUCKET_KEYPATH` is for? The example suggests it's the whole S3 path including artifact name?

**Comment by chuwy** [comment]
@alexanderdean yes, updating names. Yes, keypath is full upload path. I believe this is because we want js asset name to be random to avoid adblockers filtering https://github.com/snowplow/snowplow-javascript-tracker/issues/461

**Comment by chuwy** [comment]
On `AWS_BUCKET_KEYPATH`. This is probably need to be autogenerated, instead of changing it on each release. Removing it.

**Comment by alexanderdean** [comment]
Added creds. Still need to configure permissions though...
