### ISSUE TITLE
Core: only send custom contexts if non-empty array

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#540]
This effectively reverts https://github.com/snowplow/snowplow-javascript-tracker/issues/292 and https://github.com/snowplow/snowplow-javascript-tracker/issues/296. We cannot use `1-0-1` because Kinesis Elasticsearch Sink still [checks context](https://github.com/snowplow/snowplow/issues/2927#issuecomment-259069597) for non-emptiness. This means KES will automatically send all events with empty contexts to bad rows.

**Comment by alexanderdean** [comment]
Hey @chuwy - I think this ticket name is a bit misleading. A better name would be "Core: only send custom contexts if non-empty array"

**Comment by chuwy** [comment]
Agree
