### ISSUE TITLE
Refr doesnt work with GET request

### ISSUE THREAD

**Issue by nesbtesh** [snowplow/snowplow-javascript-tracker#542]
The referer URL doesn't work with GET

**Comment by alexanderdean** [comment]
Hey @nesbtesh - can you provide more detail on this bug report please?

**Comment by nesbtesh** [comment]
Hey when I try sending everything in a get request it doesnt include the referer url

**Comment by chuwy** [comment]
Hey @nesbtesh, can you provide a public URL with tracking code?

**Comment by paulboocock** [comment]
Unable to reproduce this in 2.13.0. refr field is populated fine with GET requests.
Will reopen if we get a reproducable example.
