### ISSUE TITLE
Field [vp]: does not contain valid view dimensions 

### ISSUE THREAD

**Issue by 13scoobie** [snowplow/snowplow-javascript-tracker#544]
here are the two that come up the most: -56 and -224 along with vp, ds, res and vid attributes (if that helps provide context)

Field [vp]: [0x-56] does not contain valid view dimensions

Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G925T Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36
11:"res=360x640"
16:"vp=0x-56"
17:"ds=320x16978"
18:"vid=2"
Field [vp]: [0x-224] does not contain valid view dimensions

Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G920T Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36
11:"res=360x640"
16:"vp=0x-224"
17:"ds=320x1168"
18:"vid=2"

Ref: http://discourse.snowplowanalytics.com/t/field-vp-does-not-contain-valid-view-dimensions/848/3

**Comment by alexanderdean** [comment]
Regression on #488?

**Comment by paulboocock** [comment]
Looking at the code as it stands now, it is impossible (famous last words) to get negative values for the vp attribute and we don't seem to have any reports of this for 3 years. Closing, can reopen if this shows up again.
