### ISSUE TITLE
How do you track mouse position when adding a enableLinkClickTracking

### ISSUE THREAD

**Issue by nesbtesh** [snowplow/snowplow-javascript-tracker#550]
Hi I am trying to track mouse x and y position  when the user clicks a link. How do I do that?

**Comment by chuwy** [comment]
Hello @nesbtesh,

Could you please post your question on our support forum: http://discourse.snowplowanalytics.com/c/engineers/snowplow-trackers

Github issues for bug reports and features requests only.
