### ISSUE TITLE
Placeholder for supressing logging

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#556]
There's at least one use use-case for suppressed log output - particularly, some users cannot avoid calling `newTracker` twice. While it doesn't harm - it could be undesirable for end-user to see this message (if for some reason end-user open console). One more way to solve this particular problem is #514.

All other console output in tracker related to deprecated methods such as `setCookieNamePrefix`.

**Comment by chuwy** [comment]
Does it belong to https://github.com/snowplow/snowplow-javascript-tracker/milestone/33?

**Comment by alexanderdean** [comment]
Sure, added!
