### ISSUE TITLE
Add support for not recording any state

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#563]
As opposed to recording state in either cookies (the default) or localStorage (#506).

This is different from #459 - #459 assumes that the site owner wants to track state, but individual users want to opt out of this. By contrast, this ticket assumes that the site owner wants to disable all state tracking, perhaps because:

* They have very stringent security requirements
* Their target platform does not support cookies or localStorage
* The Snowplow client identification/sessionization algorithms (the major consumers of this state) are not meaningful to them

**Comment by BenFradet** [comment]
Could we reuse [`configDoNotTrack`](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L159-L160) since it seems to be already preventing the events from being sent to a collector?

**Comment by alexanderdean** [comment]
No, `configDoNotTrack` is whether the site author wants to respect the user's browser's DoNotTrack setting. That's user-specific.

**Comment by BenFradet** [comment]
So, we need another config that does the same job (prevent setting the cookies and queuing stuff for sending to the collector)?

**Comment by alexanderdean** [comment]
No, state is not the same as tracking. It's possible to track events without bothering to maintain any state.

Think of it as an enum:

`state: COOKIE | LOCAL_STORAGE | NONE`

**Comment by alexanderdean** [comment]
Changed the title to prevent confusion between recording state and tracking events
