### ISSUE TITLE
Fix non-linear incrementing of session index

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#568]
- lasts for as long as `sessionCookieTimeout`
- doesn't respect `heartbeatDelay` (multiple page pings per second despite an heartbeat of 5s)
- possible leads:
  - `configHeartBeatTimer` might somehow be `null` [here](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L1291) which would cause the callback to happen relentlessly
  - multiple [`setInterval`](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L1280) are set, that could be solved by `clearInterval` if we mean to have only one at any time

Session indices look like the following when ordered by `dvce_created_tstamp`:

![image](https://cloud.githubusercontent.com/assets/1737211/24855257/ee7e80a6-1dd8-11e7-87d1-0a5567620839.png)

which would suggest some kind of mad callback.

Tracker initialization looked like the following when the bug occurred:

```js
window._tracker("newTracker", "js", "", {
    appId: "",
    platform: "web",
    post: !0,
    cookieLifetime: 31536e4,
    contexts: {
        webPage: !0,
        performanceTiming: !0
    }
}), 
window._tracker("enableLinkClickTracking", null, !0, !0), 
window._tracker("refreshLinkClickTracking"), 
window._tracker("enableActivityTracking", 5, 5), 
window._tracker("trackPageView"),
```

**Comment by alexanderdean** [comment]
This ticket name needs to be improved! And fleshed out with some example data of the problem.

**Comment by BenFradet** [comment]
I'll update it once I've narrowed it down.

**Comment by BenFradet** [comment]
Still stuck on this one, trying to find a pattern with other users having encountered the same issue.

**Comment by BenFradet** [comment]
We're thinking `configHeartBeatTimer` might somehow be `null` [here](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L1291) which would cause the callback to happen relentlessly but this seems a bit far-fetched.

**Comment by alexanderdean** [comment]
Hey @BenFradet - `configHeartBeatTimer` - why don't we create a new ticket that puts a guard on the value of this, rather than just `&& configHeartBeatTimer`? I tried a setInterval with "" as the interval and yes it just triggered relentlessly...

**Comment by BenFradet** [comment]
@alexanderdean Do you propose having a default value when it's null?

**Comment by alexanderdean** [comment]
Hmm, no I'd probably just put guards onto both args in this function:

https://github.com/snowplow/snowplow-javascript-tracker/blob/0ba1bad19e276d381ffe214669042dde17a4d9fd/src/js/tracker.js#L1680-L1683

If either arg is not an int, then don't enable. Less magic that way.

**Comment by paulboocock** [comment]
This has altered considerably since this issue was created, including the addition of guarding to prevent relentless callbacks. Likely no longer an issue.
