### ISSUE TITLE
Documentation: add a warning about changing the cookie domain

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-javascript-tracker#577]
Changing the cookie domain will also “reset” all existing cookies (which are now set against the various subdomains). Changing the cookie domain is the better solution long-term, but it will also be a major one-time disruption, because all visitors to the website will receive a new domain_userid.

**Comment by alexanderdean** [comment]
Can you migrate to snowplow/snowplow please, that's where all documentation tickets reside.
