### ISSUE TITLE
Use Closure Compiler to reduce sp.js size

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow-javascript-tracker#583]
Using the [Closure Compiler](https://developers.google.com/closure/compiler/), I was able to reduce the  `sp.js` (version 2.8.0) size from 72k to 67k, a 7% improvement. And this is using the "Simple" optimization - we might be able to reduce it even further using "Advanced", though it will require reviewing the code to avoid breaking changes.

For now, we could run the simple optimization before pushing new versions to Cloudfront. It's done in seconds and saves eveyone a few milliseconds of load time - and maybe a few bucks on your CF bill :)

On a side note (this might be worth an issue for itself): we could also reduce the file size by compiling only the necessary methods. We're not using Optimizely, for example, and all of its methods are loading unnecessarily for the end user. As the number of integrations grow, that problem could become more pronounced. Is that something you're looking into?

**Comment by alexanderdean** [comment]
Thanks @bernardosrulzon ! I think this is well worth exploring - but represents a fairly big change in our pipelining, so putting into the 3.0.0...
