### ISSUE TITLE
Add ability to anonymize IP address

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#586]
Similar to Google Analytics, although supporting our more granular anonymization configuration.

This lets you anonymize all requests before a cookie wall is accepted; this way you can measure what percentage accepts cookies and what percentage doesn't.

If somebody doesn't accept the cookie wall you can never measure the IP address...

This is great for GDPR compliance. It also harmonizes Snowpow behavior with GA, which will be helpful after we deliver the GA->Snowplow integration.

**Comment by DoHe** [comment]
@alexanderdean are there any updates on this? This would be really important both for GDPR compliance and for the level of privacy we would love to offer our users.
I know we can already anonymize in the enrichment, but as far as I understand that we still would store the full ip in the collector logs (we're using the clojure collector). You also referenced the connected issue for the scala collector (https://github.com/snowplow/snowplow/issues/3248), are there similar plans for the clojure collector?

**Comment by alexanderdean** [comment]
Good point - adding this to the next release.

> are there similar plans for the clojure collector?

No, I'd suggest upgrading to the SSC if you want access to these capabilities in due course.

**Comment by paulboocock** [comment]
This should go hand in hand with #793 as an alternative option. Would be great to support either option or perhaps "levels" of anonymisation.

**Comment by paulboocock** [comment]
This is available using anonymous tracking released in v2.17.0+
