### ISSUE TITLE
Javascript sometimes sends invalid view dimensions in IE (multiple versions)

### ISSUE THREAD

**Issue by lehneres** [snowplow/snowplow-javascript-tracker#587]
We have seen occasionally an entry in `badEvents` which are caused by invalid view dimensions:

`{"line":"validBase64","errors":[{"level":"error","message":"Field [ds]: [1144x687.2000122070312] does not contain valid view dimensions"}],"failure_tstamp":"2017-06-17T11:28:17.232Z"}`

This could be tracked down to IE browsers. 

While not urgent, I thought we should let you know...

**Comment by alexanderdean** [comment]
Thanks for flagging, scheduling...
