### ISSUE TITLE
Fix string ids in Optimizely Summary context

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#591]
`activeExperiment` and `variation` always were numeric strings at the time of adding Optimizely Summary context. It seems that Optimizely changed behavior and now they send it as proper integers.

We probably need to update schema with `{"activeExperiment: {"type": ["integer", "string"]}}` and try to cast all ids to integer in tracker's code - in case of failure send as `string`.

See http://discourse.snowplowanalytics.com/t/optimizely-flags-payload-way-too-big/1254/10

**Comment by alexanderdean** [comment]
Why not just cast them as strings? I have no faith that Optimizely won't change them again if they run out of ints...

**Comment by chuwy** [comment]
Good point. We don't need to update schema then.

**Comment by cmardiros** [comment]
I have what might be a related issue to this:

In our tags we have

```
contexts: {
 ...
  optimizelySummary: true
}

```

We have a huge amount of bad rows like this

```
[{level=error, message=error: instance type (integer) does not match any allowed primitive type (allowed: ["string"]) level: "error" schema: {"loadingURI":"#","pointer":"/properties/activeExperimentId"} instance: {"pointer":"/activeExperimentId"} domain: "validation" keyword: "type" found: "integer" expected: ["string"] }]
```

Optimizely schema being used by the tracker is: 
```
iglu:com.optimizely.snowplow/optimizely_summary/jsonschema/1-0-0
```

I could be wrong, but it looks to me like the casting to string doesn't work properly based on `found: "integer" expected: ["string"]`

Is there a fix?

**Comment by alexanderdean** [comment]
What tracker version is this with @cmardiros ?

**Comment by cmardiros** [comment]
Ah of course, sorry. It's `2.7.2`

**Comment by alexanderdean** [comment]
Cool, you had me worried!
