### ISSUE TITLE
browser fingerprinting

### ISSUE THREAD

**Issue by wurma** [snowplow/snowplow-javascript-tracker#593]
The fingerprint generated in https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/lib/detectors.js#L115 doesn't seem very unique to me. 
Maybe using a more advanced method like [ClientJS](https://clientjs.org/)

**Comment by alexanderdean** [comment]
Won't fix, see #549. You can implement any browser fingerprint you want and send it with your events as a custom context.
