### ISSUE TITLE
Updated documentation to recommend discoverRootDomain as default

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplow-javascript-tracker#601]
If the tracker is implemented across various root domains, it feel like there should be an option to set the cookie domain dynamically, so that you can easily deploy the tracker across, eg:

www.mysite.com
blog.mysite.com
www.mysite.co.uk
application.mysite.co.uk
etc

Currently, we add this to the tracker tag:

```
function getDomain(url, subdomain) {
    subdomain = subdomain || false;
    url = url.replace(/(https?:\/\/)?(www.)?/i, '');

    if (!subdomain) {
        url = url.split('.');
        url = url.slice(url.length - 2).join('.');
    }

    if (url.indexOf('/') !== -1) {
        return url.split('/')[0];
    }

    return url;
};

var cookieDomain = (".").concat(getDomain(window.location.href));
```

and then:

```
(...)
cookieDomain: cookieDomain;
(...)
```

Maybe this should be the default?

**Comment by bogaert** [comment]
This would reimplement `discoverRootDomain`: https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#2219-automatically-discover-and-set-the-root-domain

That said, it should still be recommended as the default option in our documentation.

**Comment by mhadam** [comment]
Updated documentation in this wiki fork: mhadam/snowplow.wiki-fork@a963df2

**Comment by mhadam** [comment]
the documentation? or the feature suggested by @dilyan?

**Comment by alexanderdean** [comment]
Just the documentation...

**Comment by mhadam** [comment]
yes, it's been included

**Comment by alexanderdean** [comment]
Ace, thanks
