### ISSUE TITLE
Enforce that geolocation.timestamp is an integer

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#602]
We are getting reports that some browser(s) are sending in the `geolocation.timestamp` as a number with decimal point and 3 decimal places. Most likely this is a misguided attempt to provide millisecond precision as part of the timestamp.

Unfortunately we assume that `geolocation.timestamp` is an integer.

Fix: on this line:

https://github.com/snowplow/snowplow-javascript-tracker/blob/699632f6319c0f2025862a482149fe499958941a/src/js/tracker.js#L1336

we should box the value in a `Math.round()`.

**Comment by alexanderdean** [comment]
Adding the data-loss label as this validation failure will fail the event.

**Comment by alexanderdean** [comment]
Descheduling as this isn't a live issue in a browser. We should still do at some point though.

**Comment by miike** [comment]
@alexanderdean Any idea what browser/versions are sending this? If it's anything like [this bug](https://bugs.webkit.org/show_bug.cgi?id=48518) we may want to check the magnitude of the value and multiply by 1000 to convert to milliseconds.

**Comment by alexanderdean** [comment]
This was a false alarm - we should still do it but actually it was a customer with a mis-configured iOS tracker. So no burning platform but might as well put this in.
