### ISSUE TITLE
Publish unminified version

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-javascript-tracker#603]
...to simplify debugging, explore human-readable code and set breakpoints. Could be something like `2.8.1/sp-dev.js`.

It is not always possible to reproduce exact build that was several versions ago.

**Comment by alexanderdean** [comment]
This feels like a good idea... We will synchronize this with our plans to move away from hosting the JS Tracker for the community.

**Comment by paulboocock** [comment]
We shouldn't need this if we do #653
