### ISSUE TITLE
Remove respectOptOutCookie from the Tracker function comments

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-javascript-tracker#605]
https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L85

It's an artifact from a previous implementation.

**Comment by chuwy** [comment]
I have a feeling that these argmap docstring either misses or misrepresent many other properties. Need to double-check all of them.

**Comment by chrissherlock** [comment]
```userFingerprint``` doesn't seem to be used either.

**Comment by alexanderdean** [comment]
This commit @mhadam should match the ticket name
