### ISSUE TITLE
sp.js error 

### ISSUE THREAD

**Issue by waspesi** [snowplow/snowplow-javascript-tracker#608]
Hi,
The link click tracking is an automatic feature of the Snowplow library.  I'm not sure why it is not tracking the target url as it should be according to the documentation.  I've tried using the "manual" link click tracking to see if we manually pass our own targetURL, but there is an error thrown.  
See attached.  
![image](https://user-images.githubusercontent.com/29575504/30439598-3761582c-9942-11e7-92b7-0b9286596a6f.png)

I even tried this hardcoding this on a local test page without using Tealium and it still gives me the same error.  
See attached.  
![image](https://user-images.githubusercontent.com/29575504/30439631-51f36c84-9942-11e7-9614-f04cefc1ffa1.png)

I will have to defer to support from Snowplow at this point.  I am more than happy to get on a call with them to figure out what needs to be done at this point.  
Thanks!

**Comment by BenFradet** [comment]
Sorry for the useless redirection to this repo, but after looking at your issue it seems to be a support question and those are handled on our forums: https://discourse.snowplowanalytics.com/.

Again, sorry for the misdirection.
