### ISSUE TITLE
undefined usePost variable won't get set correctly in object.OutQueueManager

### ISSUE THREAD

**Issue by chrissherlock** [snowplow/snowplow-javascript-tracker#613]
In the function object.OutQueueManager (src/js/out_queue.js) there is the following line:

```javascript
usePost = usePost && window.XMLHttpRequest && ('withCredentials' in new XMLHttpRequest());
```

If `usePost` is set to true or false, then you get the desired outcome. Not so if for some reason `usePost` is undefined. Then you just get undefined. 

At least give a warning that it's undefined perhaps?

**Comment by BenFradet** [comment]
A undefined check first would make sense indeed, feel free to open a pull request :+1:

**Comment by chrissherlock** [comment]
Pull request submitted. I just emit a Console.warn(), hopefully this is sufficient for any dev that might be debugging...

**Comment by chrissherlock** [comment]
Hmmmm... we can't use Console.warn()?

**Comment by chrissherlock** [comment]
Sorry about before, try this patch.

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by snowplowcla** [comment]
@chrissherlock has signed the Individual Contributor License Agreement. Thanks so much

**Comment by paulboocock** [comment]
See note on #615
