### ISSUE TITLE
Fix al.optimizely.get is not a function error

### ISSUE THREAD

**Issue by markjensen74** [snowplow/snowplow-javascript-tracker#619]
We were comparing our Snowplow pageviews against Google Analytics pageviews and wondering why Snowplow was always lower after we started to use 2.8.2 and Optimizely Summary flags in JS. Is anyone else getting this? This optimizely error inside Snowplow Tracker is causing pageview event not to fire, which probably explaining why we are lower than GA. I’m using chrome.

```
sp.js:63 Uncaught TypeError: al.optimizely.get is not a function
    at aI (sp.js:63)
    at aa (sp.js:63)
    at a2 (sp.js:66)
    at bp (sp.js:61)
    at aK (sp.js:67)
    at sp.js:73
    at ae (sp.js:69)
    at Object.trackPageView (sp.js:73)
    at s (sp.js:29)
    at new d.InQueueManager (sp.js:29)
```

**Comment by markjensen74** [comment]
from one of my lead developers:

because that seems to be the problem… the `getOptimizelyXData` function in the SP tracker looks for `optimizely` to be defined, and then tries to call `optimizely.get`, which has been added in the optimizelyX JS API

(the `getOptimizelyData` function for the normal optimizely summary looks for both `optimizely` and `optimizely.data` to be defined before attempting access)

and that’s getting called in the initialization of the tracker… so if it errors out there, we get nothing.

**Comment by chuwy** [comment]
Hey @markjensen74, can you provide some more context? Are you using *both* `optimizelyXSummary` and `optimizelySummary`?

**Comment by markjensen74** [comment]
@chuwy yes we have both enabled at the same time.  here is our config:

 }(window, document, 'script', '//d1fc8wv8zag5ca.cloudfront.net/2.8.2/sp.js', 'GAplow'));

    window.GAplow('newTracker', 'cf-hosted-v2.8.2', this.spCollector, {
      appId: this.appId,
      platform: 'web',
      cookieDomain: '.generalassemb.ly',
      discoverRootDomain: true,
      cookieName: 'sp',
      encodeBase64: false,
      respectDoNotTrack: true,
      userFingerprint: true,
      userFingerprintSeed: 6485926835,
      pageUnloadTimer: 0,
      forceSecureTracker: false,
      useCookies: true,
      post: true,
      bufferSize: 1,
      maxPostBytes: 45000,
      cookieLifetime: 86400 * 180,
      contexts: {
        webPage: true,
        gaCookies: true,
        optimizelyXSummary: true,
        optimizelySummary: true
      }
    })

    window.GAplow('enableActivityTracking', 30, 30);
    window.GAplow('trackPageView');
    window.GAplow('enableErrorTracking');
    if (this.userCookieName) window.GAplow('setUserIdFromCookie', this.userCookieName);
  }

**Comment by chuwy** [comment]
Thanks, we're looking into it.

**Comment by alexanderdean** [comment]
We'll get this scheduled! Thanks for raising

**Comment by dannifreshbooks** [comment]
any updates on this?
