### ISSUE TITLE
Add trackConsentGranted method

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#623]
@yalisassoon to specify the arguments to be provided. Guessing there will be some kind of `consentDocumentId` and something around age/is-minor in there...

**Comment by alexanderdean** [comment]
Nudge @yalisassoon

**Comment by yalisassoon** [comment]
Hey @alexanderdean @mhadam 

So I think we need these underlying schemas:

```json
{
	"$schema": "http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#",
	"description": "Schema for consent document context",
	"self": {
		"vendor": "com.snowplowanalytics.snowplow",
		"name": "consent_document",
		"format": "jsonschema",
		"version": "1-0-0"
	},

	"type": "object",
	"properties": {
		"id": {
			"type": "string",
      "maxLength": 36
		},
    "version": {
			"type": "string",
      "maxLength": 36
		},
		"name": {
			"type": "string",
      "maxLength": 60
		},
    "description": {
      "type": "string",
      "maxLength": 10000
    }
	},
	"required": ["id", "version"],
	"additionalProperties": false
}
```

The consent_granted event would be sent with at least one consent document context. (You could in theory send this with multiple documents if a person consented to multiple things at the same time.) There'd only be one event-specific field in the consent_granted event: an optional expiry date:

```json
{
	"$schema": "http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#",
	"description": "Schema for consent granted",
	"self": {
		"vendor": "com.snowplowanalytics.snowplow",
		"name": "consent_granted",
		"format": "jsonschema",
		"version": "1-0-0"
	},

	"type": "object",
	"properties": {
    "expiry": {
      "type": "string",
      "format": "date-time"
    }
	},
	"additionalProperties": false
}
```

The `trackConsentGiven` method would then take the following arguments:

* document_id (required)
* document_version (required)
* document_name
* document_description
* expiry_date

**Comment by alexanderdean** [comment]
LGTM - @mhadam can you create the associated tickets in Iglu Central?

**Comment by alexanderdean** [comment]
Just a reminder to reword the commit (to match the ticket)

**Comment by mhadam** [comment]
The iglu event that's PR'd is consent_granted, let me know if you'd like that changed.

**Comment by alexanderdean** [comment]
Let's use Granted everywhere (schemas, method names, every tracker), sorry for confusion.
