### ISSUE TITLE
Bump semver to 4.3.2

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#625]

**Comment by mhadam** [comment]
Wondering if there's anything potentially wrong with npm-shrinkwrap.json changing significantly. I ran `npm install`, `npm install semver@4.3.2` and `npm shrinkwrap`.

**Comment by alexanderdean** [comment]
I'm afraid I don't know enough about this to have a view - perhaps @BenFradet, @chuwy or @lhache?

**Comment by lhache** [comment]
@mhadam seems related to your issue: https://github.com/angular/angular/issues/13935

**Comment by mhadam** [comment]
Ok. Seems like the npm-shrinkwrap.json file was outdated/referencing a package that isn't used in the project. I've updated the semver package to 4.3.2, and now npm-shrinkwrap.json defines the production packages(which is the default behaviour for npm). `npm prune --production` did the trick.
