### ISSUE TITLE
LocalStorage domain user ID is not persisted properly

### ISSUE THREAD

**Issue by acgray** [snowplow/snowplow-javascript-tracker#627]
When using the LocalStorage stateStorageStrategy the domain user id does not persist and is regenerated on every page load.

This appears to be due to an error in the `getSnowplowCookieValue` method, which attempts to retrieve cookie values using the logical cookie name instead of the value returned by `getSnowplowCookieName`:

https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L480

This seems like a major issue as it clearly makes the data recorded useless for any user-level analysis.

**Comment by BenFradet** [comment]
Nicely spotted!

I think we should incorporate this into 2.9.0 given how critical it is, wdyt @alexanderdean @mhadam @chuwy ?

**Comment by mhadam** [comment]
Seems like a good idea to me.

**Comment by alexanderdean** [comment]
Ouch! Many thanks for the spot @acgray. Scheduling...
