### ISSUE TITLE
Documentation: clarify behavior of bufferSize

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-javascript-tracker#631]
My understanding is that a `bufferSize` equal to 1 triggers `executeQueue` for every request: https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/out_queue.js#L194-L196

However, during queue "execution", the number of events to be sent is determined by `maxPostBytes`:
https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/out_queue.js#L234-L246

As a result, it's possible that we send multiple events despite `bufferSize` being equal to 1. This should be made clear in the documentation or behaviour should be changed.

**Comment by alexanderdean** [comment]
Thanks for flagging @BenFradet
