### ISSUE TITLE
Update OS X test targets for Saucelabs

### ISSUE THREAD

**Issue by mhadam** [snowplow/snowplow-javascript-tracker#632]
The Travis CI build failures seem to be because OSX 10.8 isn't supported anymore. I'll remove that platform. And since there's one OSX platform in the configuration that does work, I'll add the next available platform after that.

Here's the Saucelabs platform list: https://saucelabs.com/platforms

**Comment by chuwy** [comment]
Fine by me.

**Comment by alexanderdean** [comment]
Improved ticket name, please update commit

**Comment by chuwy** [comment]
Hey @mhadam just a heads-up that commit title needs to be changed.

**Comment by mhadam** [comment]
The tests hang when testing with Safari 7 on OSX10.9. It runs fine when that platform is removed. I'm assuming it's deprecated.
