### ISSUE TITLE
Install dependencies and update shrinkwrap before deployment

### ISSUE THREAD

**Issue by mhadam** [snowplow/snowplow-javascript-tracker#633]
During deployment, for some reason grunt and other packages aren't available. This is fixed by adding a line installing all npm packages in the project.

**Comment by chuwy** [comment]
I'm still quite puzzled on what happened between `2.8.2` and `2.9.0`.

**Comment by mhadam** [comment]
I had removed the semver commit thinking that's the only change that touches anything in Gruntfile.js, but that didn't have any effect. It might be worth seeing if 2.8.2 still deploys fine, although you'd have to apply the Saucelabs fix commit.

**Comment by chuwy** [comment]
Travis CI also adds a lot of chaos into this and most likely the it is the reason. I'm puzzled, but don't think it is worth to explore. Let's just fix it.

**Comment by alexanderdean** [comment]
Thanks guys

**Comment by mhadam** [comment]
I finally managed to make this build correctly - the problem seems to be due to a mix of production and development packages being needed at different steps of the build. I made it install all of them in the beginning.

It also seems that skipping cleanup during deployment is necessary since browserify takes some files from the nested/compiled core package.

The shrinkwrap file interfered too. Oddly enough, npm throws errors when a package in package.json is specified by git repo + tag, you have to include it by git repo + commit hash.

**Comment by alexanderdean** [comment]
Hero! Thanks @mhadam
