### ISSUE TITLE
Extend cookie configuration to support secure and same-site

### ISSUE THREAD

**Issue by mhadam** [snowplow/snowplow-javascript-tracker#634]
Create tracker settings to enforce that session cookies are created with the following attributes:

- secure
- same-site
- http-only

**Comment by alexanderdean** [comment]
@mhadam will explore these options.

**Comment by alexanderdean** [comment]
All three of them @mhadam ?

**Comment by mhadam** [comment]
Yes.

**Comment by alexanderdean** [comment]
I've removed http-only from the ticket. We'll probably close this ticket altogether.

**Comment by alexanderdean** [comment]
Created this ticket as a companion/successor: https://github.com/snowplow/snowplow/issues/3753

**Comment by yalisassoon** [comment]
Hey @mhadam - should we close this ticket given the requirement only seems to apply to server-set cookies ?

**Comment by Dreamsorcerer** [comment]
same-site and secure should still be useful, in what way are these only related to server-side cookies?
http-only would stop the JS from accessing the cookie, so probably not useful (unless the JS never reads the cookie it sets).

**Comment by paulboocock** [comment]
The cookies which the tracker sets are not sent with requests as headers but rather read by the tracker on send and added to the POST body. This means we can't use http-only.

As for SameSite and Secure, they could perhaps be useful to prevent other third parties from reading the cookie ID but again, given the use of our current JS set cookies it isn't a requirement. Investigating if SameSite=Lax would be beneficial for our JS cookies is worth some triage.

On a side note, our collector set cookies are sent with SameSite=None and Secure by default now.

**Comment by paulboocock** [comment]
This was done in 2.15.
