### ISSUE TITLE
Remove chromeFirstPaint from PerformanceTiming context

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow-javascript-tracker#635]
Currently we rely on `chrome.loadTimes` to populate the `chromeFirstPaint` value for the `iglu:org.w3/PerformanceTiming` schema.

`loadTimes` is deprecated[1] in Chrome 64 and will be removed in Chrome 71 (release early in December 2018). Google recommend[2] replacing this with values from the [PaintTiming](https://w3c.github.io/paint-timing/) spec/API instead though the spec for this is still in draft.

Once this is more widely implemented in browsers this could belong in it's own context rather than replacing the current first paint values.

[1] https://developers.google.com/web/updates/2017/12/chrome-loadtimes-deprecated

**Comment by alexanderdean** [comment]
Thanks for flagging @miike. Per the comments on the commit:

* What is the impact of leaving this in till late this year?
* Is there any ETA on the new spec being implemented by the major browsers?

**Comment by alexanderdean** [comment]
Nudge @miike

**Comment by miike** [comment]
Chrome currently has full support but the support in [other browsers](https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming#Browser_compatibility) is still non-existent at this stage.

**Comment by bermannoah** [comment]
Hi there, any word on when the fix in #636 might get merged? Anything else that needs to be done? (I figured I'd ask in the issue since the PR says it's been de-scheduled pending conversation here.)

**Comment by alexanderdean** [comment]
Thanks for asking @bermannoah - assigning to @mhadam to look into...

**Comment by miike** [comment]
I think this should be fine to remove now. If we want to grab paint values (in Chrome or other supported browsers) it makes sense to have these in a different paint specific context.
