### ISSUE TITLE
Canceled request with slow3g

### ISSUE THREAD

**Issue by asamoilich** [snowplow/snowplow-javascript-tracker#642]
During integration of snowplow JS tracker we found out that with slow connection we got canceled status with error : net_error = -3 (ERR_ABORTED) for requests with > 5sec time.(Easy reproduce with first call in browser private mode and turned on slow3g)

I had load https://d1fc8wv8zag5ca.cloudfront.net/2.6.2/sp.js1 and change there timeout to 10seconds.
After this changes our requests got success status.

Question: is it possible to add new param to set timeout ?

For example:
window.snowplow(‘newTracker’, ‘cj’, ‘{TRACKER_PIXEL}', { appId: '{APP_ID}’,
cookieDomain: ‘${COOKIE_DOMAIN}’,
timeout: 10000
});

**Comment by paulboocock** [comment]
This seems like a reasonable request. Default to the current 5000ms.

We should ensure the timeout configuration is considered here too: #770
