### ISSUE TITLE
Core: fix type incompatibility in consent methods

### ISSUE THREAD

**Issue by mhadam** [snowplow/snowplow-javascript-tracker#652]
The consent methods accept numbers for the id and version - they should accept strings to conform to the schema.

**Comment by alexanderdean** [comment]
Let's schedule this into a patch release.

**Comment by mhadam** [comment]
By that you mean 2.9.1, or add it to 2.10.0?

**Comment by alexanderdean** [comment]
Sorry yes, 2.10.0 is fine.
