### ISSUE TITLE
Add source maps into tracker

### ISSUE THREAD

**Issue by mhadam** [snowplow/snowplow-javascript-tracker#653]
Debugging the tracker could be enhanced by including source maps in order to decipher the minified code.

**Comment by alexanderdean** [comment]
Can we add this into this release - how big a job is it?

**Comment by alexanderdean** [comment]
This is why we ruled out Uglify before, not sure if things have changed:

https://github.com/snowplow/snowplow-javascript-tracker/issues/278

**Comment by mhadam** [comment]
Ran into some issues with deploying version 2.9.1 - it spits an error out during minifying. Possibly a yui-compressor problem. If that's the case, I'll have to narrow down if it's due to code in the newest release. Otherwise it might be worth re-exploring why Uglify can't be used, YUI Compressor really isn't maintained that much. If you were referring to [this line](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/tags/tag.js#L47) in #278, then I can probably figure a way to do that in Uglify.

**Comment by alexanderdean** [comment]
Hey @mhadam - sorry to hear about the difficulties. I think there's a line somewhere in the tracker which references some gnarly unicode characters. I think you'll need to trace that code so that you can verify that whatever uses those characters continues to function as you expect post-switch-to-uglify...

**Comment by juanstiza** [comment]
@mhadam were you using Node v10 or +7? I had a `Fatal error: Callback must be a function` error while running the `min:deploy` task. Maybe its related to this: [https://github.com/gruntjs/grunt-contrib-jasmine/pull/262](https://github.com/gruntjs/grunt-contrib-jasmine/pull/262).
