### ISSUE TITLE
browser es5/es6 polyfill support

### ISSUE THREAD

**Issue by epikhighs** [snowplow/snowplow-javascript-tracker#660]
I was curious if the authors have thought about introducing a polyfill for ES5 and ES6 language features?

I have a fork of this repo and was wondering if anyone else has tried or if there's some pitfall I should consider before introducing one.

**Comment by alexanderdean** [comment]
This is (I believe) in the scope for the new release we are working on - assigning to @mhadam to clarify...

**Comment by paulboocock** [comment]
In v3 we will be modernising the tracker, using ES modules and perhaps even a switch to typescript.
