### ISSUE TITLE
Remove wheel and passive event listener feature flags

### ISSUE THREAD

**Issue by rgabo** [snowplow/snowplow-javascript-tracker#661]
We have an existing batch pipeline that uses the latest JavaScript Tracker along with R87 components for Enrich and Storage.

All events recorded using 2.9.1 are now going into bad rows with the following error:

```json
{
    "errors": [
        {
            "level": "error",
            "message": "error: object instance has properties which are not allowed by the schema: [\"f_passive\",\"f_wheel\"]\n    level: \"error\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"/items\"}\n    instance: {\"pointer\":\"/0\"}\n    domain: \"validation\"\n    keyword: \"additionalProperties\"\n    unwanted: [\"f_passive\",\"f_wheel\"]\n"
        }
    ],
}
```

`f_passive` and `f_wheel` seems to have been introduced by the following commit: https://github.com/snowplow/snowplow-javascript-tracker/commit/a28888111dc8ea66ca8339396bd00a2f84c4d5db#diff-3e7c17598500b655533daae15e659338R275

It is unclear what other environmental factors are necessary for the issue to appear so I am listing everything that might be relevant:

 * Enrichment runs on R87
 * Tracker is configured to POST to the collector
 * At least one other vendor uses Snowplow on the pages where we are integrated into
 * Static Iglu repositories are used for resolution (iglucentral.com and one private)

I have not yet been able to find the JSON schema that the "web" portion of the events are validated against and I am now investigating upgrade paths. It would be helpful if someone could point me to where the validation occurs so I can identify the earliest version the issue would be fixed with.

Thanks!

**Comment by BenFradet** [comment]
Hey @rgabo , thanks for the report, we're aware of the issue with 2.9.1 and will be doing a patch release cc @mhadam

**Comment by rgabo** [comment]
@BenFradet what do you recommend for bad row reprocessing for the time being? Should we strip `f_wheel` and `f_passive` as part of extracting bad rows for reprocessing and stick with the current components?

**Comment by BenFradet** [comment]
unfortunately yes :disappointed:

**Comment by rgabo** [comment]
@BenFradet no worries, we have a Databricks notebook in place we've used for Invalid URI fixups in the past. Do you have an ETA for the patch? It would make sense for us to do the reprocessing once we stop accumulating bad rows. Thanks!

**Comment by BenFradet** [comment]
@mhadam can give a rough estimate

**Comment by mhadam** [comment]
I've got the patch done, should be able to get this out today.

**Comment by mhadam** [comment]
The new release is mirrored now.
