### ISSUE TITLE
Core: migrate addCommonContexts

### ISSUE THREAD

**Issue by mhadam** [snowplow/snowplow-javascript-tracker#664]

**Comment by alexanderdean** [comment]
Can you provide some context on this one?

**Comment by mhadam** [comment]
It's commented in this line:
https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L806

I think it should be easy to wrap this into the other work around sticky contexts, etc.

**Comment by alexanderdean** [comment]
So this ticket title - migrate what from where to where?

**Comment by mhadam** [comment]
Actually looking at it again, I think they intended to move the member variable `commonContexts` to the core, so that any call to `track` will send the common contexts additionally. Right now, every tracking function appends `commonContexts` to the ones supplied to the function.

I think a better title is something along the lines of "migrate commonContexts functionality from tracker into the core."

**Comment by alexanderdean** [comment]
Got it, sounds good
