### ISSUE TITLE
Remove outdated addClickListener method

### ISSUE THREAD

**Issue by mhadam** [snowplow/snowplow-javascript-tracker#667]
This seems to have been wrong for a while, it mustn't have been caught in refactoring. It provides three arguments when there should be one. The right function is now under `LinkTrackingManager`.

This line is the problem:
https://github.com/snowplow/snowplow-javascript-tracker/blob/89ed2d7bd4860a2814e52b38f121df8605768c2d/src/js/tracker.js#L1899

**Comment by alexanderdean** [comment]
What's the impact of this?

**Comment by mhadam** [comment]
As a public method, it doesn't do anything. It seems to have been broken a long time and throws the error `ReferenceError: addClickListener is not defined` when used.

**Comment by mhadam** [comment]
I'm going to remove this method, since it seems to break with the current structure of the tracker (i.e. the link tracking manager only has settings for all click link events).
