### ISSUE TITLE
Add main field to package.json in both repo and core

### ISSUE THREAD

**Issue by ladera** [snowplow/snowplow-javascript-tracker#683]
the main field is missing in the package.json file of both snowplow-tracker-core and snowplow-javascript-tracker. When importing into a typescript project it only has reference to main.d.ts and not the index.ts which is the actual module. To get around this have to import through file path instead like '../node_modules/snowplow-tracker-core/index'

**Comment by paulboocock** [comment]
This has been fixed in core/0.9.0. Will also be done in v3 of the JavaScript tracker when published to NPM.
