### ISSUE TITLE
Snowplow not tracking events in iframe which is being created dynamically.

### ISSUE THREAD

**Issue by datasleek** [snowplow/snowplow-javascript-tracker#715]
I have pasted a script given by survey monkey on my html page to show survey in a pop up window. Now the problem is whatever i am doing in survey is not being tracked by snowplow .Survey has 'Done' button.I want to track whether the visitor has clicked on that button on not but i cannot see any GET request by snowplow on my server whatever i do with survey.

Can you help me out what could be the possible reason for this ?
Following is the code that i have copy-pasted on html page.

          <script type="text/javascript" >
            var t=0;

              ;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];
                p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
                };p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
                n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","http://my_domain:80/static/sp.js","snowplow"));
                window.snowplow('newTracker', 'cf', 'my_domain:80', { // Initialise a tracker
                  encodeBase64: false, // Default is true
                  appId: 'CFe23a',
                   // Site ID can be anything you want. Set it if you're tracking more than one site in this account
                }
                      );
                window.snowplow('enableActivityTracking', 10, 20);
                window.snowplow('trackPageView',null);
                window.snowplow('enableLinkClickTracking');
                window.snowplow('trackStructEvent');

          </script> 
	
P.S: Please note that snowplow tracker is working absolutely fine for my html page if no survey pops up.

Thanks

**Comment by mhadam** [comment]
Unless I'm missing something, this should be possible with `refreshLinkClickTracking`, here's the documentation:

https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#392-refreshlinkclicktracking

We try to direct support questions toward our discourse forum, so in the future please raise stuff that isn't clearly a bug there:

https://discourse.snowplowanalytics.com/
