### ISSUE TITLE
Add option for page ping timer reset to trackPageView

### ISSUE THREAD

**Issue by regorsmitz** [snowplow/snowplow-javascript-tracker#717]
Currently if trackPageView is called in a context where the DOM has not been reloaded, the page ping timer does not reset. It would be helpful to have an optional argument to trackPageView to force the page ping timer to reset (so that the first page ping will once again happen after X seconds, where X is the timeout). 

By contrast, currently when the new page view happens (without a DOM reload), the timing of the first page pings depends on the interval between the current time and the last page ping on the previous page. As a result, time spent on page measurements based on page pings may be biased (due to different page ping intervals for page views when DOM is reloaded vs when it is not, for websites that mix one page app style page loads and full page loads).

**Comment by paulboocock** [comment]
Closing this in favour of #717 and the discussion that has happened there.
We'll be adding an optional argument to control the behaviour as suggested here to the fix for this.
