### ISSUE TITLE
Port to TypeScript

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#72]
See this intro here: http://10consulting.com/2012/10/12/introduction-to-typescript-presentation/

Porting to TypeScript is quite well aligned with the Snowplow tech goal of strongly typed data pipelines.

Unlike CoffeeScript, TS doesn't introduce any of its own design weirdnesses.

**Comment by chuwy** [comment]
See https://github.com/snowplow/snowplow-javascript-tracker/issues/526

**Comment by chuwy** [comment]
We even can publish definition files for stringly-typed method like `snowplow_name_here('trackEvent') https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/google.analytics/index.d.ts

**Comment by alexanderdean** [comment]
Cool idea!

**Comment by paulboocock** [comment]
Good opportunity to do this as we move to v3.
