### ISSUE TITLE
Method for deleting all local tracker storage (cookies and localStorage)

### ISSUE THREAD

**Issue by mhadam** [snowplow/snowplow-javascript-tracker#723]

**Comment by paulboocock** [comment]
We envision this being a new apiMethod defined in tracker.js. Maybe something along the lines of `clearStateStorage`. It should clear all snowplow tracker values in Cookies and Local Storage (Irrespective of the stateStorageStrategy) - it should only clear the ones that match the current domain hash.

**Comment by paulboocock** [comment]
This is now in v3.0.0
