### ISSUE TITLE
Why setCookiePath create a new cookie instead of setting path of existing cookie

### ISSUE THREAD

**Issue by unustalha** [snowplow/snowplow-javascript-tracker#724]
Hi
I am using snowplow version 2.10.2. I am trying to set cookie path but it create a new cookie instead of setting path of existing one.

```
window.snowplow('newTracker', 'default', 'PATH', {
    appId: 'manager',
    contexts: {webPage: true, gaCookies: true}
});
window.snowplow('setCookiePath', '/manager');
```

![Screen Shot 2019-05-27 at 12 31 31 PM](https://user-images.githubusercontent.com/1440559/58406773-68da9900-807b-11e9-85ab-84a5d7dd965f.png)

**Comment by paulboocock** [comment]
This occurs as the cookie path forms part of the domain hash (`05bf` and `a834`) in your case. We do this as the cookie should be tied to its path and we hash the domain so that multiple trackers can exist on the same page.
