### ISSUE TITLE
Why image name is forced to `i` 

### ISSUE THREAD

**Issue by allan-simon** [snowplow/snowplow-javascript-tracker#725]
is there a technical reason why the image must be `i` for sending the events through get ? 

https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/out_queue.js#L89

i.e it seems to me that it will not affect in a lot of place the code to make it  by default `i` and being able to customize it if needed. (for example in my case it's easier to filter access logs in GCP stackdriver, if i can say  "filter http logs that contains 'my_image_for_snowplow.png' " (as well as being self explained for ops guys who may wonder what this image is used for )

**Comment by mhadam** [comment]
No other than it's tracker protocol supported by our collectors. There's some discussion around allowing different paths for requests but, for the time being, we've mostly stuck with supporting the routes that are used by design.

**Comment by allanlegalstart** [comment]
yes but you agree with me that  permitting user to override it would not affect current user (that rely on `i`) being the default ?

**Comment by allanlegalstart** [comment]
i.e if i make a PR in that direction, will it be accepted ?

**Comment by kingo55** [comment]
IIRC, it was originally "ice.png" back in the day and they merely shortened it to ```i```:

https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/loaders/collectorPayloadSpecs.scala#L37

I think making it as short as possible meant we could stuff more characters into each GET request.

**Comment by paulboocock** [comment]
This isn't currently possible as our collectors only support `/i` for GET requests. Should we choose to decide to allow for custom paths on `/i` then this feature will be implemented in the trackers much like custom POST paths have been now that the collectors support them.
