### ISSUE TITLE
setOptOutCookie not working

### ISSUE THREAD

**Issue by awoehrl** [snowplow/snowplow-javascript-tracker#738]
Hi,

it seems, that the setting of an OptOutCookie is only working if stateStorageStrategy is "Cookie". It doesn't work if stateStorageStrategy is 'localStorage'.

Is this intended?

Best
Andreas

**Comment by paulboocock** [comment]
I have triaged this and don't believe it to be an issue.
I have test this with the following minimal implementation:
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <script type="text/javascript" async=1>
            ;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];
            p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
            };p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
            n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","sp.js","snowplow"));
        </script>
        <script>
            window.snowplow('newTracker', 'sp', '<<COLLECTORURL>>', {
                appId: 'cookie-test',
                eventMethod: 'post',
                stateStorageStrategy: 'localStorage',
                contexts: {
                    webPage: true,
                    performanceTiming: true
                }
            });
            window.snowplow('setOptOutCookie', 'spoptoutcookie');

            function setCookie() {
                document.cookie = 'spoptoutcookie=true';
            }
        </script>
    <body>
        <input type="button" onclick="setCookie()" value="Opt Out" />
        <input type="button" onclick="window.snowplow('trackPageView')" value="Track Page View" />
    </body>
</html>
```

Clicking the Track Page View works as expected and then once the Opt Out button is clicked, the Track Page View button will no longer send any events.

**Comment by bradgarropy** [comment]
Hey @paulboocock, really appreciate the minimal example!

How exactly are you confirming that no events are being sent? When I tried to run the example on my machine, I still saw entries in the Snowplow Chrome Extension and over the Network.

**Comment by paulboocock** [comment]
Hey @bradgarropy 

I'm confirming this using the Network tab in my browser (I also have Kibana open on a Snowplow Mini to ensure they aren't sent on subsequent Page Loads).

With the example above, if you are opening the file in your browser via a file:// url, then it will only work in Firefox. Chrome doesn't allow cookies on pages opened from local files unless they are being served by some sort of web server (so on http://127.0.0.1 or similar). 

As Chrome doesn't allow cookies on local files opened in the browser, the opt out cookie can't be set and the tracker will continue sending events. Try it in Firefox or pop the example above and sp.js into a Github pages repository https://pages.github.com/ to test in Chrome.

**Comment by bradgarropy** [comment]
Yep, I can see your example working when I spun up a local webserver.

We are using the `beacon` event method, does this cause any issue?

**Comment by bradgarropy** [comment]
Okay, figured out the issue. I was setting the cookie `mg_dnt` with no value. Once I set the value to `true` like you did in your example, things are now working as expected.

**Comment by paulboocock** [comment]
> We are using the `beacon` event method, does this cause any issue?

Just to confirm this will work fine with Beacon 🙂
