### ISSUE TITLE
Fix dynamic context callbacks sometimes returning null

### ISSUE THREAD

**Issue by max-tgam** [snowplow/snowplow-javascript-tracker#743]
I have noticed that in some cases result of user supplied function for custom context or custom context itself can be set to `null` instead of proper object. Since presence of one custom custom context not generally critical to event data - the data should not go into bad stream because logic sees `null` instead of context. 

The solution is to sanitize user supplied contexts for "falsy" values. 

In order to do that the following adjustments would be needed in `helpers.js` under `src/js/lib` sub-folder add following:
   - `filter = require("lodash/filter"),` line right after `map = require("lodash/map"),` line
   - Update `object.resolveDynamicContexts` function's return statement and wrap returning `map` function in `filter()` i.e to this:
```
return filter(map(dynamicOrStaticContexts, function(context) {
			if (typeof context === 'function') {
				try {
					return context.apply(null, params);
				} catch (e) {
					//TODO: provide warning
				}
			} else {
				return context;
			}
		}));
```

**Comment by max-tgam** [comment]
@colmsnowplow This is what I mentioned yesterday during the call.

**Comment by colmsnowplow** [comment]
Thanks @max-tgam

**Comment by max-tgam** [comment]
Just a bit more context - this causes issue with `link_click` tracking for us in some edge cases (what seems to be slower connection on Windows Chrome v49 and v74)

**Comment by max-tgam** [comment]
@colmsnowplow Do you want me to create PR for this?

**Comment by colmsnowplow** [comment]
@max-tgam - sorry I hadn't had a chance to take a closer look before. Thanks for the nudge. 

Yes if you'd like to create a PR I could get this into the next release. Thanks Max!

**Comment by colmsnowplow** [comment]
Suggested approach looks good.

**Comment by max-tgam** [comment]
@colmsnowplow I have PR ready but not sure where I should push it. When I try to push it to this repo I get permission denied message. Can you provide some guidance?

**Comment by colmsnowplow** [comment]
Hey @max-tgam 

All changes staged for the next release should go to the `develop` branch - I think you should be able to open a PR to that one, but please let me know if you have issues doing that.

**Comment by max-tgam** [comment]
@colmsnowplow I get 
`Permission to snowplow/snowplow-javascript-tracker.git denied to max-tgam.` message when I try to run `git push origin issue/743`

**Comment by jbeemster** [comment]
Hi @max-tgam to contribute to this repository you would need to first fork the tracker, push the changes to your fork and then open a PR from your fork back to this repository.

**Comment by max-tgam** [comment]
@jbeemster Thanks! I was able to create PR.

**Comment by max-tgam** [comment]
@szareiangm FYI
