### ISSUE TITLE
Switch to rollup and gulp

### ISSUE THREAD

**Issue by jamessnowplow** [snowplow/snowplow-javascript-tracker#752]
We should explore a move away from the current 'concat the iifes' bundling process to module bundling one.

Tools to try:
https://rollupjs.org/guide/en/
https://webpack.js.org

We might also want to take a look at exploring the [closure](https://developers.google.com/closure/compiler) compiler while we are there and evaluate its impact on bundle size.

**Comment by alexanderdean** [comment]
See also https://github.com/snowplow/snowplow-javascript-tracker/pull/677
