### ISSUE TITLE
jstimezonedetect package update (re #756)

### ISSUE THREAD

**Issue by jamessnowplow** [snowplow/snowplow-javascript-tracker#758]
We are a couple of minor versions behind on this one : https://www.npmjs.com/package/jstimezonedetect

Attempting the upgrade seemed to cause issues with browsers not supporting `Intl`. We should get to the bottom of the problem before we get too behind.

**Comment by paulboocock** [comment]
This is fixed in v3, upgraded when moving timezone capturing into a separate plugin.
