### ISSUE TITLE
Fix tracker continuing to insert events up to max Local Storage quota

### ISSUE THREAD

**Issue by paulboocock** [snowplow/snowplow-javascript-tracker#764]
**Affected Version:** `2.11.0`

**Description:** When an event is tracked, where available, it is stored temporarily in a Local Storage queue to later be sent in a batch. If an event fails to send (lack of connectivity, adblocker, etc.) then the event is placed back on to the local storage queue where it will be attempted to be sent again at the next opportunity.

If all events are unable to be sent then the Local Storage queue will continue to grow until it eventually becomes full and no further events can be added to Local Storage. At this stage, the browser begins to error - perhaps worse is that the tracker uses all the available Local Storage quota for the site, meaning that websites that rely on local storage to operate will begin to error.

**Suggested Fix:** As this is an edge case, most likely caused by adblockers, it seems sensible to drop events if local storage is full and to implement a limit to the amount of local storage quota the tracker will use. As users effected by this have an AdBlocker installed then the events would never be received by the collector so dropping them doesn't lead to any data loss.

**Comment by colmsnowplow** [comment]
Possible duplicate: #640
