### ISSUE TITLE
Fix example pages to use CDN hosted sp.js

### ISSUE THREAD

**Issue by paulboocock** [snowplow/snowplow-javascript-tracker#775]
The example pages don't currently work as they point to a non-existant sp.js file since it is no longer hosted on Cloudfront. 
This makes it unclear how to get the Example pages working correctly for newcomers and makes the example pages appear more broken than they are.

**Comment by paulboocock** [comment]
Once on NPM, we can us jsdelivr and unpkg to host sp.js. This will allow us to fix the example pages and offer a hosted version of sp.js again.

**Comment by alexanderdean** [comment]
Hey @paulboocock - there has been debate about whether to endorse a specific third-party hosting sp.js on account of reputational risk. Worth picking up with @goodits to see where that discussion ended up.
