### ISSUE TITLE
Potential Race Condition when loading different versions on the same page

### ISSUE THREAD

**Issue by paulboocock** [snowplow/snowplow-javascript-tracker#776]
It is currently possible to initialise the JavaScript tracker against multiple namespaces on the window object.

However, if different sp.js file versions are requested we have the potential to end up with a race condition where we can't guarentee which namespace will recieve which version of sp.js.

This stems from the fact that when we initialise the GlobalSnowplowNamespace in the javascript tag snippet, we place both namespaces onto this array. Then once one of the sp.js files loads, it will pop off a namespace from this queue and initialise the tracker.
As the sp.js files are loaded asynchronously, it is not guarenteed that the right namespace will be popped off the queue.

This can lead to tracker functions not being available or not behaving as expected when executed as there maybe differences between different versions of the JavaScript tracker. Additionally, this has the potential to lead to errors occuring when initialising the tracker if functions are not available, potentially leading to the initialisation queue not emptying and trackers not being set up correctly. We should look at improving the error handling and initialisation of the Snowplow object within init.js.

To resolve this, if you wish to use multiple versions of the sp.js file, you can load them synchronously and call the newTracker initialisation code in the same <script> tag or you can ensure you are using the same sp.js file across all namespaces.

**Comment by chuwy** [comment]
Isn't it the same as https://github.com/snowplow/snowplow-javascript-tracker/issues/560?

**Comment by paulboocock** [comment]
Yes it is. Closing this in favour of #560 and the discussion there.

**Comment by paulboocock** [comment]
> Isn't it the same as #560?

Yes it is. Closing this in favour of #560 and the discussion there.
