### ISSUE TITLE
Tracker report invalid refr value

### ISSUE THREAD

**Issue by dmalmkvist** [snowplow/snowplow-javascript-tracker#777]
We have observed that some events comes in with invalid `refr` value
```
"refr": "http://",
```

We have not been able to reproduce this and are not sure what browser this comes from. It have been observed on https://www.jetblue.com/

**Comment by paulboocock** [comment]
Hi @dmalmkvist 
We make a couple of attempts at finding the referer value:
https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/lib/helpers.js#L98

The most obvious way you could end up with an empty refr value, is if there is a query string `referer` value or if this is a Single Page App and you are not calling trackPageView on navigation events, then we may lose referer information (as this refreshes the referer information).

Without more details I'm not sure if this could be an implementation issue or if there is an issue with the trackers identification of referers. I'm leaning towards an implementation issue as this isn't something I've seen previously but it could be a particular browser not identifing referers in a way that our tracker appreciates. Any more information you have regarding this would be useful.

What version of the tracker are you using?
What type of events are you seeing incorrect refr values?
Is there a particular browser the events originate from where refr is not populated?
Is it a particular page that users are landing on that doesn't report the referer?

Lastly, if we believe this is an implementation issue then this may be better discussed on our Discourse where there is a more active community: https://discourse.snowplowanalytics.com/

**Comment by dmalmkvist** [comment]
Hi @paulboocock 

Thanks for the background, thats gives me some understanding on what is happening. Since the `refr` value can be taken from a query string there is no guarantee it will be a valid URL. 

In our case the event collector we use validate that the `refr` is a valid URL and rejects the event if it's not, this is to avoid having invalid data stored. 

What are your thoughts of having a similar URL validation in the tracker code to avoid sending invalid URLs in the event `refr`?

**Comment by paulboocock** [comment]
We try to limit logic like this in the tracker, as there might be a use case where someone wishes to track a non-url (or an invalid url) refr via the query string (Infact we know some users current do track invalid url characters and this would be a breaking changing for them). I appreciate this probably isn't ideal, particularly as the referer field should be a url. 

If this does pose you an issue in your data then we would suggest (as you already have alluded) that the best option is the validate this downstream - perhaps reject the event in a JS Enrichment or in a Data Modelling step.
