### ISSUE TITLE
Tracker send request with wrong Content-Type

### ISSUE THREAD

**Issue by dmalmkvist** [snowplow/snowplow-javascript-tracker#778]
We have received events from the tracker where the content type is not `application/json`, but instead `text/plain` or `application/x-www-form-urlencoded`.

It has been observed on Safari. 
UserAgent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15`

I'm not sure if this is an issue with the tracker or if this could be related to browser plugin / proxies etc that change content-type.

**Comment by paulboocock** [comment]
There is currently no way the tracker can POST an event without the Content-Type: application/json header attached. This is likely either being modified by a plugin as you suggest or could potentially be bot traffic (albeit with an odd User Agent for a bot).

The only other thing to consider, if you are using Beacon as the eventMethod then you may see odd events coming from Safari as Safari's Beacon implementation doesn't work correctly in older version. This is something we are currently invesitgating and can be tracked here: #751 
If this is the case, then I'd advise switching to using Post as the eventMethod until we resolve this in the next tracker release.
