### ISSUE TITLE
Develop easier options for cookieless tracking

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-javascript-tracker#793]
It is increasingly common for companies to want to:

* Do completely anonymous tracking i.e. track page views but no associated personal data (e.g. IP address, cookie IDs)
* Only track personal data where users have opted in

It would be great to better support both the above options easier with simple tracker initialization arguemnts.

**Comment by paulboocock** [comment]
Whilst this is achievable with the current tracker initialisation argmap, to switch from cookieless to with cookies on the same page you would need to initialise two trackers with different argmaps which does increase complexity. 

Potential route to this:
- Write better documentation on how to utilise the tracker in a cookieless manner (both now and updated in future)
- Allow for a argmap option that runs in cookieless/no local storage (i.e. `anonymousTracking: true`), this mode will win over other flags such as `stateStorageStrategy: 'cookie'`, and expose a new method that can flip the mode to "with personal data" tracking (i.e. `enableUserTracking()`) where we will then start sending IP Address, Cookie Ids etc with events.

Any thoughts on what we should name the flags/methods to make this clear?

**Comment by alexanderdean** [comment]
This ticket reminds of [this recent thread](https://www.linkedin.com/posts/peeplaja_abtesting-analytics-activity-6629378169382203392-5-HZ) between Peep and Simo:

<img width="494" alt="peep-simo-tracking" src="https://user-images.githubusercontent.com/200511/74071869-f5a46780-49fc-11ea-8a23-227ca843ad1c.png">

Preparing for this "black swan" scenario well ahead of time might be wise...
