### ISSUE TITLE
Add HTML5 Media Tracking plugin

### ISSUE THREAD

**Issue by paulboocock** [snowplow/snowplow-javascript-tracker#805]
Currently, tracking playback of videos has to be implemented manually. We could add automatic support for common video players (Youtube, Brightcove, ...). Functionality would be required to track playback progress, play, pause, stop.

New schemas would also be required for this functionality.

**Comment by alexanderdean** [comment]
I think this could be done more neatly with player-specific plugins. Those plugins could then be versioned with their associated data models, rather than the tracker - think 'Brightcove video analytics kit'.

**Comment by max-tgam** [comment]
I would be advising against this being a part of the core tracker like some current plugins currently are (e.g. Optimizely) and having pre-defined schemas. Here is why:

- Some built-in plugins like Optimizely is used by a very small fraction of tracker users but the plugin ships with a base tracker code bloating tracker size, resulting in us going into the code and manually stripping useless (for us) code out which creates room for error. Any vendor specific tracking should be optional to include in build process by defining build time variables.
- Schemas for the vendor specific tracking should not be defined by Snowplow but should be defined by people implementing tracking (not even vendors). Snowplow can provide a sample or "default" schema but it should be configurable what data to collect in that schema. For example, traditionally most video analytics implementations have play/pause/thresholds/completion event tracking - we only pick a few of those events to track videos and also have a few extra events that are specific to our needs that might not work for everyone.

**Comment by alexanderdean** [comment]
I think the nice thing about a true plugin (a built-in plugin is not a plugin!) approach is that it is forkable - think of the plugin+schemas as a kit that can be adapted and tailored to the specific company.

This would be a great starting point for the community, rather than each user having to write all of this from scratch...

**Comment by max-tgam** [comment]
I agree with "forkability" and stand-alone/template approach. 

Also some major API hooks for vendors is definitely good to have. I.e. this can have API hooks for YouTube/Brightcove/JWPlayer/HTML5video/etc players - that way it is all in one place and templated. As long as it is maintained and provides non-restrictive (in terms of data to capture/events to track) base - this would be a great addition.

**Comment by paulboocock** [comment]
So one of the idea's we're toying with in v3, it to have an interface that allows seperate "plugins" to interact with the Snowplow JavaScript Tracker. 
This would allow for the current "built in plugins" such as Optimizely to be removed through a flag at build time for sp.js (or in the case of NPM packages which we'll have in v3, not included in the app and therefore not added to the list of plugins).

I'm imagining something similar for this functionality, as @alexanderdean suggests - an analytics kit for a particular media player that you can add in and it is able to automatically work with the JS tracker on the page with little to no required input.

I think out of the box, these new "plugins" or "kits" would need to have Snowplow iglu-central hosted schemas as the default as we need it to work without users needing to create and upload their own schemas. However, I would like all the features to be customisable in some way (toggle on or off, add custom entities to specific events, etc.).

Thanks for the feedback, it's helping to shape what this might start to look like :-)

**Comment by alexanderdean** [comment]
That sounds great @paulboocock

**Comment by max-tgam** [comment]
Having non-core snowplow code as plugins would be amazing!
