### ISSUE TITLE
Allow alternative Access-Control-Allow-Credentials values

### ISSUE THREAD

**Issue by max-tgam** [snowplow/snowplow-javascript-tracker#808]
We had a security advisor company perform audit and they pointed out current potential vulnerability of snowplow collector code (for us risk is low but depending on case by case implementations could be high). They suggested that `Access-Control-Allow-Origin should` always be set to `*` but `Access-Control-Allow-Credentials` should always be set to `false` as that will ensure that attacker have absolutely no chance of stealing cookies.
This would require adjustment to `CollectorService.scala` to modify [this block](https://github.com/snowplow/snowplow/blob/3b8d9cc839e4af0b97c68477fb1c9f484de233e2/2-collectors/scala-stream-collector/core/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/CollectorService.scala#L416) as well as adding `Access-Control-Allow-Credentials` to header values.

**Comment by paulboocock** [comment]
Hi @max-tgam thanks for raising this. We'll look at triaging the impact of this change and how we could possibly roll it out.
