### ISSUE TITLE
Snowplow javascript tracker 2.14.0 not setting custom values

### ISSUE THREAD

**Issue by tatitati** [snowplow/snowplow-javascript-tracker#814]
I'm having a problem with snowplow tracker in javascript, with the version 2.14.0. We want to use the SameSite and CookieSecure option, however we are seeing some weird behaviour in this last version. For example we are trying this basic code to change the default name of the cookie:

```js
  snowplow("newTracker", "somethinghere", "somethingelse", {
    appId: appId,
    cookieDomain: cookieDomain,        
    cookieName: "mycookie1"
  });
```

We tried previous versions (2.6.2, and 2.10.0), they set the proper cookie name, however for 2.14.0 is not setting the cookieName indicated, but the default value `_sp_.....` 

We were suffering the same with CookieSecure or cookieSameSite (for these options only in the version 2.14.0 as they were introduced here)

I was using Chrome, with none plugins, and with none block-trackers

is this a bug? we are using it as specified here, but having a different behaviour:
https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#22-initialising-a-tracker

**Comment by paulboocock** [comment]
I've just created this minimal example, loaded 2.14.0 sp.js, and the cookieName is set as expected.

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <script type="text/javascript" async=1>
            ;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];
            p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
            };p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
            n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","sp.js","snowplow"));
        </script>
        <script>
            window.snowplow('newTracker', 'sp', '<<collector_url>>', {
                appId: 'test',
                cookieName: "mycookie1"
            });
            window.snowplow('trackPageView');
        </script>
    <body>
    </body>
</html>
```

Could you test if this works for you? If you are testing this as a local file, please bare in mind cookies won't work on file:// URLs within Chrome.

**Comment by tatitati** [comment]
I tried many times. I tested it for versions 2.10.0, 2.11.0, 2.12.0, 2.13.0, 2.14.0
I switched multiple times betwen 2.13.0 and 2.14.0. I saw my cookies appearing for 2.13.0 and not appearing with the proper name for 2.14.0. Always using incognito mode. I will try to provide screenshots

**Comment by paulboocock** [comment]
Try as I might, I'm unable to reproduce this across a variety of browsers. So far I've tested Firefox, Chrome, Edge, Safari across HTTPS and HTTP on a test bed site and snowplowanalytics.com. We also use custom cookie names on snowplowanalytics.com and JS Tracker 2.14.0 and the data there looks ok too.

Two things that might be at play here:
If you are seeing a cookie called `sp` this is likely the cookie from the collector. JS Tracker set cookies, by default, should look like `_sp.{hash}`.

From 2.14.0, the defaults for cookies have changed (to help with Chromiums SameSite changes) and will be `SameSite=None; Secure` by default. This means the cookies will not be stored in HTTP pages, only HTTPS pages with the default settings. If you set:
```
        cookieSameSite: null,
        cookieSecure: false
```
does this work for you? If so, in your original tests were you trying to test this on a page served via HTTP?

We dicussed these changes in more detail here: https://snowplowanalytics.com/blog/2020/03/05/snowplow-javascript-tracker-2.14.0-released/

Also, just to confirm did you download the 2.14.0 asset from here: https://github.com/snowplow/snowplow-javascript-tracker/releases/tag/2.14.0 ? Just confirming to make sure there are no moficiations to the tracker that you are using.

Lastly, I think to test this further I'm going to need a more complete example. Is there a public page anywhere that you are trying to get this working on or could you provide a Gist or GitHub Page with the issue?

**Comment by tatitati** [comment]
Yeah, after some debugging I confirm the special behaviour we are having is because of something in our side. Thanks for everything, there is no need to keep investigating. This issue can be closed.

Thanks @paulboocock for everything
