### ISSUE TITLE
Fix Missing Enhanced Ecommerce Contexts

### ISSUE THREAD

**Issue by seobrain** [snowplow/snowplow-javascript-tracker#851]
**Describe the bug**
We migrated from js-tracker v2.14 to v2.16.1, by just replacing the tracking library. And noticed that the EnhancedEcommerceProductContext is missing completely on add/remove/detail actions.

**To Reproduce**
Watch the tracking call payloads.

**Comment by paulboocock** [comment]
Thanks for raising the defect. I'll take a look at this.

**Comment by paulboocock** [comment]
https://github.com/snowplow/snowplow-javascript-tracker/releases/tag/2.16.2 is now available
