### ISSUE TITLE
Remove restriction on field lengths for focus_form events

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow-javascript-tracker#872]
The [schema](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/focus_form/jsonschema/1-0-0) for focus_form events restricts field lengths, where the equivalent in change_form or submit_form have no such restrictions. 

Suggest we update to a 1-0-1 which removes that restriction.

[Originally flagged on discourse](https://discourse.snowplowanalytics.com/t/enableformtracking-data-payload-issue-javascript/4521).

**Comment by paulboocock** [comment]
Will be resolved with https://github.com/snowplow/iglu-central/pull/1087
