### ISSUE TITLE
Cannot send any event with my custom schema

### ISSUE THREAD

**Issue by galkrisztina** [snowplow/snowplow-javascript-tracker#873]
Hi!
I am trying to send a self describing event via Snowplow as provided in the docs, with my custom schema, but it applies on the custom data the Snowplow's default schema (iglu:com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-4). My custom schema is not applied on the data unfortunatelly and I couldn't find any solution neither in the docs nor here between the existing issues. 
My tracker init and event sending looks like this:

```
snowplow_name_here('newTracker', 'sp', 'track.my-company-name.io', {
    appId: "cfe23a",
    platform: "web",
    contexts: {
        webPage: true,
        performanceTiming: true
    }
})

snowplow_name_here(
    'trackSelfDescribingEvent',
     {
         schema: 'iglu:my-company-name/event_name/jsonschema/1-0-0',
         data: { ... }
     }
);
```

The collector and the chema are both on AWS. My question is that am I doing something wrong? Why is it sending the event always with the custom schema? It doesn't give any errors. It would be helpful if you could give an answer.

Thanks,
Krisztina

**Comment by paulboocock** [comment]
Hi @galkrisztina 

Just a heads up that questions like this are usually best suited to our [Discourse community](https://discourse.snowplowanalytics.com/).

The `iglu:com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-4` schema is the wrapper schema for entire payload sent to the collector. Within that you'll find your self describing event, the `ue_*` property will always be wrapped in this schema for self describing events. By default this is base64 encoded in the `ue_px` property. If you don't want it to be base64 encoded, you can specify `encodeBase64: false` when initialising the tracker (where you specify `appId` and `platform`). If you disable base64 encoding then your data will be in the `ue_pr` property. You should then see your `iglu:my-company-name/event_name/jsonschema/1-0-0` schema and data is inside this in the payload to the collector.

Your payload should look something like this:

```
{
  "schema": "iglu:com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-4",
  "data": [
    {
      "e": "ue",
      "ue_pr": "{\"schema\":\"iglu:com.snowplowanalytics.snowplow/unstruct_event/jsonschema/1-0-0\",\"data\":{\"schema\":\"iglu:my-company-name/event_name/jsonschema/1-0-0\",\"data\":{\"example\":\"data\"}}}",
      "tv": "js-2.16.3",
      "tna": "sp",
      "aid": "simple-test",
      "p": "web",
      "tz": "Europe/London",
      "lang": "en-GB",
      "cs": "UTF-8",
      "res": "3440x1440",
      "cd": "24",
      "cookie": "1",
      "eid": "f36ba979-0cf9-4191-b57b-378d2fa48de5",
      "dtm": "1607331636911",
      "co": "{\"schema\":\"iglu:com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-0\",\"data\":[{\"schema\":\"iglu:com.snowplowanalytics.snowplow/web_page/jsonschema/1-0-0\",\"data\":{\"id\":\"b3173c4c-92bc-4a75-86c0-215b8079a389\"}}]}",
      "vp": "759x1313",
      "ds": "2008x2016",
      "vid": "1",
      "sid": "e0863358-bde7-4b74-8e46-dacee3516e7d",
      "duid": "caeb7815-93e1-4eb7-95b0-f686a193fb5f",
      "url": "http://www.website.com",
      "stm": "1607331640193"
    }
  ]
}
```

**Comment by galkrisztina** [comment]
@paulboocock thank you very much for your answer! I didn't find it nowhere unfortunately. Just a question then: so the logic has to be written in the collector to match the data with the sent schema after it decodes from the `ue_px` key?

**Comment by paulboocock** [comment]
The collector should write the event to an event stream (Kinesis, Kafka, PubSub) which should then be read by Snowplow Enrich which will validate the payload against all the schemas specified within the payload. Enrich will then output the validated event to the good or bad event streams depending on if it passed validation or not.
