### ISSUE TITLE
Set custom session id

### ISSUE THREAD

**Issue by louaig** [snowplow/snowplow-javascript-tracker#889]
Sometimes it's hard to connect two sessions in parent and child frames. It would be helpful if we can set the session ID if there's a public API for it, the same way setUserId behaves.

One could implement it using a different param, for example sending a custom made session ID of your own through track calls and make sure it's consistent for both instances of snowplow, but that would make the snoplow session ID not useful in the data analysis so why not set in the same way we do for the user Id.

Would love to hear your thoughts about this if there is any architectural complexity that would cause a misfunction to internal behavior.

Thanks!

**Comment by paulboocock** [comment]
I'd recommend you solve this with a [Custom Schema](https://docs.snowplowanalytics.com/docs/understanding-tracking-design/predefined-vs-custom-entities/#Custom_contexts) and attaching a "context" [to each event](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-tracker/tracking-specific-events/#Custom_contexts), either per event or by using [Global Contexts](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-tracker/tracking-specific-events/#Global_contexts). 

We won't be allowing users to change the built in session identifiers, this opens up too many doors for mistakes that can cause unexpected issues downstream and we're currently not looking to extend the atomic.events schema. This is why custom contexts exist, to allow you to extend the captured data with your own identifiers and data points.
