### ISSUE TITLE
Fix dynamic contexts not being evaluated on each page ping

### ISSUE THREAD

**Issue by CesarManriqueH** [snowplow/snowplow-javascript-tracker#891]
**Describe the bug**

According to the documentation [tracking-specific-events/#pageviews](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-tracker/tracking-specific-events/#pageviews)
> The page view and every subsequent page ping will have both a static_context and a dynamic_context attached. The static_contexts will all have the same staticValue, but the **dynamic_contexts will have different dynamicValues since a new context is created for every event.**

That is not how the tracker is working for page pings, dynamic contexts are evaluated when setting up the activity tracking interval hence all page pings contain the same values on their dynamic contexts. I think this goes against the purpose of dynamic context features.

**To Reproduce**

In order to reproduce the error you can use the same example from the documentation.

```javascript
// Turn on page pings every 10 seconds
snowplow('enableActivityTracking', 10, 10);

snowplow(
  'trackPageView',

  // no custom title
  null,

  // The usual array of static contexts
  [{
    schema: 'iglu:com.acme/static_context/jsonschema/1-0-0',
    data: {
      staticValue: new Date().toString()
    }
  }],

  // Function which returns an array of custom contexts
  // Gets called once per page view / page ping
  function() {
    return [{
      schema: 'iglu:com.acme/dynamic_context/jsonschema/1-0-0',
      data: {
        dynamicValue: new Date().toString()
      }
    }];
  }
);
```

**Current behavior**

Snowplow is sending a list of contexts with same values for all events, during my testing it sent this for all page views and page pings:
```
{
  "schema": "iglu:com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-0",
  "data":[
    {
      "schema": "iglu:com.acme/static_context/jsonschema/1-0-0",
      "data": { "staticValue": "Tue Feb 09 2021 12:29:58 GMT-0600 (Central Standard Time)"}
    },
    {
      "schema": "iglu:com.acme/dynamic_context/jsonschema/1-0-0",
      "data": { "dynamicValue": "Tue Feb 09 2021 12:29:58 GMT-0600 (Central Standard Time)" }
    }
  ]
}
```

**Expected behavior**

That all events (page view and page pings) have the same value for the static context is ok, that is what I'd expect.

On the other hand the value of `dynamicValue` should be different in every event. Since `minimumVisitLength=10` and `heartBeatDelay=10`, events should have a difference of approximately 10 seconds in relation to the order they are fired. I mean:

For page view, `dynamicValue` should be `Tue Feb 09 2021 12:29:58 GMT-0600 (Central Standard Time)`
For page ping #1, `dynamicValue` should be `Tue Feb 09 2021 12:30:08 GMT-0600 (Central Standard Time)`
For page ping #2, `dynamicValue` should be `Tue Feb 09 2021 12:30:18 GMT-0600 (Central Standard Time)`

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 88.0.4324

**Additional context**

I have already read some small parts of the tracker code and the problem is that `finalizeContexts` is passed to `activityInterval` function instead of being called from inside the setInterval callback.

I would like to know if you would be interested in changing this behavior, I think it would be great since dynamic contexts act pretty much like static contexts in page pings which makes impossible to add dynamic values on each page ping.

**Comment by paulboocock** [comment]
This looks like a regression in 2.13.0. I'll organise getting this fixed shortly and make a 2.17.2 release, unless you'd like to open a PR for it? It looks like moving `finalizeContexts()` into `activityInterval()` (and passing `contextCallback` into it) should be enough to resolve this.

**Comment by CesarManriqueH** [comment]
Hi @paulboocock. Thank you for your quick response!

I would like to open a PR for this.  Is it ok if I base my PR on tag 2.17.1?

**Comment by paulboocock** [comment]
Yep, basing it on 2.17.1 would be perfect. Thanks!
