### ISSUE TITLE
Remove Parrable browser plugin

### ISSUE THREAD

**Issue by icflournoy** [snowplow/snowplow-javascript-tracker#925]
Hi Snowplow, on behalf of Parrable I'd like to request that our browser plugin be removed.

It implements outdated functionality that we introduced 4 years ago (https://github.com/Parrable/snowplow-javascript-tracker/pull/1) and we have not had any installations using the Snowplow Parrable tracker in a long time.

Specifically, the functionality that the Parrable plugin provides is reading an optout cookie which has since been renamed from the value used here.

It appears that you're preparing the v3 release of this repo and now would be a good time to remove the plugin as it's part of the breaking version change.

I can put in the PR to remove our plugin, I just need to know where to look/remove things from. I've gathered this list:

- plugins/browser-plugin-parrable
- rush.json
- common/config/rush.json
- trackers/javascript-tracker/tracker.config.ts
- trackers/javascript-tracker/tracker.lite.config.ts
- trackers/javascript-tracker/configuration.js
- trackers/javascript-tracker/features.ts

I'm not familiar with Rush so if there is an easy command to remove ourselves from its config please let me know.

Finally, the npm (https://www.npmjs.com/package/@snowplow/browser-plugin-parrable) can be marked as depricated.

Feel free to reach out to me at ian@parrable.com with any questions.

**Comment by paulboocock** [comment]
Hi Ian, Thanks for the update. I've been struggling to find the history of the Parrable features so this is really useful. 

I think you've caught all the files that mention it there, I'm more than happy to accept a PR on this or I can remove it myself next week. 

There's no easy rush command to remove a package, so manually removing from rush.json and running `rush update` should do the trick, it'll likely update a couple of `common` files that should be in the PR. Removing usages from the other files you mention should be enough and the JavaScript trackers package.json.

**Comment by icflournoy** [comment]
Hi Paul, thanks for the affirmation on the list of files! I'll put in a PR in the next few days.

**Comment by paulboocock** [comment]
Marked as deprecated on npm: https://www.npmjs.com/package/@snowplow/browser-plugin-parrable
