### ISSUE TITLE
JavaScript tracker refreshLinkClickTracking is not an available function

### ISSUE THREAD

**Issue by blake-newman** [snowplow/snowplow-javascript-tracker#948]
**Describe the bug**
JavaScript Tracker:

> refreshLinkClickTracking is not an available function

Although documented to be available: 

https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/tracking-events/

**To Reproduce**
You can visit this page and observe in console that when you navigate page the warning appears. 

https://dashboard.askattest.com/survey/QEP79WBE9253XW/results

**Expected behavior**
For them method to be available and executed.

**Comment by paulboocock** [comment]
Hi @blake-newman 

I'm struggling to replicate this on my own sites and test beds, but I can definitely see it happening at the link you shared. However, the tracker doesn't seem to be behaving normally on that site so I have a feeling something else is going on.

For example, in DevTools running:

```
window.snowplow(function() { console.log(this); });
```

should print all the tracker instances, but it prints an empty object. This suggests the tracker hasn't been initialised yet.

Can you confirm you are calling `newTracker`? It will look something like this (you're configuration might be more complex than this, this is a minimal example):
e.g.
```
window.snowplow('newTracker', 'sp', '{{COLLECTOR_URL}}', {
  appId: 'askattest'
});
```

**Comment by blake-newman** [comment]
Yes this is a problem ourside :facepalm: sorry for the false issue
