### ISSUE TITLE
Split tracker.js in two

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-javascript-tracker#99]
We want to split `tracker.js` into:
1. An environment-agnostic tracker, for the purposes of this ticket let's call `AbsTracker`. Could be run from e.g. node.js (but won't be in this release)
2. A browser-specific tracker, let's call it `BrowseTracker` for now. This version uses `detectors.js` to detect things in the browser, fires page pings, wires into the DOM etc

Acceptance criteria for this ticket: when `AbsTracker` is fully unit testable from a server-side unit test (i.e. doesn't need to be run in a browser).

**Comment by paulboocock** [comment]
Close as we will be move to a module system in the near future (for v3). Probably end up with @snowplow/browser-tracker, @snowplow/nodejs-tracker and @snowplow/tracker-core.
