### ISSUE TITLE
Fix undefined argument regression in setUserId and setOptOutCookie

### ISSUE THREAD

**Issue by jethron** [snowplow/snowplow-javascript-tracker#991]
**Describe the bug**
Version 3 of the tracker behaves differently to v2 when passed `undefined` as an argument for some tracker commands.

In v3, setting the userId to `undefined` [triggers logic](https://github.com/snowplow/snowplow-javascript-tracker/blob/5172e2c5e46ba9611a97ca823b48938b1d16c6a9/trackers/javascript-tracker/src/in_queue.ts#L296) to replace it with a default value (an empty object), which is stringified and the user ID unexpectedly becomes the string value "[object Object]".

We have some implementations where the userId is pulled from the dataLayer and passed directly to the tracker via `setUserId`. In v2 this was fine because if the userId was missing from the dataLayer (it would be undefined), it would be ignored or cleared of its previous value. Subsequent events would not have the `uid` parameter attached.

We can fix this in the tagging side by checking the userId is defined before setting it. But it would be nice for the tracker to behave the (arguably less surprising) way that v2 did.

I'm not sure which interface this default was added to satisfy.

**To Reproduce**
Compare the user ID sent in the `uid` tracking protocol parameter after `snowplow('setUserId', undefined)`.
In theory it would have no value.
In practice it has the value `[object Object]`

**Expected behavior**
No `uid` parameter is sent because the user ID has no value when set to `undefined`.

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

**Comment by paulboocock** [comment]
Thanks for the report @jethron I'll resolve this asap.

**Comment by jethron** [comment]
Awesome, thanks @paulboocock! Love your work.
