### ISSUE TITLE
Add missing setter to detectPassiveEvents

### ISSUE THREAD

**Issue by StephenHonor** [snowplow/snowplow-javascript-tracker#995]
**Describe the bug**
There is an issue when trying to set the promise attribute of the options argument passed to the addEventListener function.

Because you do not have a setter and only a getter the browser errors when trying to set the value of passive within options.

This is the problem code within the detectPassiveEvents:
```
var options = Object.defineProperty({}, 'passive', {
    get: function get() {
        passive = true;
    }
});
```

**To Reproduce**
1. Override the addEventListener function
2. Within this function set the options.promise = false
3. Include the snowplow code

This is code taken from Magento:
```
let func = EventTarget.prototype.addEventListener;
EventTarget.prototype.addEventListener = function(type, fn, capture) {
    this.func = func;
    if (typeof capture !== "boolean") {
        capture = capture || {};
        capture.passive = false;
    }
    this.func(type, fn, capture);
}
...
// include snowplow javascript
```

**Expected behavior**
There should be no issue setting.

**Screenshots**
![image](https://user-images.githubusercontent.com/6010639/130094057-5b98e730-2a93-4567-a1ba-0925ec203a41.png)

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
All that needs adding is a set function and it'll fix the issue we're having and any other potential issues.

**Comment by paulboocock** [comment]
Thanks for the bug report @StephenHonor 

I'll look to get this resolved shortly. Open to a PR if you have time!

**Comment by StephenHonor** [comment]
https://github.com/snowplow/snowplow-javascript-tracker/pull/997
